<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/fullcalendar/fullcalendar.css" />
<form action="#" class="form" id="agendaConsulta">

	<input type="hidden" name="start" id="start">
	<input type="hidden" name="end" id="end">
	<input type="hidden" name="className" id="className">
	<input type="hidden" name="idevento" id="idevento">

	
	<div class="modal fade" id="modAgendarcon" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-lg">
	    <div class="modal-content">
	      	<div class="modal-header">
	        	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
	        	<h4 class="modal-title">
	        		Cita
	        	</h4>
	      	</div>
	      	<div class="modal-body">
	      		<div class="row">
	      			<div class="col-sm-4">
	      				<div class="form-group">
	      					<label>Fecha</label>
	      					<input class="form-control" type="date" id="cFecha">	
	      				</div>
	      				
	      			</div>
	      			<div class="col-sm-4">
	      				<div class="form-group">
	      					<label>Inicio:</label>
	      					<input class="form-control" type="time" id="desde">	
	      				</div>	      				
	      			</div>
	      			<div class="col-sm-4">
	      				<div class="form-group">
	      					<label>Fin: </label>
	      					<input class="form-control col-sm-4" type="time" id="hasta">	
	      				</div>	      				
	      			</div>	
	      		</div>      							
				<div class="row">
					<div class="col-sm-6">							
						<div class="form-group">
							<input type="text" class="form-control" id="title" name="title">
							<label for="title">PACIENTE</label>	
						</div>							
					</div>
					<div class="col-sm-3">
						<div class="form-group">
							<input type="text" class="form-control" id="edad" name="edad">
							<label for="edad">EDAD</label>	
						</div>						
					</div>
					<!-- <div class="col-sm-3" style="margin-bottom:10px">
					    <button id="bNuevopaciente" type="button" class="btn btn-default btn-raised glyphicon glyphicon-user" onclick="pacientesModal()" style="margin-top:23px;padding:6px 12px"> Registrar</button>
					</div> -->	
				</div>
				<div class="row">
					<div class="col-sm-6">
						<div class="form-group">
							<input type="text" class="form-control" name="referido" id="referidopor">
							<label for="referidopor">REFERIDO POR</label>	
						</div>							
					</div>
					<div class="form-group col-sm-4">
						<select name="scargo" class="form-control" id="sCargo">
							<option value="1">PARTICULAR</option>
							<option value="2">BANCO
							<option value="3">IMSS</option>
							<option value="4">CORTESÍA</option>
						</select>
						<label for="sCargo">CARGO</label>
					</div>												
				</div>										
				<div class="row">
					<div class="col-sm-6">
						<div class="form-group">
							<input type="text" class="form-control" id="telefono1" name="telefono1">
							<label for="telefono1">TELÉFONO 1</label>	
						</div>
						
					</div>
					<div class="col-sm-6">
						<div class="form-group">
							<input type="text" class="form-control" id="telefono2" name="telefono2">
							<label for="telefono2">TELÉFONO 2</label>	
						</div>						
					</div>					
				</div>						
	      	</div>
	      	<div class="modal-footer">
	      		<a href="#" onclick="borrarevento();" id="lBorrar" style="float:left">Eliminar evento</a>
	        	<button type="button" class="btn btn-primary" id="btnGuardarcita">GUARDAR</button>        
	      	</div>
	    </div>
	  </div>
	</div>
</form>


<div class="section-body">
	<div class="row">

		<!-- BEGIN CALENDAR EVENTS -->
		<div class="col-sm-3">
			<h2>Citas</h2>
			<p class="opacity-75">Por favor arrastre de la lista al calendario para planear sus próximas citas.</p>
			<br/>
			<br/>
			<ul class="list divider-full-bleed list-events">
				<li class="tile">
					<div class="tile-content">
						<div class="tile-text">Consulta de primera vez</div>
						<div class="tile-icon"><i class="fa fa-circle-thin text-primary"></i></div>
					</div>
				</li>
				<li class="tile" data-class-name="event-warning">
					<div class="tile-content">
						<div class="tile-text">Consulta de seguimiento</div>
						<div class="tile-icon"><i class="fa fa-circle-thin text-warning"></i></div>
					</div>
				</li>
				<li class="tile" data-class-name="event-blue">
					<div class="tile-content">
						<div class="tile-text">Retiro de Puntos</div>
						<div class="tile-icon"><i class="fa fa-circle-thin text-blue"></i></div>
					</div>
				</li>
				<li class="tile" data-class-name="event-success">
					<div class="tile-content">
						<div class="tile-text">Aplicación de Zoladex</div>
						<div class="tile-icon"><i class="fa fa-circle-thin text-success"></i></div>
					</div>
				</li>
				<li class="tile" data-class-name="event-rosa">
					<div class="tile-content">
						<div class="tile-text">Resultados</div>
						<div class="tile-icon"><i class="fa fa-circle-thin text-rosa"></i></div>
					</div>
				</li>
				<li class="tile" data-class-name="event-morado">
					<div class="tile-content">
						<div class="tile-text">Orden de Internamiento</div>
						<div class="tile-icon"><i class="fa fa-circle-thin text-accent"></i></div>
					</div>
				</li>
				<li class="tile" data-class-name="event-lima">
					<div class="tile-content">
						<div class="tile-text">Llenar Informe</div>
						<div class="tile-icon"><i class="fa fa-circle-thin text-lima"></i></div>
					</div>
				</li>
				<li class="tile" data-class-name="event-cafe">
					<div class="tile-content">
						<div class="tile-text">Procedimiento Especial</div>
						<div class="tile-icon"><i class="fa fa-circle-thin text-cafe"></i></div>
					</div>
				</li>
				<li class="tile" data-class-name="event-danger">
					<div class="tile-content">
						<div class="tile-text">Embarazo</div>
						<div class="tile-icon"><i class="fa fa-circle-thin text-danger"></i></div>
					</div>
				</li>
			</ul>
		</div><!--end .col -->
		<!-- END CALENDAR EVENTS -->
		<div class="col-sm-9">
			<div class="card">
				<div class="card-head style-primary">
					<header>
						<span class="selected-day">&nbsp;</span> &nbsp;<small class="selected-date">&nbsp;</small>
					</header>
					<div class="tools">
						<div class="btn-group">
							<a id="calender-prev" class="btn btn-icon-toggle ink-reaction"><i class="fa fa-angle-left"></i></a>
							<a id="calender-next" class="btn btn-icon-toggle ink-reaction"><i class="fa fa-angle-right"></i></a>
						</div>
						<div class="btn-group pull-right">
						</div>
					</div>
					<ul class="nav nav-tabs tabs-text-contrast tabs-accent" data-toggle="tabs">
						<li data-mode="month"><a href="#">Mes</a></li>
						<li data-mode="agendaWeek" class="active"><a href="#">Semana</a></li>
						<li data-mode="agendaDay"><a href="#">Día</a></li>
					</ul>
				</div><!--end .card-head -->
				<div class="card-body no-padding">
					<div id="calendar"></div>
				</div><!--end .card-body -->
			</div><!--end .card -->
		</div><!--end .col -->
		<!-- END CALENDAR -->

	</div><!--end .row -->
</div><!--end .section-body -->
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-ui/jquery-ui.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/fullcalendar/fullcalendar.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/exclie/agenda.js"></script>
<script>
	var ruta = '<?php echo $this->basePath(); ?>';

function borrarevento () {
	
	$.post('<?php echo $this->basePath() ?>/agenda/borrarevento',{id:$("#idevento").val()},
		function (data){
			location.reload();
	});
}
</script>