<div class="card">
	<div id="verpacientes">
		<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/wizard/wizard.css" />
		<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/jquery-ui/jquery-ui-theme.css" />
		<div class="card-head style-primary">
			<header>Registro de paciente</header>
		</div>
		<div class="card-body ">
			<div id="rootwizard1" class="form-wizard form-wizard-horizontal">
				<form id="formPac" class="form form-validate floating-label" novalidate="novalidate">
					<div class="form-wizard-nav">
						<div class="progress"><div class="progress-bar progress-bar-primary"></div></div>
						<ul class="nav nav-justified">
							<li class="active"><a href="#tab1" data-toggle="tab"><span class="step">1</span> <span class="title">GENERAL</span></a></li>
							<li><a href="#tab2" data-toggle="tab"><span class="step">2</span> <span class="title">ANTECEDENTES</span></a></li>
							<li><a href="#tab3" data-toggle="tab"><span class="step">3</span> <span class="title">ANTECEDENTES 2</span></a></li>
						</ul>
					</div><!--end .form-wizard-nav -->
					<div class="tab-content clearfix">
						<div class="tab-pane active" id="tab1">
							<div>
								<label class="radio-inline radio-styled">
									<input type="radio" name="SEXO" value="1"><span>MASCULINO</span>
								</label>
								<label class="radio-inline radio-styled">
									<input type="radio" name="SEXO" value="2" checked><span>FEMENINO</span>
								</label>
							</div>
							<br/>
							<div class="row">						
								<div class="col-sm-4">
									<div class="form-group floating-label">
										<input type="text" class="form-control input-lg" name="APELLIDO_PATERNO" id="Lastname1" required data-rule-minlength="2">
										<label for="Lastname1">APELLIDO PATERNO</label>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group floating-label">
										<input type="text" class="form-control input-lg" name="APELLIDO_MATERNO" id="Lastname1">
										<label for="Lastname1">APELLIDO MATERNO</label>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group floating-label">
										<input type="text" class="form-control input-lg" id="Firstname1" name="NOMBRE" required data-rule-minlength="2">
										<label for="Firstname1">NOMBRE(s)</label>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-4">
									<div class="form-group floating-label">
										<div class="input-group">
											<div class="input-group-content" id="demo-date-format">
												<input type="text" class="form-control" id="fecha_nacimiento" name="FECHA_NACIMIENTO">
												<label for="fecha_nacimiento">FECHA NACIMIENTO</label>
											</div>
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>
								</div>						
								<div class="col-sm-4">
									<div class="form-group floating-label">
										<select class="form-control input-lg" class="form-control input-lg" name="ESTADO" id="sEstados">
											<?php foreach ($estados as $key => $estado): ?>
												<option value="<?php echo $estado['ID'] ?>" 
												<?php if ($estado['ID'] == 8): // Chihuahua predefinido ?>
													selected
												<?php endif ?>><?php echo $estado['NOMBRE']; ?></option>
											<?php endforeach ?>
										</select class="form-control input-lg">
										<label for="Lastname1">CIUDAD</label>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group floating-label">
										<select class="form-control input-lg" class="form-control input-lg" name="MUNICIPIO" id="sEstados">
											<?php foreach ($municipios as $key => $municipio): ?>
												<option value="<?php echo $municipio['ID'] ?>" 
												<?php if ($municipio['ID'] == 233): // Chihuahua predefinido ?>
													selected	
												<?php endif ?>><?php echo $municipio['NOMBRE']; ?></option>
											<?php endforeach ?>
										</select class="form-control input-lg">
										<label for="Lastname1">MUNICIPIO</label>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-6">
									<div class="form-group floating-label">
										<input type="text" class="form-control input-lg" name="CALLE" id="Lastname1">
										<label for="Lastname1">CALLE</label>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="form-group floating-label">
										<input type="text" class="form-control input-lg" name="NUM_EXT" id="Lastname1">
										<label for="Lastname1">NUM EXT.</label>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="form-group floating-label">
										<input type="text" class="form-control input-lg" name="NUM_INT" id="Lastname1">
										<label for="Lastname1">NUM INT.</label>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-4">
									<div class="form-group floating-label">
										<input type="text" class="form-control input-lg" name="COLONIA" id="Lastname1">
										<label for="Lastname1">COLONIA</label>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group floating-label">
										<input type="text" class="form-control input-lg" name="TELEFONO1" id="Lastname1" data-inputmask="'mask': '(999) 999-9999'">
										<label for="Lastname1">TELÉFONO 1</label>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group floating-label">
										<input type="text" class="form-control input-lg" name="TELEFONO2" id="Lastname1" data-inputmask="'mask': '(999) 999-9999'">
										<label for="Lastname1">TELÉFONO 2</label>
									</div>
								</div>
							</div>
							<div class="row">						
								<div class="col-sm-4">
									<div class="form-group floating-label">
										<input type="text" class="form-control input-lg" name="OCUPACION" id="Lastname1">
										<label for="Lastname1">OCUPACIÓN</label>
									</div>
								</div>

								<div class="col-sm-4">
									<div class="form-group floating-label">
										<select class="form-control input-lg" class="form-control input-lg" name="ESTADO_CIVIL" id="sEstadocivil">
											<option value="1">Soltero(a)</option>
											<option value="2">Casado(a)</option>
											<option value="3">Viudo(a)</option>
										</select class="form-control input-lg">
										<label for="ESTADO_CIVIL">ESTADO CIVIL</label>
									</div>
								</div>
								
								<div class="col-sm-4">
									<div class="form-group floating-label">
										<select class="form-control input-lg" class="form-control input-lg" name="TIPO_SANGUINEO" id="sTipoSanguineo">
											<option value="9">Desconoce</option>
											<option value="1">O+</option>
											<option value="2">A+</option>
											<option value="3">O-</option>
											<option value="4">B+</option>
											<option value="5">A-</option>
											<option value="6">B-</option>
											<option value="7">AB+</option>
											<option value="8">AB-</option>
										</select class="form-control input-lg">
										<label for="TIPO_SANGUINEO">TIPO DE SANGRE</label>
									</div>
								</div>						
							</div>																				
						</div><!--end #tab1 -->

						<!-- EMPIEZAN ANTECEDENTES -->
						<div class="tab-pane" id="tab2">
							<h3>Por favor contesta lo siguiente:</h3>
							<div class="row">
								<div class="form-group col-sm-2">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divFuma">
											<span style="font-size:18px">FUMAS?</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-4 hidden" id="divFuma">
									<input type="text" id="verClase" class="form-control" name="TABAQUISMO">
									<label>QUE TANTO FUMAS?</label>
								</div>
								<div class="form-group col-sm-2">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divBebe">
											<span style="font-size:18px">BEBES ALCOHOL?</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-4 hidden" id="divBebe" >
									<input type="text" class="form-control" name="ALCOHOLISMO">
									<label>QUE TANTO BEBES ALCOHOL?</label>
								</div>											
							</div>
							<div class="row">
								<div class="form-group col-sm-2">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divDroga">
											<span style="font-size:18px">USAS ALGUNA DROGA?</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-4 hidden" id="divDroga" >
									<input type="text" class="form-control" name="TOXICOMANIAS">
									<label>CUAL(es) DROGA(s) USAS?</label>
								</div>
								<div class="form-group col-sm-2">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divCirugia">
											<span style="font-size:18px">HAS TENIDO CIRUGIAS?</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-4 hidden" id="divCirugia" >
									<input type="text" class="form-control" name="CIRUGIAS">
									<label>QUE CIRUGIAS?</label>
								</div>
							</div>
							<div class="row">
								<div class="form-group col-sm-2">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divAlergia">
											<span style="font-size:18px">TIENES ALERGIAS?</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-4 hidden" id="divAlergia" >
									<input type="text" class="form-control" name="ALERGIAS">
									<label>A QUÉ ERES ALÉRGICO?</label>
								</div>											
							</div>	
							
			
						</div><!--end #tab2 -->
						<div class="tab-pane" id="tab3">
							<h3>Alguno de tus parientes ha padecido de:</h3>
							<div class="row">
								<div class="form-group col-sm-2">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divDiabetes">
											<span style="font-size:18px">DIABETES</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-3 hidden" id="divDiabetes">
									<select class="form-control" name="DIABETES" id="sDiabetes">
										<option value="1">MADRE</option>
										<option value="2">PADRE</option>
										<option value="3">MADRE Y PADRE</option>
										<option value="4">ABUELA</option>
										<option value="5">ABUELO</option>
										<option value="6">ABUELA Y ABUELO</option>
									</select>
									<label>QUIEN PACEDE DIABETES?</label>
								</div>
								<div class="form-group col-sm-3">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divHipertension">
											<span style="font-size:18px">HIPERTENSIÓN</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-3 hidden" id="divHipertension" >
									<select class="form-control" name="HIPERTENSION" id="sHipertension">
										<option value="1">MADRE</option>
										<option value="2">PADRE</option>
										<option value="3">MADRE Y PADRE</option>
										<option value="4">ABUELA</option>
										<option value="5">ABUELO</option>
										<option value="6">ABUELA Y ABUELO</option>
									</select>
									<label>QUIEN PACEDE HIPERTENSIÓN?</label>
								</div>											
							</div>
							<div class="row">
								<div class="form-group col-sm-2">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divArtritis">
											<span style="font-size:18px">ARTRITIS</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-3 hidden" id="divArtritis" >
									<select class="form-control" name="ARTRITIS" id="sArtritis">
										<option value="1">MADRE</option>
										<option value="2">PADRE</option>
										<option value="3">MADRE Y PADRE</option>
										<option value="4">ABUELA</option>
										<option value="5">ABUELO</option>
										<option value="6">ABUELA Y ABUELO</option>
									</select>
									<label>QUIEN PACEDE ARTRITIS?</label>
								</div>
								<div class="form-group col-sm-3">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divTiroides">
											<span style="font-size:18px">ENFERMEDADES DE TIROIDES</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-3 hidden" id="divTiroides" >
									<select class="form-control" name="TIROIDES" id="sTiroides">
										<option value="1">MADRE</option>
										<option value="2">PADRE</option>
										<option value="3">MADRE Y PADRE</option>
										<option value="4">ABUELA</option>
										<option value="5">ABUELO</option>
										<option value="6">ABUELA Y ABUELO</option>
									</select>
									<label>QUIEN PACEDE DE TIROIDES?</label>
								</div>
							</div>
							<div class="row">
								<div class="form-group col-sm-2">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divCancer">
											<span style="font-size:18px">CANCER</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-3 hidden" id="divCancer" >
									<select class="form-control" name="CANCER" id="sCancer">
										<option value="1">MADRE</option>
										<option value="2">PADRE</option>
										<option value="3">MADRE Y PADRE</option>
										<option value="4">ABUELA</option>
										<option value="5">ABUELO</option>
										<option value="6">ABUELA Y ABUELO</option>
									</select>
									<label>QUIEN PACEDE CANCER?</label>
								</div>											
							</div>
							<div class="row">
								<div class="form-group col-sm-2">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divLupus">
											<span style="font-size:18px">LUPUS</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-3 hidden" id="divLupus" >
									<select class="form-control" name="LUPUS" id="sLupus">
										<option value="1">MADRE</option>
										<option value="2">PADRE</option>
										<option value="3">MADRE Y PADRE</option>
										<option value="4">ABUELA</option>
										<option value="5">ABUELO</option>
										<option value="6">ABUELA Y ABUELO</option>
									</select>
									<label>QUIEN PACEDE LUPUS?</label>
								</div>											
							</div>
							<div class="row">
								<div class="form-group col-sm-3">
									<div>
										<label class="checkbox checkbox-styled">
											<input type="checkbox" divref="divCardiacas">
											<span style="font-size:18px">ENFERMEDADES CARDIACAS</span>
										</label>												
									</div>		
								</div>
								<div class="form-group col-sm-3 hidden" id="divCardiacas" >
									<select class="form-control" name="CARDIACAS" id="sCardiacas">
										<option value="1">MADRE</option>
										<option value="2">PADRE</option>
										<option value="3">MADRE Y PADRE</option>
										<option value="4">ABUELA</option>
										<option value="5">ABUELO</option>
										<option value="6">ABUELA Y ABUELO</option>
									</select>
									<label>QUIEN PACEDE CARDIACAS?</label>
								</div>											
							</div>	
						</div><!--end #tab3 -->			
											
					</div><!--end .tab-content -->

					<ul class="pager wizard">									
						<li class="previous"><a class="btn-raised" href="javascript:void(0);">Atrás</a></li>									
						<li class="next"><a class="btn-raised" href="javascript:void(0);">Siguiente</a></li>
						<li class="next finish" style="display:none;"><a href="javascript:;">Guardar</a></li>
					</ul>
					
				</form>
			</div><!--end #rootwizard -->
		</div><!--end .card-body -->
	</div>
	<div id="capturando">
		<div class="card">
			<div class="card-head style-primary">
				<header>Agregar Consultas</header>
			</div>
			<div class="card-body">
				<div class="row">
					<div class="col-md-12">
						<form action="" id="formcapt" class="form form-validate" novalidate="novalidate">
							
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<input type="text" class="form-control" id="nombrePaciente" disabled="true">
										<label for="">Nombre del Paciente</label>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<input type="text" class="form-control" id="fecha_consulta" >
										<label for="fecha_consulta">Fecha de Consulta</label>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-head style-primary">
								<header>Subir Imagenes</header>
							</div>
							<div class="card-body no-padding">
								<form action="<?php echo $this->basePath() ?>/captura/guardarimagenescons" class="dropzone dz-clickable" id="dropa">
									<input type="hidden" id="idPaciente" name="idPaciente">
									<input type="hidden" id="fecha_consulta2" name="fecha_consulta">
									<div class="dz-message">
										<h3>Agrega aquí las imagenes</h3>
									</div>
								</form>
							</div><!--end .card-body -->
						</div><!--end .card -->
					</div>
				</div>
				<div class="card-actionbar">
					<div class="card-actionbar-row">
						<button type="button" class="btn btn-raised btn-primary ink-reaction" onclick="nuevoExpediente()" id="nuevoExp">Terminar</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/dropzone/dropzone-theme.css">
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/wizard/wizard.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/bootstrap-datepicker/datepicker3.css">
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/jquery-ui/jquery-ui-theme.css" />	
	
<script src="<?php echo $this->basePath() ?>/public/js/libs/dropzone/dropzone.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/wizard/jquery.bootstrap.wizard.min.js"></script>

<script src="<?php echo $this->basePath() ?>/public/js/exclie/pacientes.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/exclie/captura.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/core/demo/DemoFormWizard.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-ui/jquery-ui.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/inputmask/jquery.inputmask.bundle.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/moment/moment.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/bootstrap-datepicker/bootstrap-datepicker.js"></script>



	<script>
	$(document).ready(function() {
		$('#capturando').hide();


		$("#fecha_consulta").keyup(function () {
	        var valorfec = $('#fecha_consulta').val();
	        $("#fecha_consulta2").val(valorfec);
    	
    	});
    
   	});
	var _ruta = '<?php echo $this->basePath(); ?>';	
	
	$('#rootwizard1 .finish').click(function() {
			
		var formulario = $('#formPac').serialize();
		$.ajax({
		    type: "POST",
		    url: "<?php echo $this->basePath() ?>/captura/guardarpaciente",
		    dataType: "json",
		    data: formulario,
		    success: function(respuesta) {
		       $("#verpacientes").hide();
		       $('#capturando').show();
		       idPaciente = respuesta.id;
		       nombrepac = respuesta.nombre;		       
			   $('#idPaciente').val(idPaciente);
			   $('#nombrePaciente').val(nombrepac);
		    },
		    error: function(){
		          alert('Ocurrió un error, inténtelo más tarde.');
		    }
		});
		
		
	});

	function nuevoExpediente(){
		window.location.href = _ruta+'/captura';
	}

	</script>