<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-1/libs/rickshaw/rickshaw.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-1/libs/morris/morris.core.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/estilos.css" />

<script src="<?php echo $this->basePath() ?>/public/js/core/demo/Demo.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/sparkline/jquery.sparkline.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/d3/d3.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/d3/d3.v3.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/rickshaw/rickshaw.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.time.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.resize.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.orderBars.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.pie.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/curvedLines.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/spin.js/spin.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-knob/jquery.knob.min.js"></script>
    

    <div class="section-body">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <br>
                    <!-- BEGIN ALERT - BOUNCE RATES -->
                    <div class="row">
                        <div class="col-md-4">
                            <a href="<?php echo $this->basePath() ?>/captura/registro" >
                            <div class="card card-bordered style-primary">
                                <div class="card-body">
                                    <strong class="pull-right text-xl"><i class="fa fa-user-plus fa-2x"></i></strong>
                                    <strong class="text-xl">Registro de Pacientes</strong><br/>
                                </div><!--end .card-body -->
                            </div><!--end .card -->
                            </a>
                        </div><!--end .col -->
                        <div class="col-md-4">
                            <a href="<?php echo $this->basePath() ?>/captura/listadepacientes" >
                            <div class="card card-bordered style-primary">
                                <div class="card-body">
                                    <strong class="pull-right text-xl"><i class="fa fa-list-alt fa-2x"></i></strong>
                                    <strong class="text-xl">Lista de Pacientes</strong><br/>
                                </div><!--end .card-body -->
                            </div><!--end .card -->
                            </a>
                        </div>
                        <div class="col-md-4">
                            <a href="<?php echo $this->basePath() ?>/captura/verexpediente" >
                            <div class="card card-bordered style-primary">
                                <div class="card-body">
                                    <strong class="pull-right text-xl"><i class="fa fa-file-text fa-2x"></i></strong>
                                    <strong class="text-xl">Ver Expediente</strong><br/>
                                </div><!--end .card-body -->
                            </div><!--end .card -->
                            </a>
                        </div><!--end .col -->
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <a href="<?php echo $this->basePath() ?>/captura/pacienteduplicado" >
                            <div class="card card-bordered style-primary">
                                <div class="card-body">
                                    <strong class="pull-right text-xl"><i class="fa fa-users fa-2x"></i></strong>
                                    <strong class="text-xl">Pacientes Duplicados</strong><br/>
                                </div><!--end .card-body -->
                            </div><!--end .card -->
                            </a>
                        </div>
                        <div class="col-md-4"></div>
                        <div class="col-md-4"></div>
                    </div>
                </div>
            </div>
        </div><!--end .row -->
    </div>