<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/bootstrap-datepicker/datepicker3.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/estilos.css" />

<div class="card">

	<!-- COMIENZA CABECERA  -->
	<div class="card-head style-primary-dark">
		<div class="tools">
			<a class="btn btn-icon-toggle ink-reaction" href="#datosgenerales" data-toggle="offcanvas">
                <i class="fa fa-user"></i>
            </a>
		</div><!--end .tools -->
	</div><!--end .card-head -->
	<!-- TERMINA CABECERA -->

	<!-- BEGIN CONTACT DETAILS -->
	<div class="card-tiles">
		<div class="hbox-md col-md-12">
			<div class="hbox-column col-md-9">
				<div class="row">

					<!-- COMIENZA LISTADO CASOS -->
					<div class="col-sm-5 col-md-4 col-lg-3" >
						<div class="card tabs-left style-default-light scroll height-18">
							<ul data-toggle="tabs" class="card-head nav nav-tabs">
								<li class="active"><a href="#listaTiroides">Tiroides</a></li>
								<li class=""><a href="#listaSenos">Senos</a></li>
								<li class=""><a href="#listaOvarios">Ovarios</a></li>
								<li class=""><a href="#listaEndometriosis">Endometriosis</a></li>
								<li class=""><a href="#listaLiquido">Liquido Libre</a></li>
								<li class=""><a href="#listaMioma">Miomas</a></li>
								<li class=""><a href="#listaPolipos">Polipos</a></li>
								<li class=""><a href="#listaHematometria">Hematometria</a></li>
								<li class=""><a href="#listaHiperplasia">Hiperplasia</a></li>
							</ul>
							<div class="card-body tab-content style-default-bright">
								<div id="listaTiroides" class="tab-pane active">
									<div class="list-results list-results-underlined">
										<div class="col-xs-12" onclick="tipotiroides('normal');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="" >
											<p>Tiroides Normal</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipotiroides('ganglio');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Tiroides Ganglio</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipotiroides('dolor');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Tiroides Dolor</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipotiroides('nodulo');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Tiroides Nodulo</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipotiroides('quiste');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Tiroides Quiste</p>
										</div><!--end .col -->
									</div>
								</div>
								<div id="listaSenos" class="tab-pane">
									<div class="list-results list-results-underlined">
										<div class="col-xs-12" onclick="tipoSenos('normal');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Senos Normal</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('quiste');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Senos Quiste</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('zona-dura');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Senos Zona Dura</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('dolor');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Senos Dolor</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('ganglio');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Senos Ganglio</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('multiples-quistes');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Senos Multiples Quistes</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('izq-operado');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Seno Izq. Operado Cancer</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('der-operado');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Seno Der. Operado Cancer</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('protesis');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Senos Prótesis</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('ambos-operados');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Senos operados Cancer (Ambos)</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('der-secrecion');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Seno Der. Salida Secrecíon/Leche </p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('izq-secrecion');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Seno Izq. Salida Secreción/Leche </p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoSenos('ambos-secrecion');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Senos Secreción/Leche (Ambos)</p>
										</div><!--end .col -->
									</div>
								</div>
								<div id="listaOvarios" class="tab-pane">
									<div class="list-results list-results-underlined">
										<div class="col-xs-12" onclick="tipoOvary('normal');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Ovario Normal con Ovulación</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('sin-ovulacion');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario sin ovulación</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('menopausica');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Mujer Menopausica</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('solo-der');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Derecho (Solo)</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('solo-izq');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Izquierdo (Solo)</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('no-ovarios');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>No Ovarios</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('poliq-tipo1');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Sindrome Ovario Poliquístico Tipo I</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('poliq-tipo2');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Sindrome Ovario Poliquístico Tipo II</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('poliq-tratamiento');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Sindrome Ovario Poliquístico con tratamiento (mejoría)</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('quiste-simple');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Quiste simple</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('der-quistesimple');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Der. Quiste simple</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('izq-quistesimple');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Izq. Quiste simple</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('der-quistepapilas');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Der. Quiste con papilas/increcencias</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('izq-quistepapilas');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Izq. Quiste con papilas/increcencias</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('der-quistesolido');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Der. Quiste Sólido</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('der-quisteliquido');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Der. Quiste Sólido y líquido libre</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('izq-quistesolido');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Izq. Quiste Sólido</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('izq-quisteliquido');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Izq. Quiste Sólido y líquido libre</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('der-endometrioma');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Der. Endometrioma</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('izq-endometrioma');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Izq. Endometrioma</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('der-teratoma');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Der. Teratoma</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('izq-teratoma');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Izq. Teratoma</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('quiste-simplebilateral');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Quistes simple bilateral</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('quiste-papilasbilateral');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Quistes con papilas e increcencias bilateral</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('teratoma-bilateral');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Teratoma Bilateral</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('endometrioma-bilateral');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Endometrioma Bilateral</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('solo-der');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Sólo Ovario Derecho</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('solo-izq');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Sólo Ovario Izquierdo</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('no-ovarios');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>No Ovarios</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('liquido-libre');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Ovario Líquido libre</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoOvary('hiperestimulacion');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Sindrome Ovarica de Hiperestimulación</p>
										</div><!--end .col -->
									</div>
								</div>
								<div id="listaEndometriosis" class="tab-pane">
									<div class="list-results list-results-underlined">
										<div class="col-xs-12" onclick="tipoCervix('grado1');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Endometriosis Grado I</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoCervix('grado2');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Endometriosis Grado II</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoCervix('grado3');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Endometriosis Grado III</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoCervix('grado4');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Endometriosis Grado IV</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoCervix('adenomiosis');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Adenomiosis</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoCervix('adeno-endo1');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Adenomiosis y Endometriosis Grado I</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoCervix('adeno-endo2');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Adenomiosis y Endometriosis Grado II</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoCervix('adeno-endo3');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Adenomiosis y Endometriosis Grado III</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoCervix('adeno-endo4');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img12.jpg" alt="">
											<p>Adenomiosis y Endometriosis Grado IV</p>
										</div><!--end .col -->
									</div>
								</div>
								<div id="listaLiquido" class="tab-pane">
									<div class="list-results list-results-underlined">
										<div class="col-xs-12" onclick="tipoLiquido('libre');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Líquido libre</p>
										</div><!--end .col -->
									</div>
								</div>
								<div id="listaMioma" class="tab-pane">
									<div class="list-results list-results-underlined">
										<div class="col-xs-12" onclick="tipoMioma('subseroso');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Mioma Subseroso</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoMioma('intramural');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Mioma Intramural</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoMioma('intra-subseroso');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Mioma Intracavitario Subseroso</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoMioma('multiples-elem');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Mioma de Múltiples elementos</p>
										</div><!--end .col -->
									</div>
								</div>
								<div id="listaPolipos" class="tab-pane">
									<div class="list-results list-results-underlined">
										<div class="col-xs-12" onclick="tipoPolipo('unico');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Pólipo Único</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoPolipo('multiple');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Pólipo Múltiple</p>
										</div><!--end .col -->
									</div>
								</div>
								<div id="listaHematometria" class="tab-pane">
									<div class="list-results list-results-underlined">
										<div class="col-xs-12" onclick="tipoHematometria('hema');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Hematometría</p>
										</div><!--end .col -->
										<div class="col-xs-12" onclick="tipoHematometria('diu');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>DIU IN SITU</p>
										</div><!--end .col -->
									</div>
								</div>
								<div id="listaHiperplasia" class="tab-pane">
									<div class="list-results list-results-underlined">
										<div class="col-xs-12" onclick="tipoHiperplasia('hiper');">
											<img class="pull-left width-2" src="<?php echo $this->basePath() ?>/public/img/img11.jpg" alt="">
											<p>Hiperplasia</p>
										</div><!--end .col -->
									</div>
								</div>
							</div><!--end .card-body -->
						</div>
					</div><!--end .col -->
					<!-- TERMINA LISTADO CASOS -->

					<!-- BEGIN CONTACTS MAIN CONTENT -->
					<div class="col-sm-7 col-md-8 col-lg-9">
						<div class="margin-bottom-xxl">
							
							<?php if(!isset($paciente)){ ?>
								<h1 class="text-light no-margin"><?php echo "No hay paciente definido"; ?></h1>
							<?php }else{ ?>
							<h1 class="text-light no-margin"><?php echo $paciente[0]['NOMBRE'].' '.$paciente[0]['APELLIDO_PATERNO'].' '.$paciente[0]['APELLIDO_MATERNO']; ?></h1>

							<?php } ?>
							&nbsp;&nbsp;
						</div><!--end .margin-bottom-xxl -->
						<ul class="nav nav-tabs" data-toggle="tabs">
							<li class="active"><a href="#addconsulta">CONSULTA</a></li>
							<li><a href="#notes">NOTAS</a></li>
						</ul>
						<div class="tab-content">
							<!-- COMIENZA NOTAS PACIENTE -->
							<div class="tab-pane" id="notes">
								<br/>
								<form class="form" id="formNotes" accept-charset="utf-8" method="post">
									<div class="form-group">
										<textarea id="summernote" name="message" class="form-control control-3-rows" placeholder="Agregar una nota ..." spellcheck="false"></textarea>
									</div>
									<div class="form-group clearfix">
										<button type="submit" class="btn btn-raised btn-primary pull-right">Agregar</button>
									</div>
								</form>
								<div class="list-results list-results-underlined">
									<div class="col-xs-12">
										<p class="clearfix">
											<span class="fa fa-fw fa-file-o fa-2x pull-left"></span>
											<span class="pull-left">
												<span class="text-bold">Saturday, Oktober 18, 2014</span><br/>
												<span class="opacity-50">Note by Daniel Johnson.</span>
											</span>
										</p>
										<div>
											<em>"It looks like he wanted our help and there is an opening here."</em>
										</div>
									</div><!--end .col -->
									<div class="col-xs-12">
										<p class="clearfix">
											<span class="fa fa-fw fa-envelope-o fa-2x pull-left"></span>
											<span class="pull-left">
												<span class="text-bold">Tuesday, Juli 08, 2011</span><br/>
												<span class="opacity-50">Email via Ann Laurens.</span><br/>
												<span class="opacity-50">Subject: Can we meet tomorrow and come to a decision?</span>
											</span>
										</p>
										<div>
												<p>
													Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
												</p>
												<p>
													Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
												</p>
												<p>
													Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra..
												</p>
										</div>
									</div><!--end .col -->
									<div class="col-xs-12">
										<p class="clearfix">
											<span class="fa fa-fw fa-file-o fa-2x pull-left"></span>
											<span class="pull-left">
												<span class="text-bold">Wednesday, May 28, 2014</span><br/>
												<span class="opacity-50">Note by Daniel Johnson.</span>
											</span>
										</p>
										<div>
											<em>There should be a meeting scheduled soon.</em>
										</div>
									</div><!--end .col -->
								</div><!--end .list-results -->
							</div><!--end #notes -->
							<!-- TERMINA NOTAS PACIENTE -->

							<!-- BEGIN ADDCONSULTA DETAILS -->
							<div class="tab-pane active" id="addconsulta">
								<br>
								<form class="form form-validate" id="formConsul" novalidate="novalidate">
									<div class="card">
										<input type="hidden" name="idpac" value="<?php echo $paciente[0]['ID']; ?>">
										<div class="card-body ">
											<div class="row">
												<div class="col-md-7">
													<div class="form-group">
														<input type="text" class="form-control" id="motivo" name="motivo">
														<label for="Firstname2">Motivo Consulta</label>
													</div>
												</div>
												<div class="col-md-2"></div>
												<div class="col-md-3">
													<div class="form-group">
														<input type="text" class="form-control" id="fechahoy" name="fechahoy">
														<label for="fechahoy">Fecha</label>
													</div>
												</div>
											</div>
											<div class="row">
												<div class="col-sm-4">
													<div class="form-group">
														<input type="text" class="form-control" id="edad" name="edad">
														<label for="edad">Edad</label>
													</div>
													<div class="form-group">
														<input type="text" class="form-control" id="ciclo" name="ciclo">
														<label for="ciclo">Ciclo</label>
													</div>
													<div class="form-group">
														<input type="text" class="form-control" id="fum" name="fum">
														<label for="fum">FUM</label>
													</div>
													<div class="row">
														<div class="col-sm-3">
															<div class="form-group">
																<input type="text" class="form-control" id="gestas" name="gestas" data-rule-number="true">
																<label for="gestas">G</label>
															</div>
														</div>
														<div class="col-sm-3">
															<div class="form-group">
																<input type="text" class="form-control" id="partos" name="partos">
																<label for="partos">P</label>
															</div>
														</div>
														<div class="col-sm-3">
															<div class="form-group">
																<input type="text" class="form-control" id="cesarea" name="cesarea">
																<label for="cesarea">C</label>
															</div>
														</div>
														<div class="col-sm-3">
															<div class="form-group">
																<input type="text" class="form-control" id="abortos" name="bortos">
																<label for="abortos">A</label>
															</div>
														</div>
													</div>
												</div>
												<div class="col-sm-5"></div>
												<div class="col-sm-3">
													
													<div class="form-group">
														<input type="text" class="form-control" id="tiroidestxt" name="tiroidestxt">
														<label for="tiroidestxt">Tiroides</label>
													</div>
													<div class="form-group">
														<input type="text" class="form-control" id="peso" name="peso">
														<label for="peso">Peso</label>
													</div>
													<div class="form-group">
														<input type="text" class="form-control" id="presion" name="presion">
														<label for="presion">Presión</label>
													</div>
												</div>
											</div>
											<hr>
											<div class="row">
												<div class="col-md-9">
													<div class="card">
														<div class="card-head style-primary-dark">
															<header>Tiroides</header>
														</div>
														<div class="card-body height-8" id="TiroidesImagen"></div>
													</div>
												</div>
												<div class="col-md-3">
													<div class="card">
														<div class="card-head style-primary-dark">
															<header>Datos Tiroides</header>
														</div>
														<div class="card-body height-8">
															<div class="form-group">
																<textarea name="notasts" id="notasts" class="form-control" rows="3" placeholder=""></textarea>
																<label for="notasts">Notas</label>
															</div>
														</div>
													</div>
												</div>
												
												
											</div>
											<div class="row">
												<div class="col-md-9">
													<div class="card">
														<div class="card-head style-primary-dark">
															<header>Senos</header>
														</div>
														<div class="card-body height-8" id="SenosImagen"></div>
													</div>
												</div>
												<div class="col-md-3">
													<div class="card">
														<div class="card-head style-primary-dark">
															<header>Datos Senos</header>
														</div>
														<div class="card-body height-8">
															<div class="form-group">
																<input type="text" class="form-control" id="tamanoq" name="tamanoq">
																<label for="tamanoq">Tamaño</label>
															</div>
															<div class="form-group">
																<input type="text" class="form-control" id="numeroq" name="numeroq">
																<label for="numeroq">Numero</label>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="row">
												<div class="col-md-9">
													<div class="card">
														<div class="card-head style-primary-dark">
															<header>Cervix</header>
														</div>
														<div class="card-body height-8" id="CervixImagen">
															
														</div>
													</div>
												</div>
												<div class="col-md-3">
													<div class="card">
														<div class="card-head style-primary-dark">
															<header>Datos Cervix</header>
														</div>
														<div class="card-body height-8">
															<div class="form-group">
																<textarea name="notascx" id="notascx" class="form-control" rows="3" placeholder=""></textarea>
																<label for="notascx">Notas</label>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="row">
												<div class="col-md-9">
													<div class="card">
														<div class="card-head style-primary-dark">
															<header>Ovarios</header>
														</div>
														<div class="card-body height-8" id="OvariosImagen">
															
														</div>
													</div>
												</div>
												<div class="col-md-3">
													<div class="card">
														<div class="card-head style-primary-dark">
															<header>Datos Ovarios</header>
														</div>
														<div class="card-body height-8">
															<div class="form-group">
																<input type="text" class="form-control" id="medidao" name="medidao">
																<label for="medidao">Medida</label>
															</div>
															<div class="form-group">
																<label class="col-sm-9 control-label">Cápsula</label>
																<div class="col-sm-9">
																	<label class="radio-inline radio-styled">
																		<input type="radio" name="capsula" value="si"><span>Sí</span>
																	</label>
																	<label class="radio-inline radio-styled">
																		<input type="radio" name="capsula" value="no"><span>No</span>
																	</label>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="row">
												<div class="col-md-9">
													<div class="card">
														<div class="card-head style-primary-dark">
															<header>Cuello</header>
														</div>
														<div class="card-body height-8">
															
														</div>
													</div>
												</div>
												<div class="col-md-3">
													<div class="card">
														<div class="card-head style-primary-dark">
															<header>Datos Cuello</header>
														</div>
														<div class="card-body height-8">
															<div class="form-group">
																<textarea name="notascllo" id="notascllo" class="form-control" rows="3" placeholder=""></textarea>
																<label for="notascllo">Notas</label>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="row">
												<div class="col-md-12">
													<div class="form-group">
														<textarea name="plan" id="plan" class="form-control" rows="3" placeholder=""></textarea>
														<label for="plan">Plan</label>
													</div>
												</div>
											</div>
										</div><!--end .card-body -->
										<div class="card-actionbar">
											<div class="card-actionbar-row">
												<button type="button" class="btn btn-raised btn-primary ink-reaction" onclick="guardarconsulta()">Guardar</button>
											</div>
										</div>
									</div><!--end .card -->
									
								</form>
								
								</div>
							</div><!--end #details -->
							<!-- END ADDCONSULTA DETAILS -->
						</div><!--end .tab-content -->
					</div><!--end .col -->
					<!-- END CONTACTS MAIN CONTENT -->
				</div><!--end .row -->
			</div><!--end .hbox-column -->
		</div><!--end .hbox-md -->
	</div><!--end .card-tiles -->
	<!-- END CONTACTS DETAILS -->
	<div class="offcanvas backdrop">
		<!-- BEGIN CONTACTS COMMON DETAILS -->
		<div id="datosgenerales" class="offcanvas-pane width-8">
			<div class="offcanvas-head">
                <header class="text-primary">Información del Paciente</header>
                <div class="offcanvas-tools">
                    <a class="btn btn-icon-toggle btn-default-light pull-right" data-dismiss="offcanvas">
                        <i class="md md-close"></i>
                    </a>
                </div>
            </div>
            <div class="offcanvas-body no-padding">
				<div class="hbox-column col-md-12 style-default-light">
					<div class="row">
						<div class="col-xs-12">
							<h4>Datos Personales</h4>
							<br/>
							
							<?php if(!isset($paciente)){ ?>
								<span class="text-medium style-warning">No hay usuario seleccionado</span>
							<?php }else{ ?>
							<div class="width-3 clearfix hidden-xs">
								<?php if(!isset($paciente) || $paciente[0]['IMAGEN'] == '')  {  ?>
									<img alt="" src="<?php echo $this->basePath(); ?>/public/img/avatar7.jpg" class="img-circle size-2">
								<?php } else  {?>
									 <img  src="<?php echo $this->basePath().'/public/imagenes/Pacientes/'.$paciente[0]['ID'].'/'.$paciente[0]['IMAGEN'];?>"  class="img-circle size-2" >
                          		<?php } ?> 
							</div>
							<dl class="dl-horizontal dl-icon">
								<dt><span class="fa fa-fw fa-gift fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Años</span><br/>
									<span class="text-medium" id="Edad"></span>
								</dd>
								<dt><span class="fa fa-fw fa-home fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Dirección</span><br/>
									<span class="text-medium"><?php echo $paciente[0]['CALLE']; ?>&nbsp;<?php echo $paciente[0]['NUMERO_EXT']; ?></span><br>
									<span class="text-medium"><?php echo $paciente[0]['COLONIA']; ?></span><br>
									<span class="text-medium"><span class="opacity-50">C.P. </span><?php echo $paciente[0]['CODIGO_POSTAL']; ?></span>
								</dd>
								<dt><span class="fa fa-fw fa-home fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Tipo Sanguíneo</span><br/>
									<span class="text-medium"><?php echo $paciente[0]['CALLE']; ?></span>
								</dd>
							</dl><!--end .dl-horizontal -->
							<?php } ?>
							<br/>
							<h4>Antecedentes</h4>
							<br/>
							<?php if(!isset($paciente)){ ?>
								<span class="text-medium style-warning">No hay usuario seleccionado</span>
							<?php }else{ ?>
							<dl class="dl-horizontal dl-icon">
								<dt><span class="fa fa-fw fa-mobile fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Tabaquismo</span><br/>
									<span class="text-medium">233-332-342</span> &nbsp;<span class="opacity-50">work</span><br/>
									<span class="text-medium">766-766-4532</span> &nbsp;<span class="opacity-50">mobile</span>
								</dd>
								<dt><span class="fa fa-fw fa-envelope-square fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Toxicomanias</span><br/>
									<a class="text-medium" href="../../../html/mail/compose.html">philip@Ericsson.com</a>
								</dd>
								<dt><span class="fa fa-fw fa-location-arrow fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Alcoholismo</span><br/>
									<a class="text-medium" href="../../../html/mail/compose.html">philip@Ericsson.com</a>
								</dd>
								<dt><span class="fa fa-fw fa-location-arrow fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Aumento/Perdida de Peso</span><br/>
									<a class="text-medium" href="../../../html/mail/compose.html">philip@Ericsson.com</a>
								</dd>
								<dt><span class="fa fa-fw fa-location-arrow fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Alergias</span><br/>
									<a class="text-medium" href="../../../html/mail/compose.html">philip@Ericsson.com</a>
								</dd>
								<dt><span class="fa fa-fw fa-location-arrow fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Cirugias</span><br/>
									<a class="text-medium" href="../../../html/mail/compose.html">philip@Ericsson.com</a>
								</dd>
							</dl><!--end .dl-horizontal -->
							<?php } ?>
						</div><!--end .col -->
					</div><!--end .row -->
				</div><!--end .hbox-column -->
			</div>
		</div>
		<!-- END CONTACTS COMMON DETAILS -->	
	</div>
</div>
<div id="respuesta" style="display:none">Se guardó</div>
  

<script src="<?php echo $this->basePath() ?>/public/js/libs/moment/moment.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/bootstrap-datepicker/bootstrap-datepicker.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-validation/dist/additional-methods.min.js"></script>

<script>

	$(document).ready(function() {

		$('#edad').val(getEdad('<?php echo date_format($paciente[0]["FECHA_NACIMIENTO"],"Y-m-d") ?>'));
    	$("#Edad").text(getEdad('<?php echo date_format($paciente[0]["FECHA_NACIMIENTO"],"Y-m-d") ?>')+' años');
    	fechaActual();
    	
    
   	});
	$('#fum').datepicker();
	

	function tipotiroides(tipo){

		document.getElementById("TiroidesImagen").innerHTML="";

		if(tipo == 'normal'){
			var imagen = 'img2.jpg';
			$('#TiroidesImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#TiroidesImagen').append('<input type="hidden" name="imgtiroides" value="'+imagen+'">');
		}
		if(tipo == 'ganglio'){
			var imagen = 'img2.jpg';
			$('#TiroidesImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#TiroidesImagen').append('<input type="hidden" name="imgtiroides" value="'+imagen+'">');
		}
		if(tipo == 'dolor'){
			var imagen = 'img2.jpg';
			$('#TiroidesImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#TiroidesImagen').append('<input type="hidden" name="imgtiroides" value="'+imagen+'">');
		}
		if(tipo == 'nodulo'){
			var imagen = 'img2.jpg';
			$('#TiroidesImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#TiroidesImagen').append('<input type="hidden" name="imgtiroides" value="'+imagen+'">');
		}
		if(tipo == 'quiste'){
			var imagen = 'img2.jpg';
			$('#TiroidesImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#TiroidesImagen').append('<input type="hidden" name="imgtiroides" value="'+imagen+'">');
		}
	}

	function tipoSenos(tipo){

		document.getElementById("SenosImagen").innerHTML="";

		if(tipo == 'normal'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'quiste'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'zona-dura'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'dolor'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'ganglio'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'multiples-quistes'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'izq-operado'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'der-operado'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'protesis'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'ambos-operados'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'der-secrecion'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'izq-secrecion'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
		if(tipo == 'ambos-secrecion'){
			var imagen = 'img1.jpg';
			$('#SenosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#SenosImagen').append('<input type="hidden" name="imgsenos" value="'+imagen+'">');
		}
	}

	function tipoOvary(tipo){

		document.getElementById("OvariosImagen").innerHTML="";

		if(tipo == 'normal'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'sin-ovulacion'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'menopausica'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'solo-der'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'solo-izq'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'no-ovarios'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'poliq-tipo1'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'poliq-tipo2'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'poliq-tratamiento'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'quiste-simple'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'der-quistesimple'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'izq-quistesimple'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'der-quistepapilas'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'izq-quistepapilas'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'izq-quistesolido'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'izq-quisteliquido'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'der-quistesolido'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'der-quisteliquido'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'izq-endometrioma'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'der-endometrioma'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'izq-teratoma'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'der-teratoma'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'quiste-simplebilateral'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'quiste-papilasbilateral'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'teratoma-bilateral'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'endometrioma-bilateral'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'solo-izq'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'solo-der'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'no-ovarios'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'liquido-libre'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
		if(tipo == 'hiperestimulacion'){
			var imagen = 'img6.jpg';
			$('#OvariosImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#OvariosImagen').append('<input type="hidden" name="imgovarios" value="'+imagen+'">');
		}
	}

	function tipoLiquido(tipo){
		document.getElementById("CervixImagen").innerHTML="";

		if(tipo == 'libre'){
			var imagen = 'img3.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
	}

	function tipoCervix(tipo){
		document.getElementById("CervixImagen").innerHTML="";

		if(tipo == 'grado1'){
			var imagen = 'img7.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'grado2'){
			var imagen = 'img7.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'grado3'){
			var imagen = 'img7.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'grado4'){
			var imagen = 'img7.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'adenomiosis'){
			var imagen = 'img7.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'adeno-endo1'){
			var imagen = 'img7.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'adeno-endo2'){
			var imagen = 'img7.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'adeno-endo3'){
			var imagen = 'img10.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'adeno-endo4'){
			var imagen = 'img10.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
	}

	function tipoMioma(tipo){
		document.getElementById("CervixImagen").innerHTML="";

		if(tipo == 'subseroso'){
			var imagen = 'img12.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'intramural'){
			var imagen = 'img13.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'intra-subseroso'){
			var imagen = 'img13.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'multiples-elem'){
			var imagen = 'img13.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
	}

	function tipoPolipo(tipo){
		document.getElementById("CervixImagen").innerHTML="";

		if(tipo == 'unico'){
			var imagen = 'img12.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'multiple'){
			var imagen = 'img12.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
	}

	function tipoHematometria(tipo){
		document.getElementById("CervixImagen").innerHTML="";

		if(tipo == 'hema'){
			var imagen = 'img12.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
		if(tipo == 'diu'){
			var imagen = 'img12.jpg';
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"' />");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}
	}

	function tipoHiperplasia(tipo){
		document.getElementById("CervixImagen").innerHTML="";

		if(tipo == 'hiper'){
			var imagen = 'img12.jpg';
			
			$('#CervixImagen').append("<img src='<?php echo $this->basePath(); ?>/public/img/"+imagen+"'/>");
			$('#CervixImagen').append('<input type="hidden" name="imgcervix" value="'+imagen+'">');
		}	
		
		
	}

	function getEdad(fechanac){
		var hoy = new Date();
    	var fechaNacimiento = new Date(fechanac);
    	var edad = hoy.getFullYear() - fechaNacimiento.getFullYear();
    	var m = hoy.getMonth() - fechaNacimiento.getMonth();
    	if (m < 0 || (m === 0 && hoy.getDate() < fechaNacimiento.getDate())) {
        	edad--;
    	}
    	return edad;
	}

	function fechaActual(){
		var today = new Date();
	    var dd = today.getDate();
	    var mm = today.getMonth()+1; 
	    var yyyy = today.getFullYear();

	    if(dd<10){
	        dd='0'+dd
	    } 
	    if(mm<10){
	        mm='0'+mm
	    } 
	    var today = dd+'-'+mm+'-'+yyyy;

	    $('#fechahoy').val(today);
	}

	function guardarconsulta(){
		var formulario = $('#formConsul').serialize();
		$.ajax({
           type: "POST",
           url: "<?php echo $this->basePath() ?>/consultados/guardarconsulta",
           data: formulario,
           dataType: "JSON",
           
           success: function(data) {
               $("#respuesta").fadeIn(5000);
           },
           error: function(){
                 alert('Inténtalo más tarde.');
           }
       });
	}

	
  
</script>