<div class="container">
		<div id="multi" style="margin-left: 30px">
			<div><div data-force="5" class="layer title title_xl">Multi</div></div>

			<div class="layer tile" data-force="30">
				<div class="tile__name">Group A</div>
				<div class="tile__list">
					<img src="st/face-01.jpg"><!--
					--><img src="st/face-02.jpg"><!--
					--><img src="st/face-03.jpg"><!--
					--><img src="st/face-04.jpg">
				</div>
			</div>

			<div class="layer tile" data-force="25">
				<div class="tile__name">Group B</div>
				<div class="tile__list">
					<img src="st/face-05.jpg"><!--
					--><img src="st/face-06.jpg"><!--
					--><img src="st/face-07.jpg">
				</div>
			</div>

			<div class="layer tile" data-force="20">
				<div class="tile__name">Group C</div>
				<div class="tile__list">
					<img src="st/face-08.jpg"><!--
					--><img src="st/face-09.jpg">
				</div>
			</div>

		</div>
	</div>