<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/estilos.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/jquery-ui/jquery-ui-theme.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/bootstrap-datepicker/datepicker3.css" />
<div class="card">

	<!-- COMIENZA CABECERA  -->
	<div class="card-head style-primary-dark">
		<div class="tools">
			<a class="btn btn-icon-toggle ink-reaction" href="#datosgenerales" data-toggle="offcanvas">
                <i class="fa fa-user"></i>
            </a>
		</div>
	</div>
	<div class="card-body">
		<div class="row">
			<!-- BEGIN CONTACTS MAIN CONTENT -->
			<div class="col-md-12">
				<!-- COMIENZA DATOS PACIENTE -->
				<div class="margin-bottom-xxl">
					<?php if(!isset($paciente)){ ?>
						<h1 class="text-light no-margin"><?php echo "No hay paciente definido"; ?></h1>
					<?php }else{ ?>
					<h1 class="text-light no-margin"><?php echo $paciente[0]['NOMBRE'].' '.$paciente[0]['APELLIDO_PATERNO'].' '.$paciente[0]['APELLIDO_MATERNO']; ?></h1>

					<?php } ?>
					&nbsp;&nbsp;
				</div>
				<!-- COMIENZA NAVEGACION -->
				<ul class="nav nav-tabs" data-toggle="tabs">
					<li id='licons' class="active"><a href="#addconsulta">CONSULTA</a></li>
					<li id='lireproduccion'><a href="#reproduccion">REPRODUCCIÓN ASISTIDA</a></li>
					<li><a href="#notes">NOTAS</a></li>
					<li id="lirecetas"><a href="#recetas">RECETAS</a></li>
					<li><a href="#histoAntes">Historial Anterior</a></li>
					<li><a href="#videos">Videos</a></li>
				</ul>
				<div class="tab-content">
					<!-- COMIENZA NOTAS PACIENTE -->
					<div class="tab-pane" id="notes">
						<br/>
						<form class="form" id="formNotes" accept-charset="utf-8" method="post">
							<div class="form-group">
								<textarea id="recordar" name="recordar" class="form-control control-3-rows" placeholder="Agregar una nota ..." spellcheck="false"></textarea>
							</div>
							<div class="form-group clearfix">
								<button type="button" class="btn btn-raised btn-primary pull-right" onclick="guardarNota()">Agregar</button>
							</div>
						</form>
						<div id="resultaNotas">
						
						</div>
					</div>
					
					<!-- COMIENZA REPRODUCCION ASISTIDA -->
					<div class="tab-pane" id="reproduccion">
						<div id="monito"></div>
					</div>
										
					<!-- BEGIN HISTORIAL ANTERIOR  -->
					<div class="tab-pane" id="histoAntes">
						<br/>
						<!-- BEGIN FILE UPLOAD -->
						<div class="row">
							<?php if(isset($paciente))  {  ?>
								<br/>
								<?php if(!isset($files) || $files == ''){ echo 'No hay Archivos' ; } else{ ?>
							
										<div class="list-results list-results-underlined">
											<div class="col-xs-12">
												<div id="links" class="links">
													<div id="resultaArchivos"></div>
													<div id="blueimp-gallery" class="blueimp-gallery">
													    <div class="slides"></div>
													    <h3 class="title"></h3>
													    <a class="prev">‹</a>
													    <a class="next">›</a>
													    <a class="close">×</a>
													    <a class="play-pause"></a>
													    <ol class="indicator"></ol>
													</div>
												</div>
											</div>
										</div>
								<?php } ?>
								<div class=" col-md-12">
									<div class="card">
										<div class="card-head style-primary">
											<header>Subir Archivos</header>
										</div>
										<div class="card-body no-padding">
											<form action="<?php echo $this->basePath() ?>/consultados/guardahistoanterior" class="dropzone dz-clickable" id="drops">
												<input type="hidden" id="patient" name="patient" value= <?php echo $paciente[0]['ID'];?> >
												<div class="dz-message">
													<h3>  Agrega los expedientes  <br/><br/></h3>
												</div>
											</form>
										</div>
									</div>
								</div>
							<?php } ?>
						</div>
					</div>
					<!-- END HISTORIAL ANTERIOR -->

					<!--Inicio mostrar videos -->
					<div class="tab-pane" id="videos">
						<br/>
						<!-- BEGIN FILE UPLOAD -->
						<div class="row">
								<?php if(isset($paciente))  {  ?>
								<br/>
									<?php if(!isset($videos) || $videos == ''){ echo 'No hay Videos' ; } else{ ?>
											<div id="resultaVideos"></div>
											<div id="blueimp-video-carousel" class="blueimp-gallery blueimp-gallery-controls blueimp-gallery-carousel">
											    <div class="slides"></div>
											    <h3 class="title"></h3>
											    <a class="prev">‹</a>
											    <a class="next">›</a>
											    <a class="play-pause"></a>
											</div>
										
									<?php } ?>
						
									<div class=" col-md-12">
										<div class="card">
											<div class="card-head style-primary">
											
												<header>Subir Videos</header>
											</div>
											<div class="card-body no-padding">
												<form action="<?php echo $this->basePath() ?>/consultados/guardarvideo" class="dropzone dz-clickable" id="dropa">
												<input type="hidden" id="pacid" name="pacid" value= <?php echo $paciente[0]['ID'];?> >
												<div class="dz-message">
													<h3 >Agrega aquí los videos  <br/><br/></h3>
												</div>
												</form>
											</div>
										</div>
									</div>
								<?php } ?>
						</div>
					</div>
					
					<!-- BEGIN ADDCONSULTA DETAILS -->
					<div class="tab-pane active" id="addconsulta">
						<br>
						<div class="">
							<button type="button" class="btn ink-reaction btn-raised btn-sm btn-primary pull-left" onclick="repasistida();">Monitoreo</button>		
						</div>
						<br>
						<br>
						<form enctype="multipart/form-data" class="form form-validate" id="formConsul" novalidate="novalidate" action="" method="POST">
							<input type="hidden" name="idconsg" id="idconsg">
							
						<?php if(isset($consultas)){ $numero_consul = count($consultas);} ?>
							<!-- COMIENZA CONSULTA DE SEGUIMIENTO -->
							<?php if($numero_consul >= '1'){ ?>
							<div class="card">
								
								<input type="hidden" name="idpac" value="<?php echo $paciente[0]['ID']; ?>">
								<input type="hidden" name="tipocons" value="1">
								<input type="hidden" name="imagen" id="hImagen">
								<div class="card-body ">
									<div class="row">
										<div class="col-md-7">
											<div class="form-group">
												<input type="text" class="form-control" id="motivo" name="motivo">
												<label for="Firstname2">Motivo Consulta</label>
											</div>
										</div>
										<div class="col-md-2"></div>
										<div class="col-md-3">
											<div class="form-group">
												<input type="text" class="form-control" id="fechahoy" name="fechahoy">
												<label for="fechahoy">Fecha</label>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-4">
											<div class="form-group">
												<div class="input-group">
													<div class="input-group-content">
														<input type="text" class="form-control" id="edad" name="edad">
														<label for="edad">Edad</label>
													</div>
													<span class="input-group-addon">años</span>
												</div>
											</div>
											<div class="form-group">
												<input type="text" class="form-control" id="ciclo" name="ciclo" data-inputmask="'mask': '99X99 '">
												<label for="ciclo">Ciclo</label>
											</div>
											<div class="form-group">
												<input type="text" class="form-control" id="fum" name="fum">
												<label for="fum">FUM</label>
											</div>
											<div class="row">
												<div class="col-sm-2">
													<div class="form-group">
														<input type="text" class="form-control" id="gestas" name="gestas" data-rule-number="true">
														<label for="gestas">G</label>
													</div>
												</div>
												<div class="col-sm-2">
													<div class="form-group">
														<input type="text" class="form-control" id="partos" name="partos">
														<label for="partos">P</label>
													</div>
												</div>
												<div class="col-sm-2">
													<div class="form-group">
														<input type="text" class="form-control" id="cesarea" name="cesarea">
														<label for="cesarea">C</label>
													</div>
												</div>
												<div class="col-sm-2">
													<div class="form-group">
														<input type="text" class="form-control" id="abortos" name="bortos">
														<label for="abortos">A</label>
													</div>
												</div>
												<div class="col-sm-2">
													<div class="form-group">
														<input type="text" class="form-control" id="ectopicos" name="ectopicos">
														<label for="ectopicos">E</label>
													</div>
												</div>
											</div>
										</div>
										<div class="col-sm-5"></div>
										<div class="col-sm-3">
											<div class="form-group">
												<div class="input-group">
													<div class="input-group-content">
														<input type="text" class="form-control" id="tiroidestxt" name="tiroidestxt">
														<label for="tiroidestxt">Tiroides</label>
													</div>
													<span class="input-group-addon">ml U/L</span>
												</div>
											</div>
											<div class="form-group">
												<div class="input-group">
													<div class="input-group-content">
														<input type="text" class="form-control" id="peso" name="peso">
														<label for="peso">Peso</label>
														</div>
													<span class="input-group-addon">Kg</span>
												</div>
											</div>
											<div class="form-group">
												<div class="input-group">
													<div class="input-group-content">
														<input type="text" class="form-control" id="presion" name="presion">
														<label for="presion">Presión</label>
														</div>
													<span class="input-group-addon">mmHg</span>
												</div>
											</div>
											<div class="form-group">
												<div class="pull-right">
												<button type="button" class="btn ink-reaction btn-floating-action btn-lg btn-primary" id="tomarFotos"><i class="fa fa-camera"></i></button>
												</div>
												<div id="wrapper">
													
												    <br />
												    <div id="image-holder" ></div>
												</div>
											</div>
										</div>
									</div>
									<hr>
									
									<div class="row">
										<!-- BEGIN CANVAS -->
										<div class="card-tiles">
											<div style="overflow: hidden; margin-bottom: 5px;">
												<div class="column-right links" id="colores">
													<strong>COLORES:</strong>
														<button type="button" onclick='$("#test").data("jqScribble").update({brushColor: "rgb(32,37,43)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-default-dark fa fa-pencil" data-toggle="tooltip" data-original-title="Negro"></button>
														<button type="button" onclick='$("#test").data("jqScribble").update({brushColor: "rgb(244,67,54)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-danger fa fa-pencil" data-toggle="tooltip" data-original-title="Rojo"></button>
														<button type="button" onclick='$("#test").data("jqScribble").update({brushColor: "rgb(76,175,80)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-success fa fa-pencil" data-toggle="tooltip" data-original-title="Verde"></button>
														<button type="button" onclick='$("#test").data("jqScribble").update({brushColor: "rgb(33,150,243)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-info fa fa-pencil" data-toggle="tooltip" data-original-title="Azul"></button>
														<button type="button" onclick='$("#test").data("jqScribble").update({brushColor: "rgb(255,255,255)",brushSize:"30"});' class="btn ink-reaction btn-raised btn-sm btn-default-bright fa fa-eraser" data-toggle="tooltip" data-original-title="Borrador"></button>
												</div>
											</div>
											<div class="row">
												<canvas id="test"></canvas>
											</div>
											
											<!-- END CANVAS  -->
											<div class="row">
												<div class="col-md-6">
													<div class="form-group">
														<input type="text" class="form-control" id="imx" name="imx">
														<label for="imx">Idx</label>
													</div>
												</div>
												<div class="col-md-6">
													<div class="form-group">
														<input type="text" class="form-control" id="plan" name="plan">
														<label for="plan">Plan</label>
													</div>
												</div>
												
											</div>
											
											<!-- TERMINA REPRODUCCION ASISTIDA -->
											<div class="pull-right">	
												<button type="button" id="limpio" class="btn btn-raised btn-primary ink-reaction" onclick='$("#test").data("jqScribble").clear();'>Limpiar</button>
												<button type="button" class="btn btn-raised btn-primary ink-reaction" onclick="save()" id="saveCons">Guardar</button>
											</div>
										</div><!--end .card-tiles -->
										
									</div>
									
									
								</div><!--end .card-body -->
							</div>
							<!-- COMIENZA CONSULTA DE PRIMERA VEZ -->
							<?php }else if($numero_consul == '0'){ ?>
							<div class="card">
								<input type="hidden" name="idpac" value="<?php echo $paciente[0]['ID']; ?>">
								<input type="hidden" name="tipocons" value="0">
								<input type="hidden" name="imagen" id="hImagen">
								<div class="card-body ">
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<input type="text" class="form-control" id="motivo" name="motivo">
												<label for="Firstname2">Motivo Consulta</label>
											</div>
										</div>
										<div class="col-md-3"></div>
										<div class="col-md-3">
											<div class="form-group">
												<input type="text" class="form-control" id="fechahoy" name="fechahoy">
												<label for="fechahoy">Fecha</label>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-md-6">
											<div class="row">
												<div class="col-sm-6">
													<div class="form-group">
														<input type="text" class="form-control" id="fum" name="fum">
														<label for="fum">FUM</label>
													</div>
												</div>
											</div>
											<div class="row">
												<div class="col-sm-3">
													<div class="form-group">
														<input type="text" class="form-control" id="ciclo" name="ciclo" data-inputmask="'mask': '99X99 '">
														<label for="ciclo">Ciclos</label>
													</div>
												</div>
												<div class="col-sm-3">
													<div class="form-group">
														<input type="text" class="form-control" id="menarca" name="menarca">
														<label for="menarca">Menarca</label>
													</div>
												</div>
												<div class="col-sm-3">
													<div class="form-group">
														<input type="text" class="form-control" id="ivsa" name="ivsa">
														<label for="ivsa">IVSA</label>
													</div>
												</div>
												<div class="col-sm-3">
													<div class="form-group">
														<input type="text" class="form-control" id="duracion" name="duracion">
														<label for="duracion">Duración</label>
													</div>
												</div>
											</div>
											<div class="row">
												<div class="col-sm-2">
													<div class="form-group">
														<input type="text" class="form-control" id="gestas" name="gestas" data-rule-number="true">
														<label for="gestas">G</label>
													</div>
												</div>
												<div class="col-sm-2">
													<div class="form-group">
														<input type="text" class="form-control" id="partos" name="partos">
														<label for="partos">P</label>
													</div>
												</div>
												<div class="col-sm-2">
													<div class="form-group">
														<input type="text" class="form-control" id="cesarea" name="cesarea">
														<label for="cesarea">C</label>
													</div>
												</div>
												<div class="col-sm-2">
													<div class="form-group">
														<input type="text" class="form-control" id="abortos" name="bortos">
														<label for="abortos">A</label>
													</div>
												</div>
												<div class="col-sm-2">
													<div class="form-group">
														<input type="text" class="form-control" id="ectopicos" name="ectopicos">
														<label for="ectopicos">E</label>
													</div>
												</div>
											</div>
											<div class="row">
												<div class="form-group col-sm-3">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="hijoUno">
															<span style="font-size:12px">PRIMER HIJO</span>
														</label>												
													</div>		
												</div>
												<div class="form-group col-sm-3 hidden" id="hijoUno">
													<div>
														<div>
															<label for="hijoUnoNombre">NOMBRE</label>
															<input type="text" class="form-control input-lg" name="hijoUnoNombre" id="hijoUnoNombre"><br>
														</div>	
														<div>
															<label for="hijoUnoEdad">EDAD</label>
															<input type="text" class="form-control input-lg" name="hijoUnoEdad" id="hijoUnoEdad"><br>
														</div>											
													</div>
												</div>
												<div class="form-group col-sm-3">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="hijoDos">
															<span style="font-size:12px">SEGUNDO HIJO</span>
														</label>												
													</div>		
												</div>
												<div class="form-group col-sm-3 hidden" id="hijoDos">
													<div>
														<div>
															<label for="hijoDosNombre">NOMBRE</label>
															<input type="text" class="form-control input-lg" name="hijoDosNombre" id="hijoDosNombre"><br>
														</div>	
														<div>
															<label for="hijoDosEdad">EDAD</label>
															<input type="text" class="form-control input-lg" name="hijoDosEdad" id="hijoDosEdad"><br>
														</div>											
													</div>
												</div>
												<div class="form-group col-sm-3">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="hijoTres">
															<span style="font-size:12px">TERCER HIJO</span>
														</label>												
													</div>		
												</div>
												<div class="form-group col-sm-3 hidden" id="hijoTres">
													<div>
														<div>
															<label for="hijoTresNombre">NOMBRE</label>
															<input type="text" class="form-control input-lg" name="hijoTresNombre" id="hijoTresNombre"><br>
														</div>	
														<div>
															<label for="hijoTresEdad">EDAD</label>
															<input type="text" class="form-control input-lg" name="hijoTresEdad" id="hijoTresEdad"><br>
														</div>											
													</div>
												</div>
											</div>
											<div class="row">
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="adisme">
															<span style="font-size:12px">DISMENORREA</span>
														</label>												
													</div>		
												</div>
												<div class="form-group col-sm-3 hidden" id="adisme">
													<!-- <input type="text" class="form-control input-lg" name="DISMENORREA" id="DISMENORREA"> -->
													<textarea name="DISMENORREA" id="DISMENORREA" class="form-control" rows="3"></textarea>
												</div>
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="aflu">
															<span style="font-size:12px">FLUJO</span>
														</label>												
													</div>		
												</div>
												<div class="form-group col-sm-3 hidden" id="aflu" >
													<textarea name="FLUJO" id="FLUJO" class="form-control" rows="3"></textarea>
												</div>											
											</div>
											<div class="row">
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="asistU">
															<span style="font-size:12px">SISTEMA URINARIO</span>
														</label>
													</div>
												</div>
												<div class="form-group col-sm-3 hidden" id="asistU">
													<textarea name="sistUri" id="sistUri"  class="form-control" rows="3"></textarea>
												</div>
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="asistDige">
															<span style="font-size:12px">SISTEMA DIGESTIVO</span>
														</label>
													</div>
												</div>
												<div class="form-group col-sm-3 hidden" id="asistDige">
													<textarea name="sistDige" id="sistDige" class="form-control" rows="3"></textarea>
												</div>
											</div>
											<div class="row">
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="aAntico">
															<span style="font-size:12px">ANTICONCEPTIVO</span>
														</label>
													</div>
												</div>
												<div class="form-group col-sm-3 hidden" id="aAntico">
													<input type="text" class="form-control input-lg" name="antico" id="antico">
												</div>
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="apapani">
															<span style="font-size:12px">PAP</span>
														</label>
													</div>
												</div>
												<div class="form-group col-sm-3 hidden" id="apapani">
													<input type="text" class="form-control input-lg" name="papani" id="papani">
												</div>
											</div>
											<div class="row">
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="agalacto">
															<span style="font-size:12px">GALACTORREA</span>
														</label>
													</div>
												</div>
												<div class="form-group col-sm-3 hidden" id="agalacto">
													<input type="text" class="form-control input-lg" name="galacto" id="galacto">
												</div>
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="ahirsu">
															<span style="font-size:12px">HIRSUTISMO</span>
														</label>
													</div>
												</div>
												<div class="form-group col-sm-3 hidden" id="ahirsu">
													<input type="text" class="form-control input-lg" name="hirsu" id="hirsu">
												</div>
											</div>
											<div class="row">
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="acohham">
															<span style="font-size:12px">COH-HAM</span>
														</label>
													</div>
												</div>
												<div class="form-group col-sm-3 hidden" id="acohham">
													<select name="cohham" id="cohham" class="form-control">
														<option value="0">Selecciona</option>
														<option value="1">1</option>
														<option value="2">2</option>
														<option value="3">3</option>
														<option value="4">4</option>
														<option value="5">5</option>
														<option value="6+">6 ó más</option>
													</select>
												</div>
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="ahsg">
															<span style="font-size:12px">HSG</span>
														</label>
													</div>
												</div>
												<div class="form-group col-sm-3 hidden" id="ahsg">
													<div>
														<label for="acavidad">Cavidad</label>
														<input type="text" class="form-control input-lg" name="cavidad" id="cavidad"><br>
													</div>
													<div>
														<label for="aD">+D</label>
														<input type="text" class="form-control input-lg" name="aD" id="aD"><br>
													</div>
													<div>
														<label for="aI">+I</label>
														<input type="text" class="form-control input-lg" name="aI" id="aI">
													</div>
												</div>
											</div>
											<div class="row">
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="acirug">
															<span style="font-size:12px">CIRUGIAS PREVIAS</span>
														</label>
													</div>
												</div>
												<div class="form-group col-sm-4 hidden" id="acirug">
													<input type="text" class="form-control input-lg" name="cirugias" id="cirugias">
												</div>
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="divaespermo">
															<span style="font-size:12px">ESPERMOGRAMA</span>
														</label>
													</div>
												</div>
												<div class="form-group col-sm-10 hidden" id="divaespermo">
													<div class="form-group col-sm-3">
														<div>
															<label for="efecha">Fecha</label>
															<input type="text" class="form-control input-lg" name="efecha" id="efecha"><br>
														</div>
														<div>
															<label for="emoti">Motivilidad</label>
															<input type="text" class="form-control input-lg" name="emoti" id="emoti"><br>
														</div>
														<div>
															<label for="ecultiv">Cultivo</label>
															<input type="text" class="form-control input-lg" name="ecultiv" id="ecultiv"><br>
														</div>
													</div>
													<div class="form-group col-sm-3">
														<div>
															<label for="ecuenta">Cuenta</label>
															<input type="text" class="form-control input-lg" name="ecuenta" id="ecuenta"><br>
														</div>
														<div>
															<label for="efn">FN</label>
															<input type="text" class="form-control input-lg" name="efn" id="efn"><br>
														</div>
														<div>
															<label for="eapp">APP</label>
															<input type="text" class="form-control input-lg" name="eapp" id="eapp"><br>
														</div>
													</div>
													<div class="form-group col-sm-3">
														<div>
															<br>
															<select id="evolumen" name="evolumen" class="form-control">
																<option value="0">Selecciona</option>
																<option value="1">1</option>
																<option value="2">2</option>
																<option value="3">3</option>
																<option value="4">4</option>
																<option value="5">5</option>
															</select>
															<label for="evolumen">VOLUMEN</label>
														</div>
														<div>
														<br>
															<label for="efragm">Fragmentación DNA</label>
															<input type="text" class="form-control input-lg" name="efragm" id="efragm"> 
														</div>
													</div>
												</div>
											</div>
											<div class="row">
												<div class="form-group col-sm-4">
													<div>
														<label class="checkbox checkbox-styled">
															<input type="checkbox" divref="alab">
															<span style="font-size:12px">LABORATORIO</span>
														</label>
													</div>
												</div>
												<div class="form-group col-sm-3 hidden" id="alab">
													<input type="text" class="form-control input-lg" name="lab" id="lab">
												</div>
											</div>
										</div>
										<div class="col-sm-3"></div>
										<div class="col-sm-3">
											<div class="form-group">
												<div class="input-group">
													<div class="input-group-content">
														<input type="text" class="form-control" id="edad" name="edad">
														<label for="edad">Edad</label>
													</div>
													<span class="input-group-addon">años</span>
												</div>
											</div>
											<div class="form-group">
												<div class="input-group">
													<div class="input-group-content">
														<input type="text" class="form-control" id="tiroidestxt" name="tiroidestxt">
														<label for="tiroidestxt">Tiroides</label>
													</div>
													<span class="input-group-addon">ml U/L</span>
												</div>
											</div>
											<div class="form-group">
												<div class="input-group">
													<div class="input-group-content">
														<input type="text" class="form-control" id="peso" name="peso">
														<label for="peso">Peso</label>
														</div>
													<span class="input-group-addon">Kg</span>
												</div>
											</div>
											<div class="form-group">
												<div class="input-group">
													<div class="input-group-content">
														<input type="text" class="form-control" id="presion" name="presion">
														<label for="presion">Presión</label>
														</div>
													<span class="input-group-addon">mmHg</span>
												</div>
											</div>
											<div class="form-group">
												<textarea name="imx" id="imx" class="form-control" rows="3"></textarea>
												<label for="imx">Iny</label>
											</div>
											<div class="form-group">
												<textarea name="plan" id="plan" class="form-control" rows="3"></textarea>
												<label for="plan">Plan</label>
											</div>
										</div>
										
									</div>
									<hr>
									<div class="row">
										<!-- BEGIN CANVAS -->
										<div class="card-tiles">
											<div style="overflow: hidden; margin-bottom: 5px;">
												<div class="column-right links" id="colores">
													<strong>COLORES:</strong>
														<button type="button" onclick='$("#test").data("jqScribble").update({brushColor: "rgb(32,37,43)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-default-dark fa fa-pencil" data-toggle="tooltip" data-original-title="Negro"></button>
														<button type="button" onclick='$("#test").data("jqScribble").update({brushColor: "rgb(244,67,54)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-danger fa fa-pencil" data-toggle="tooltip" data-original-title="Rojo"></button>
														<button type="button" onclick='$("#test").data("jqScribble").update({brushColor: "rgb(76,175,80)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-success fa fa-pencil" data-toggle="tooltip" data-original-title="Verde"></button>
														<button type="button" onclick='$("#test").data("jqScribble").update({brushColor: "rgb(33,150,243)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-info fa fa-pencil" data-toggle="tooltip" data-original-title="Azul"></button>
														<button type="button" onclick='$("#test").data("jqScribble").update({brushColor: "rgb(255,255,255)",brushSize:"30"});' class="btn ink-reaction btn-raised btn-sm btn-default-bright fa fa-eraser" data-toggle="tooltip" data-original-title="Borrador"></button>
												</div>
											</div>
											<div class="row">
												<canvas id="test"></canvas>
											</div>
											<input type="hidden" value="<?php echo date_format($paciente[0]["FECHA_NACIMIENTO"],"Y-m-d") ?>" id="nacim">
											
											<div class="pull-right">	
												<button type="button" id="limpio" class="btn btn-raised btn-primary ink-reaction" onclick='$("#test").data("jqScribble").clear();'>Limpiar</button>
												<button type="button" class="btn btn-raised btn-primary ink-reaction" onclick="save()" id="saveCons">Guardar</button>
											</div>
										</div>
									</div>
								</div>
								<!--end .card-body -->
							</div>
							<?php }?>
							<input id="camera" type="file" style="display:none" accept="image/*" name="fotingas[]" multiple="" />
						</form>
					</div>
					
					<!-- COMIENZA RECETAS -->
					<div class="tab-pane" id="recetas">
						<br>
						<div id="resultarecetas">
							
						</div>
					</div>
				</div>
			</div>
			<!-- END CONTACTS MAIN CONTENT -->
		</div>
	</div>

	<!-- BEGIN OFFCANVAS -->
	<div class="offcanvas backdrop">
		<!-- BEGIN CONTACTS COMMON DETAILS -->
		<div id="datosgenerales" class="offcanvas-pane width-8">
			<div class="offcanvas-head">
                <header class="text-primary">Información del Paciente</header>
                <div class="offcanvas-tools">
                    <a class="btn btn-icon-toggle btn-default-light pull-right" data-dismiss="offcanvas">
                        <i class="md md-close"></i>
                    </a>
                </div>
            </div>
            <div class="offcanvas-body no-padding">
				<div class="hbox-column col-md-12 style-default-light">
					<div class="row">
						<div class="col-xs-12">
							<h4>Datos Personales</h4>
							<br/>
							<?php if(!isset($paciente)){ ?>
								<span class="text-medium style-warning">No hay usuario seleccionado</span>
							<?php }else{ ?>
							<dl class="dl-horizontal dl-icon">
								<dt><span class="fa fa-fw fa-gift fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Años</span><br/>
									<span class="text-medium"><p class="form-control-static" id="aniospac"></p></span>
								</dd>
								<dt><span class="fa fa-fw fa-home fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Dirección</span><br/>
									<span class="text-medium"><?php echo $paciente[0]['CALLE']; ?>&nbsp;No. <?php echo $paciente[0]['NUMERO_EXT']; ?></span><br>
									<span class="text-medium"><?php echo $paciente[0]['COLONIA']; ?></span><br>
									<span class="text-medium"><span class="opacity-50">C.P. </span><?php echo $paciente[0]['CODIGO_POSTAL']; ?></span>
								</dd>
								<dt><span class="fa fa-fw fa-home fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Tipo Sanguíneo</span><br/>
									<span class="text-medium"><?php echo $paciente[0]['CALLE']; ?></span>
								</dd>
							</dl><!--end .dl-horizontal -->
							<?php } ?>
							<br/>
							<h4>Antecedentes</h4>
							<br/>
							<?php if(!isset($paciente)){ ?>
								<span class="text-medium style-warning">No hay usuario seleccionado</span>
							<?php }else{ ?>
							<dl class="dl-horizontal dl-icon">
								<?php if(isset($antecedentes[0]['TABAQUISMO'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/cigarrete.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Tabaquismo</span><br/>
									<span class="text-medium"><?php echo $antecedentes[0]['TABAQUISMO']; ?></span><br/>
								</dd>
								<?php } ?>
								<?php if(isset($antecedentes[0]['TOXICOMANIAS'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/syringe.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Toxicomanias</span><br/>
									<span class="text-medium"><?php echo $antecedentes[0]['TOXICOMANIAS']; ?></span><br/>
								</dd>
								<?php } ?>
								<?php if(isset($antecedentes[0]['ALCOHOLISMO'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/wine.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Alcoholismo</span><br/>
									<span class="text-medium"><?php echo $antecedentes[0]['ALCOHOLISMO']; ?></span><br/>
								</dd>
								<?php } ?>
								<?php if(isset($antecedentes[0]['AUMENTO_PERDIDA'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/gainlossweight.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Aumento/Perdida de Peso</span><br/>
									<span class="text-medium"><?php if($antecedentes[0]['AUMENTO_PERDIDA'] == "1"){ echo 'Sí'; }else{?>
									<?php echo 'No'; }?>
									</span><br/>
								</dd>
								<?php } ?>
								<?php if(isset($antecedentes[0]['ALERGIAS'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/allergies.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Alergias</span><br/>
									<span class="text-medium"><?php echo $antecedentes[0]['ALERGIAS']; ?></span><br/>
								</dd>
								<?php } ?>
								<?php if(isset($antecedentes[0]['CIRUGIAS'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/surgery.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Cirugias</span><br/>
									<span class="text-medium"><?php echo $antecedentes[0]['CIRUGIAS']; ?></span><br/>
								</dd>
								<?php } ?>
							</dl><!--end .dl-horizontal -->
							<?php } ?>
						</div><!--end .col -->
					</div><!--end .row -->
				</div><!--end .hbox-column -->
			</div>
		</div>
		<!-- END CONTACTS COMMON DETAILS -->	
	</div>
	<!-- END OFFCANVAS -->
	
    	
    
</div>

<?php 	if($paciente[0]["FECHA_NACIMIENTO"]){ ?>
<input type="hidden" value="<?php echo date_format($paciente[0]["FECHA_NACIMIENTO"],"Y-m-d") ?>" id="nacim">
<?php }else{ ?>
<input type="hidden" value="" id="nacim">
<?php } ?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/dropzone/dropzone-theme.css">
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/js/libs/Gallery-master/css/blueimp-gallery.min.css">
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/js/libs/Gallery-master/css/blueimp-gallery-indicator.css">
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/js/libs/Gallery-master/css/blueimp-gallery-video.css">

<script src="<?php echo $this->basePath() ?>/public/js/libs/dropzone/dropzone.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/Gallery-master/js/blueimp-gallery.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/Gallery-master/js/blueimp-gallery-video.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/jquery.jqscribble.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath() ?>/public/js/jqscribble.extrabrushes.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath() ?>/public/js/exclie/consultando.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/inputmask/jquery.inputmask.bundle.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-ui/jquery-ui.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/moment/moment.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/bootstrap-datepicker/bootstrap-datepicker.js"></script>

<script>
	socket.on('updatecons',function(data) {
		switch(data.accion) {
			case 'refrescarreceta':
				if(data.datos.iddoctor == <?php echo $this->identity()->getId(); ?>)
					consultatablet(data.datos.idconsulta,data.datos.tipo,data.datos.consultappal);

			break;
			case 'mandarmonitoreo':
				if(data.data.iddoctor == <?php echo $this->identity()->getId(); ?>)
					monitoreotablet(data.data.idconsulta,data.data.consulppal);
			break;
		}
	});

	$(document).ready(function()
	{
		mostrarArhivos();
		mostrarVideos();
		$("#test").jqScribble();
		$('#fum').datepicker({format: "dd-mm-yyyy"});
		fechaActual();
		

		var born = document.getElementById("nacim").value;
		
		if(born == ''){
			$('#edad').val('');
		}else{
			$('#edad').val(getEdad(born));
			$('#Edad').text(getEdad(born));
			$('#aniospac').text(getEdad(born));
		}
		    	
	   	mostrarNotas();
	   	$('#lirecetas').hide();
		$('#lireproduccion').hide();

	});

	function consultatablet(id,tipo,cons)
	{
		
		$.ajax({
	       type: "POST",
	       url: "<?php echo $this->basePath() ?>/consultados/datosconsulta",
	       data: {id_consulta:id,tipo_cons:tipo,consult:cons},
	       dataType: "json",
	       success: function(response) {
	       		var carpetanum = response['pac'][0];
	       		var imagencons = response['consultag'][0].IMAGEN;
	       		var imgcons = "<?php echo $this->basePath(); ?>/public/imagenes/consultas/"+carpetanum+'/'+imagencons;
	       		$("#test").data("jqScribble").update({backgroundImage: imgcons});
	       			       		
	       		$('#lirecetas').show();
	       		mostrarReceta(response['consulta'][0]);
	       		$('#limpio').attr('disabled','disabled');

	       		$('#idconsg').val(response['consultag'][0].ID);
	       		$('#edad').val(response['consultag'][0].EDAD);
	       		$('#gestas').val(response['consultag'][0].GESTAS);
	       		$('#partos').val(response['consultag'][0].PARTOS);
	       		$('#cesarea').val(response['consultag'][0].CESAREAS);
	       		$('#abortos').val(response['consultag'][0].ABORTOS);
	       		$('#ectopicos').val(response['consultag'][0].ECTOPICOS);
				$('#tiroidestxt').val(response['consultag'][0].TIROIDESNUM);
				$('#peso').val(response['consultag'][0].PESO);
	       		$('#presion').val(response['consultag'][0].PRESION);
	       		$('#imx').val(response['consultag'][0].IMX);
	       		$('#plan').val(response['consultag'][0].PLAN);
	       		

	       		if (response['tipo'] == 1) {
	       			console.log('consulta seg');
		       		$('#motivo').val(response['consultag'][0].MOTIVO_CONS);
		       		$('#ciclo').val(response['consultag'][0].CICLO);
		       		if (response['consultag'][0].FUM) {
		       			var fecha = response['consultag'][0].FUM.date;
		       			var arr = fecha.split(" ");
		       			var mes = arr[0];
		       			var separa = mes.split("-"); 
		       			var Mes = separa[2];
		       			var dia = separa[1];
		       			var anio = separa[0];
		       			$('#fum').val(dia + "-" + Mes + "-" + anio);
		       		}
		       	}
	       		if (response['tipo'] == 0) {
	       			console.log('conslta primera');
	       			$('#motivo').val(response['consultag'][0].PADECIMIENTO);
	       			$('#ciclo').val(response['consultag'][0].CICLOS);
	       			$('#menarca').val(response['consultag'][0].MENARCA);
	       			$('#ivsa').val(response['consultag'][0].IVSA);
	       			$('#duracion').val(response['consultag'][0].DURACION);
	       			$('#fum').val(response['consultag'][0].FUM);
	       			if (response['consultag'][0].PRIMERHIJO_NOMBRE) {
	       				$('#hijoUno').removeClass('hidden');
	       				$('input[divref="hijoUno"]').attr('checked',true);
	       				$('#hijoUnoNombre').val(response['consultag'][0].PRIMERHIJO_NOMBRE);
	       				$('#hijoUnoEdad').val(response['consultag'][0].PRIMERHIJO_EDAD);
	       			} else {
	       				$('#hijoUnoNombre').val('');
	       				$('#hijoUnoEdad').val('');
	       			}
	       			if (response['consultag'][0].SEGUNDOHIJO_NOMBRE) {
	       				$('#hijoDos').removeClass('hidden');
	       				$('input[divref="hijoDos"]').attr('checked',true);
	       				$('#hijoDosNombre').val(response['consultag'][0].SEGUNDOHIJO_NOMBRE);
	       				$('#hijoDosEdad').val(response['consultag'][0].PRIMERHIJO_EDAD);
	       				
	       			} else {
	       				$('#hijoDosNombre').val('');
	       				$('#hijoDosEdad').val('');
	       			}
	       			if (response['consultag'][0].TERCERHIJO_NOMBRE) {
	       				$('#hijoTres').removeClass('hidden');
	       				$('input[divref="hijoTres"]').attr('checked',true);
	       				$('#hijoTresNombre').val(response['consultag'][0].TERCERHIJO_NOMBRE);
	       				$('#hijoTresEdad').val(response['consultag'][0].TERCERHIJO_EDAD);
	       				
	       			} else {
	       				$('#hijoTresNombre').val('');
	       				$('#hijoTresEdad').val('');
	       			}
	       			if (response['consultag'][0].DISMENORREA) {
	       				$('#adisme').removeClass('hidden');
	       				$('input[divref="adisme"]').attr('checked',true);
	       				$('#DISMENORREA').val(response['consultag'][0].DISMENORREA);
	       			} else {
	       				$('#DISMENORREA').val('');
	       			}
	       			if (response['consultag'][0].FLUJO) {
	       				$('#aflu').removeClass('hidden');
	       				$('input[divref="aflu"]').attr('checked',true);
	       				$('#FLUJO').val(response['consultag'][0].FLUJO);
	       			} else{
	       				$('#FLUJO').val('');
	       			}
	       			if (response['consultag'][0].SIST_URINARIO) {
	       				$('#asistU').removeClass('hidden');
	       				$('input[divref="asistU"]').attr('checked',true);
	       				$('#sistUri').val(response['consultag'][0].SIST_URINARIO);
	       			} else {
	       				$('#sistUri').val('');
	       			}
	       			if (response['consultag'][0].SIST_DIGESTIVO) {
	       				$('#asistDige').removeClass('hidden');
	       				$('input[divref="asistDige"]').attr('checked',true);
	       				$('#sistDige').val(response['consultag'][0].SIST_DIGESTIVO);
	       			} else {
	       				$('#sistDige').val('');
	       			}
	       			if (response['consultag'][0].ANTICONCEPTIVOS) {
	       				$('#aAntico').removeClass('hidden');
	       				$('input[divref="aAntico"]').attr('checked',true);
	       				$('#antico').val(response['consultag'][0].ANTICONCEPTIVOS);
	       			} else {
	       				$('#antico').val('');
	       			}
	       			if (response['consultag'][0].PAP) {
	       				$('#apapani').removeClass('hidden');
	       				$('input[divref="apapani"]').attr('checked',true);
	       				$('#antico').val(response['consultag'][0].PAP);
	       			} else {
	       				$('#antico').val('');
	       			}
	       			if (response['consultag'][0].COH != 0) {
	       				$('#acohham').removeClass('hidden');
	       				$('input[divref="acohham"]').attr('checked',true);
	       				$('#cohham').val(response['consultag'][0].COH);
	       			} else {
	       				$('#cohham').val('0');
	       			}
	       			if (response['consultag'][0].GALACTORREA) {
	       				$('#agalacto').removeClass('hidden');
	       				$('input[divref="galacto"]').attr('checked',true);
	       				$('#galacto').val(response['consultag'][0].GALACTORREA);
	       			} else {
	       				$('#galacto').val('');
	       			}
	       			if (response['consultag'][0].HIRSUTISM) {
	       				$('#ahirsu').removeClass('hidden');
	       				$('input[divref="ahirsu"]').attr('checked',true);
	       				$('#hirsu').val(response['consultag'][0].HIRSUTISM);
	       			} else {
	       				$('#hirsu').val('');
	       			}
	       			if (response['consultag'][0].HSG_CAVIDAD) {
	       				$('#ahsg').removeClass('hidden');
	       				$('input[divref="ahsg"]').attr('checked',true);
	       				$('#aD').val(response['consultag'][0].HSG_D);
	       				$('#aI').val(response['consultag'][0].HSG_I);
	       			} else {
	       				$('#cavidad').val('');
	       				$('#aD').val('');
	       				$('#aI').val('');
	       			}
	       			if (response['consultag'][0].LABORATORIO_NOTAS) {
	       				$('input[divref="alab"]').attr('checked',true);
	       				$('#alab').removeClass('hidden');
	       				$('#lab').val(response['consultag'][0].LABORATORIO_NOTAS);
	       			} else {
	       				$('#lab').val('');
	       			}
	       			if (response['consultag'][0].CIRUGIAS_PREVIAS) {
	       				$('#acirug').removeClass('hidden');
	       				$('input[divref="acirug"]').attr('checked',true);
	       				$('#cirugias').val(response['consultag'][0].CIRUGIAS_PREVIAS);
	       			} else {
	       				$('#cirugias').val('');
	       			}
	       			if (response['consultag'][0].ESPERMO_CUENTA) {
	       				$('#divaespermo').removeClass('hidden');
	       				$('input[divref="divaespermo"]').attr('checked',true);
	       				$('#ecuenta').val(response['consultag'][0].ESPERMO_CUENTA);
	       				$('#efecha').val(response['consultag'][0].ESPERMO_FECHA);
	       				$('#evolumen').val(response['consultag'][0].ESPERMO_VOLUMEN);
	       				$('#emoti').val(response['consultag'][0].ESPERMO_MOTIVIDAD);
	       				$('#efn').val(response['consultag'][0].ESPERMO_FN);
	       				$('#efragm').val(response['consultag'][0].ESPERMO_DNA);
	       				$('#ecultiv').val(response['consultag'][0].ESPERMO_CULTIVO);
	       				$('#eapp').val(response['consultag'][0].ESPERMO_APP);
	       			} else {
	       				$('#ecuenta').val('');
	       				$('#efecha').val('');
	       				$('#evolumen').val('0');
	       				$('#emoti').val('');
	       				$('#efn').val('');
	       				$('#efragm').val('');
	       				$('#ecultiv').val('');
	       				$('#eapp').val('');
	       			}
	       		}
	       	},
	       error: function(){
	             toastr.error('Inténtalo más tarde.');
	       }
	   });
	}

	function getEdad(fechanac)
	{
		var hoy = new Date();
    	var fechaNacimiento = new Date(fechanac);
    	var edad = hoy.getFullYear() - fechaNacimiento.getFullYear();
    	var m = hoy.getMonth() - fechaNacimiento.getMonth();
    	if (m < 0 || (m === 0 && hoy.getDate() < fechaNacimiento.getDate())) {
        	edad--;
    	}
    	return edad;
	}

	function fechaActual()
	{
		var today = new Date();
	    var dd = today.getDate();
	    var mm = today.getMonth()+1; 
	    var yyyy = today.getFullYear();

	    if(dd<10){
	        dd='0'+dd
	    } 
	    if(mm<10){
	        mm='0'+mm
	    } 
	    var today = dd+'-'+mm+'-'+yyyy;

	    $('#fechahoy').val(today);
	}

	function save()
	{

		$("#test").data("jqScribble").save(function(imageData)
		{	
			$("#hImagen").val(imageData);
			//var formulario = $('#formConsul').serialize();
			var formu2 = new FormData($('form#formConsul')[0]);
			
			$.ajax({
			    type: "POST",
				cache:false,
		        async: false,
		        contentType: false,
		        processData: false,
			    url: "<?php echo $this->basePath() ?>/consultados/guardarconsulta",
			    dataType: "json",
			    data: formu2,
			    success: function(respuesta) {
			        idConsultag = respuesta.id;
			        idConsulta = respuesta.idconsulta;
			        tipoconsu = respuesta.tipocons;
			        datasocket = {accion:'refrescarreceta',datos:{consultappal:idConsulta,idconsulta:idConsultag,iddoctor:<?php echo $this->identity()->getId(); ?>,tipo:tipoconsu}};
			        $('#saveCons').attr('disabled','disabled');
			        $('#limpio').attr('disabled','disabled');
	           		$('#consultaid').val(idConsulta);
	           		console.log(idConsulta);
	           		$('#lirecetas').show();
	       			mostrarReceta(idConsulta);
	           		socket.emit('updateconsultas',datasocket);
	           		
			    },
			    error: function(){
			          toastr.error('Ocurrió un error, inténtelo más tarde.');
			    }
			});
	
		});
	}
	
	function guardarNota()
	{
		var nota = $('#recordar').val();
		var data ={pac: <?php echo $paciente[0]['ID']; ?>,nota: nota};
		
		$.ajax({
           type: "POST",
           url: "<?php echo $this->basePath() ?>/notas/guardarnota",
           data: data,
           dataType: "JSON",
           
           success: function(response) {
           		$('#recordar').val('');
           		mostrarNotas();
           },
           error: function(){
                 toastr.error('Inténtalo más tarde.');
           }
       });
	}

	function mostrarNotas()
	{
		var data ={paciente: <?php echo $paciente[0]['ID']; ?>};
		
		$.ajax({
           type: "POST",
           url: "<?php echo $this->basePath() ?>/consultados/listanotas",
           data: data,
           dataType: "HTML",
           
           success: function(response) {
           		$('#resultaNotas').html(response);
           },
           error: function(){
                 toastr.error('Inténtalo más tarde.');
           }
       });
	}

	function mostrarReceta(id)
	{
		var data ={consulta: id};
		
		$.ajax({
           type: "POST",
           url: "<?php echo $this->basePath() ?>/consultados/receta",
           data: data,
           dataType: "HTML",
           
           success: function(response) {
           		$('#resultarecetas').html(response);
           },
           error: function(){
                 toastr.error('Inténtalo más tarde.');
           }
       });
	}

	Dropzone.autoDiscover = false;
	/** COMIENZA DROPZONE DE VIDEOS**/
	var myDropzone = new Dropzone("#dropa", {
		paramName: "file", // The name that will be used to transfer the file
		  accept: function(file, done) {
		    done();
		  },
		  addRemoveLinks: true,
		  removedfile: function(file){
		    var datos = {archivo:file.name,id:$('#pacid').val()};
		    console.log(datos);
		    $.ajax({
		          type: "POST",
		          url: "<?php echo $this->basePath() ?>/consultados/eliminarVideo",
		          data: datos,
		          dataType: "json",
		          success: function(data) {
		                  var _ref;
		                     if (file.previewElement) {
		                       if ((_ref = file.previewElement) != null) {
		                         _ref.parentNode.removeChild(file.previewElement);
		                       }
		                     }
		                     return this._updateMaxFilesReachedClass();
		                },
		          error: function(data){
		                      var _ref;
		                        if (file.previewElement) {
		                          if ((_ref = file.previewElement) != null) {
		                            _ref.parentNode.removeChild(file.previewElement);
		                          }
		                        }
		                        return this._updateMaxFilesReachedClass();

		          }
		      });
		  }
	});
	

  	/** EMPIEZA DROP DE LOS EXPEDIENTES DE HISTORIA **/
	 var myDropzone = new Dropzone("#drops", {
		paramName: "file", // The name that will be used to transfer the file
		  accept: function(file, done) {
		    done();
		    mostrarArhivos();
		  },
		  addRemoveLinks: true,
		  removedfile: function(file){
		    var datos = {archivo:file.name,id:$('#patient').val()};
		    console.log(datos);
		    $.ajax({
		          type: "POST",
		          url: "<?php echo $this->basePath() ?>/consultados/eliminarArchivo",
		          data: datos,
		          dataType: "json",
		          success: function(data) {
		                  var _ref;
		                     if (file.previewElement) {
		                       if ((_ref = file.previewElement) != null) {
		                         _ref.parentNode.removeChild(file.previewElement);
		                       }
		                     }
		                     return this._updateMaxFilesReachedClass();
		                     mostrarArhivos();
		                },
		          error: function(data){
		                      var _ref;
		                        if (file.previewElement) {
		                          if ((_ref = file.previewElement) != null) {
		                            _ref.parentNode.removeChild(file.previewElement);
		                          }
		                        }
		                        return this._updateMaxFilesReachedClass();

		          }
		      });
		  }
	});
	

	/** EMPIEZA LA GALERIA DE IMAGENES **/
	document.getElementById('links').onclick = function (event) {
	    event = event || window.event;
	    var target = event.target || event.srcElement,
	        link = target.src ? target.parentNode : target,
	        options = {index: link, event: event},
	        links = this.getElementsByTagName('a');
	    blueimp.Gallery(links, options);
	};

	

	/** INICIA MOSTRAR ARCHIVOS **/

	function mostrarArhivos()
	{
		var data ={paciente: <?php echo $paciente[0]['ID']; ?>};
		
		$.ajax({
           type: "POST",
           url: "<?php echo $this->basePath() ?>/consultados/listaarchivos",
           data: data,
           dataType: "HTML",
           
           success: function(response) {
           		$('#resultaArchivos').html(response);
           },
           error: function(){
                 toastr.error('Inténtalo más tarde.');
           }
       });
	}

	/** INICIA MOSTRAR VIDEOS **/

	function mostrarVideos()
	{
		var data ={paciente: <?php echo $paciente[0]['ID']; ?>};
		
		$.ajax({
           type: "POST",
           url: "<?php echo $this->basePath() ?>/consultados/listavideos",
           data: data,
           dataType: "HTML",
           
           success: function(response) {
           		$('#resultaVideos').html(response);
           		
           		
       

           },
           error: function(){
                 toastr.error('Inténtalo más tarde.');
           }
       });
	}
	/** INICIA MOSTRAR MONITOREO **/
	function repasistida()
	{
		var data ={paciente: <?php echo $paciente[0]['ID']; ?>};
		
		$.ajax({
	       type: "POST",
	       url: "<?php echo $this->basePath() ?>/consultados/monitoreo",
	       data: data,
	       dataType: "HTML",
	       
	       success: function(response) {
	       		$('#monito').html(response);
	       		
	       		
	       		$('#verconsulta').removeClass('active');
	       		$('#notes').removeClass('active');
	       		$('#archivo').removeClass('active');
	       		$('#historia').removeClass('active');
	       		$('#licons').removeClass('active');
	       		$('#lireproduccion').show();
	       		$('#addconsulta').hide();
	       		$('#licons').hide();
	       		$('#reproduccion').addClass('active');
	       		$('#lireproduccion').addClass('active');


	       		
	       },
	       error: function(){
	             toastr.error('Inténtalo más tarde.');
	       }
	   });
	}

	function guardamonitoreo(a){
		console.log(a);
		 $("#monitoreo").data("jqScribble").save(function(imageData)
		 {	
			$("#hImagen").val(imageData);
			$('#htipo').val(a);
			var formularioMon = $('#formMonitoreo').serialize();

			$.ajax({
			    type: "POST",
			    url: "<?php echo $this->basePath() ?>/consultados/guardamonitoreo",
			    dataType: "json",
			    data: formularioMon,
			    success: function(respuesta) {
			        idConsulta = respuesta.id;
			        consppal = respuesta.idconsulta;
			        datasocket = {accion:'mandarmonitoreo',data:{consulppal:consppal,idconsulta:idConsulta,iddoctor:<?php echo $this->identity()->getId(); ?>}};
			        $('#saveConsm').attr('disabled','disabled');
			        $('#saveConsmt').attr('disabled','disabled');
			        $('#consultaid').val(idConsulta);
	           		//console.log(idConsulta);
	           		toastr.success('Consulta Guardada.');
	           		socket.emit('updateconsultas',datasocket);
	           		
			    },
			    error: function(){
			          toastr.error('Ocurrió un error, inténtelo más tarde.');
			    }
			});
	
		 });
	}

	function monitoreotablet(id,cons)
	{
		
		$.ajax({
	       type: "POST",
	       url: "<?php echo $this->basePath() ?>/consultados/datosconsultamoni",
	       data: {id_consulta:id,consppal:cons},
	       dataType: "json",
	       success: function(response) {
	       		//console.log(response);
	       		$('#lirecetas').show();
	       		$('#saveConsm').attr('disabled','disabled');
	       		$('#repasistida').val(response['consultam'][0].REPRODUCCION);
	       		$('#protocolo').val(response['consultam'][0].PROTOCOLO);
	       		$('#progestina').val(response['consultam'][0].PROGESTINA);
	       		$('#gnrh').val(response['consultam'][0].GNRH);
	       		$('#metro').val(response['consultam'][0].MENOTROPINAS);
	       		$('#fsh').val(response['consultam'][0].FSH);
	       		$('#pgyn').val(response['consultam'][0].PRIMOGYN);
	       		$('#otros').val(response['consultam'][0].OTROS);
	       		$('#residente').val(response['consultam'][0].RESIDENTE);
	       		$('#autorizado').val(response['consultam'][0].AUTORIZADO);
	       		$('#enviado').val(response['consultam'][0].ENVIADO);
	       			       		
	       		if (response['consultam'][0].FUR) {
	       			var fecha   = response['consultam'][0].FUR.date;
	       			var arr 	= fecha.split(" ");
	       			var mes 	= arr[0];
	       			var separa  = mes.split("-"); 
	       			var Mes 	= separa[2];
	       			var dia 	= separa[1];
	       			var anio 	= separa[0];
	       			$('#fur').val(dia + "-" + Mes + "-" + anio);
	       		}else{
	       			$('#fur').val();
	       		}
	       		

	       		if (response['consultam'][0].FPM) {
	       			var fecha2  = response['consultam'][0].FPM.date;
	       			var arr2 	= fecha2.split(" ");
	       			var mes2 	= arr2[0];
	       			var separa2 = mes2.split("-"); 
	       			var Mes2 	= separa2[2];
	       			var dia2 	= separa2[1];
	       			var anio2 	= separa2[0];
	       			$('#fpm').val(dia2 + "-" + Mes2 + "-" + anio2);
	       		}else{
	       			$('#fpm').val();
	       		}
	       		

	       		if (response['consultam'][0].PROGESTINA_DEL) {
	       			var fecha3  = response['consultam'][0].PROGESTINA_DEL.date;
	       			var arr3 	= fecha3.split(" ");
	       			var mes3 	= arr3[0];
	       			var separa3 = mes3.split("-"); 
	       			var Mes3 	= separa3[2];
	       			var dia3 	= separa3[1];
	       			var anio3 	= separa3[0];
	       			$('#start_preog').val(dia3 + "-" + Mes3 + "-" + anio3);
	       		}else{
	       			$('#start_preog').val();
	       		}
	       		

	       		if (response['consultam'][0].PROGESTINA_AL) {
	       			var fecha4  = response['consultam'][0].PROGESTINA_AL.date;
	       			var arr4  	= fecha4.split(" ");
	       			var mes4 	= arr4[0];
	       			var separa4 = mes4.split("-"); 
	       			var Mes4 	= separa4[2];
	       			var dia4 	= separa4[1];
	       			var anio4 	= separa4[0];
	       			$('#end_preog').val(dia4 + "-" + Mes4 + "-" + anio4);
	       		}else{
	       			$('#end_preog').val();
	       		} 
	       		

	       		if (response['consultam'][0].GNRHD_EL) {
	       			var fecha5  = response['consultam'][0].GNRHD_EL.date;
	       			var arr5 	= fecha5.split(" ");
	       			var mes5 	= arr5[0];
	       			var separa5 = mes5.split("-"); 
	       			var Mes5 	= separa5[2];
	       			var dia5 	= separa5[1];
	       			var anio5 	= separa5[0];
	       			$('#start_ghnr').val(dia5 + "-" + Mes5 + "-" + anio5);
	       		}else{
	       			$('#start_ghnr').val();
	       		} 

	       		

	       		if (response['consultam'][0].GNRH_AL) {
	       			var fecha6  = response['consultam'][0].GNRH_AL.date;
	       			var arr6 	= fecha6.split(" ");
	       			var mes6 	= arr6[0];
	       			var separa6 = mes6.split("-"); 
	       			var Mes6 	= separa6[2];
	       			var dia6 	= separa6[1];
	       			var anio6 	= separa6[0];
	       			$('#end_ghnr').val(dia6 + "-" + Mes6 + "-" + anio6);
	       		}else{
	       			$('#end_ghnr').val();
	       		}  
	       		

	       		if (response['consultam'][0].MENOTROPINAS_DEL) {
	       			var fecha7  = response['consultam'][0].MENOTROPINAS_DEL.date;
	       			var arr7 	= fecha7.split(" ");
	       			var mes7 	= arr7[0];
	       			var separa7 = mes7.split("-"); 
	       			var Mes7 	= separa7[2];
	       			var dia7 	= separa7[1];
	       			var anio7 	= separa7[0];
	       			$('#start_metro').val(dia7 + "-" + Mes7 + "-" + anio7);
	       		}else{
	       			$('#start_metro').val();
	       		}  
	       		

	       		if (response['consultam'][0].MENOTROPINAL_AL) {
	       			var fecha8  = response['consultam'][0].MENOTROPINAL_AL.date;
	       			var arr8 	= fecha8.split(" ");
	       			var mes8 	= arr8[0];
	       			var separa8 = mes8.split("-"); 
	       			var Mes8 	= separa8[2];
	       			var dia8 	= separa8[1];
	       			var anio8 	= separa8[0];
	       			$('#end_metro').val(dia8 + "-" + Mes8 + "-" + anio8);
	       		}else{
	       			$('#end_metro').val();
	       		}  
	       		

	       		if (response['consultam'][0].FSH_DEL) {
	       			var fecha9  = response['consultam'][0].FSH_DEL.date;
	       			var arr9 	= fecha9.split(" ");
	       			var mes9 	= arr9[0];
	       			var separa9 = mes9.split("-"); 
	       			var Mes9 	= separa9[2];
	       			var dia9 	= separa9[1];
	       			var anio9 	= separa9[0];
	       			$('#start_fsh').val(dia9 + "-" + Mes9 + "-" + anio9);
	       		}else{
	       			$('#start_fsh').val();
	       		} 
	       		

	       		if (response['consultam'][0].FSH_AL) {
	       			var fecha_f  = response['consultam'][0].FSH_AL.date;
	       			var arr_f 	 = fecha_f.split(" ");
	       			var mes_f 	 = arr_f[0];
	       			var separa_f = mes_f.split("-"); 
	       			var Mes_f 	 = separa_f[2];
	       			var dia_f 	 = separa_f[1];
	       			var anio_f	 = separa_f[0];
	       			$('#end_fsh').val(dia_f + "-" + Mes_f + "-" + anio_f);
	       		}else{
	       			$('#end_fsh').val();
	       		} 
	       		

	       		if (response['consultam'][0].PRIMOGYN_DEL) {
	       			var fechagd   = response['consultam'][0].PRIMOGYN_DEL.date;
	       			var arrgd	  = fechagd.split(" ");
	       			var mesgd 	  = arrgd[0];
	       			var separagd  = mesgd.split("-"); 
	       			var Mesgd 	  = separagd[2];
	       			var diagd 	  = separagd[1];
	       			var aniogd    = separagd[0];
	       			$('#start_pgyn').val(diagd + "-" + Mesgd + "-" + aniogd);
	       		}else{
	       			$('#start_pgyn').val();
	       		} 
	       		 

	       		if (response['consultam'][0].PRIMOGYN_AL) {
	       			var fecha_ga  = response['consultam'][0].PRIMOGYN_AL.date;
	       			var arr_ga	  = fecha_ga.split(" ");
	       			var mes_ga 	  = arr_ga[0];
	       			var separa_ga = mes_ga.split("-"); 
	       			var Mes_ga 	  = separa_ga[2];
	       			var dia_ga    = separa_ga[1];
	       			var anio_ga   = separa_ga[0];
	       			$('#end_pgyn').val(dia_ga + "-" + Mes_ga + "-" + anio_ga);
	       		}else{
	       			$('#end_pgyn').val();
	       		}  
	       		

	       		if (response['consultam'][0].OTROS_DEL) {
	       			var fecha_o1  = response['consultam'][0].OTROS_DEL.date;
	       			var arr_o1 	  = fecha_o1.split(" ");
	       			var mes_o1 	  = arr_o1[0];
	       			var separa_o1 = mes_o1.split("-"); 
	       			var Mes_o1 	  = separa_o1[2];
	       			var dia_o1 	  = separa_o1[1];
	       			var anio_o1   = separa_o1[0];
	       			$('#start_otros').val(dia_o1 + "-" + Mes_o1 + "-" + anio_o1);
	       		}else{
	       			$('#start_otros').val();
	       		}  
	       		

	       		if (response['consultam'][0].OTROS_AL) {
	       			var fecha_o2  = response['consultam'][0].OTROS_AL.date;
	       			var arr_o2	  = fecha_o2.split(" ");
	       			var mes_o2 	  = arr_o2[0];
	       			var separa_o2 = mes_o2.split("-"); 
	       			var Mes_o2 	  = separa_o2[2];
	       			var dia_o2    = separa_o2[1];
	       			var anio_o2   = separa_o2[0];
	       			$('#end_otros').val(dia_o2 + "-" + Mes_o2 + "-" + anio_o2);
	       		}else{
	       			$('#end_otros').val();
	       		} 
	       		

	       		if (response['consultam'][0].FECHA_PROCEDIIENTO) {
	       			var fecha_pro  = response['consultam'][0].FECHA_PROCEDIIENTO.date;
	       			var arr_pro	   = fecha_pro.split(" ");
	       			var mes_pro    = arr_pro[0];
	       			var separa_pro = mes_pro.split("-"); 
	       			var Mes_pro    = separa_pro[2];
	       			var dia_pro    = separa_pro[1];
	       			var anio_pro   = separa_pro[0];
	       			$('#fecha_proc').val(dia_pro + "-" + Mes_pro + "-" + anio_pro);
	       		} else{
	       			$('#fecha_proc').val();
	       		}
	       		

	       		var carpetanum = response['pac'][0];
	       		var imagencons = response['consultam'][0].IMAGEN
	       		var imgcons = "<?php echo $this->basePath(); ?>/public/imagenes/consultas/"+carpetanum+'/'+imagencons;
	       		$("#monitoreo").data("jqScribble").update({backgroundImage: imgcons});
	       		 $('#idconsm').val(response['consultam'][0].ID);
	       		mostrarReceta(response['consulta'][0]);
	       	},
	       error: function(){
	             toastr.error('Inténtalo más tarde.');
	       }
	   });
	}
	/** INICIA FOTOS DE CONSULTA */
	function fotosCons(){
		var formulario = new FormData($('#formularioFoto')[0]);	
		
		$.ajax({
	      type: "POST",
	      data:formulario,
          cache:false,
          async: false,
          contentType: false,
          processData: false,
	      url: "<?php echo $this->basePath() ?>/consultados/fotingasConsul",	      
	      dataType: "json",
		      success: function(data) {
		        mostrarImagenes();
	          },
		      error: function(data){
		     	console.log('errors');
		      }
		  });
	}


	$('#tomarFotos').click(function(){
		$('#camera').click();
			
		});
	// $('#camera').on('change',function(){
		
	// 	fotosCons();
		
	// });

	$("#camera").on('change', function () {
 	
	 //Get count of selected files
	 var countFiles = $(this)[0].files.length;

	 var imgPath = $(this)[0].value;
	 var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
	 var image_holder = $("#image-holder");
	 image_holder.empty();

	 if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
	     if (typeof (FileReader) != "undefined") {

	         //loop for each file selected for uploaded.
	         for (var i = 0; i < countFiles; i++) {

	             var reader = new FileReader();
	             reader.onload = function (e) {
	                 $("<img />", {
	                     "src": e.target.result,
	                         "class": "thumb-image"
	                 }).appendTo(image_holder);
	             }

	             image_holder.show();
	             reader.readAsDataURL($(this)[0].files[i]);
	         }

	     } else {
	         toastr.error("Esté navegaador no soporta FileReader.");
	     }
	 } else {
	     toastr.error("Seleccione solo imagenes");
	 }
 });

	
</script>