<div class="card">

	<!-- BEGIN BUSCADOR DE PACIENTES -->
	<div class="card-head style-primary-dark">
		<div class="tools pull-left">
			<form class="navbar-search" role="search">
                <div class="form-group">
                    <input type="text" id="buscadorpacientes" class="form-control" name="buscadorpacientes" placeholder="Buscar Paciente">
                    <input type="hidden" class="form-control" id="idpaciente">
                </div>
                <button type="submit" class="btn btn-icon-toggle ink-reaction"><i class="fa fa-search"></i></button>
            </form>
		</div><!--end .tools -->
		<div class="tools">
			<?php if(isset($paciente))  {  ?>
				<a onclick="nuevaConsulta(<?php echo $paciente[0]['ID']; ?>);" class="btn btn-icon-toggle ink-reaction" href="#">
	                <i class="fa fa-plus"></i>
	            </a>
            <?php } ?>
			<a class="btn btn-icon-toggle ink-reaction" href="#datosgenerales" data-toggle="offcanvas">
                <i class="fa fa-user"></i>
            </a>
        </div><!--end .tools -->
	</div>
	<!-- END BUSCADOR DE PACIENTES -->

	<!-- BEGIN CONTACT DETAILS -->
	<div class="card-tiles">
		<div class="hbox-md col-md-12">
			<div class="hbox-column col-md-9">
				<div class="row">
					<!-- BEGIN CONTACTS NAV -->
					<div class="col-sm-5 col-md-4 col-lg-3">
						<ul class="nav nav-pills nav-stacked">
							<li><small class="text-primary">CATEGORIAS</small></li>
							<li class="active"><a href="#" onclick="listaConsultas();">Consultas <span class="pull-right badge style-accent"><?php if(isset($consultas)){echo count($consultas);} ?></span></a></li>
							<!-- <li><a href="#">Estudios <span class="pull-right badge style-accent">52</span></a></li>
							<li><a href="#"> <span class="pull-right badge style-accent">71</span></a></li> -->
						</ul>
						<hr>
						<ul class="list divider-full-bleed">
							<li><small class="text-primary">LISTADO</small></li>
							<?php if(!isset($consultas)){ ?>
							<p>No hay consultas </p>
							<?php } else{?>
							<?php foreach ($consultas as $con) { ?>
								<li class="tile">
									<?php if($con['ESPEC'] == 'Cgineco'){ ?>
									<a class="tile-content ink-reaction" onclick="detalleConsulta(<?php echo $con['ID'];?>);">
										<div class="tile-text">
											<?php echo date_format($con['FECHA_CONS'],'Y-m-d'); ?>
											<small>
												<?php echo $con['MOTIVO']; ?>
											</small>
										</div>
										
										<div class="tile-icon">
											<span class="fa fa-stethoscope fa-2x text-primary"></span>
										</div>
									</a>
									<?php }else if($con['ESPEC'] == 'Expescar'){?>
									<a class="tile-content ink-reaction" onclick="detalleHisto(<?php echo $con['CONSULTA'];?>);">
										<div class="tile-text">
											<?php echo date_format($con['FECHA_CONS'],'Y-m-d'); ?>
											<small>
												<?php echo $con['MOTIVO']; ?>
											</small>
										</div>
										
										<div class="tile-icon">
											<span class="fa fa-stethoscope fa-2x text-accent"></span>
										</div>
									</a>
									<?php } ?>
								</li>
							<?php } ?>
							<?php } ?>
						</ul>
					</div><!--end .col -->
					<!-- END CONTACTS NAV -->

					<!-- BEGIN CONTACTS MAIN CONTENT -->
					<div class="col-sm-7 col-md-8 col-lg-9">
						<div class="margin-bottom-xxl">
							<div class="pull-left width-3 clearfix ">
								<?php if(!isset($paciente) || $paciente[0]['IMAGEN'] == '')  {  ?>
									<img alt="" src="<?php echo $this->basePath(); ?>/public/img/avatar7.jpg" class="img-circle size-2">
								<?php } else  {?>
									 <img  src="<?php echo $this->basePath().'/public/imagenes/Pacientes/'.$paciente[0]['ID'].'/'.$paciente[0]['IMAGEN'];?>"  class="img-circle size-2" >

                          		<?php } ?> 
							</div>
							<?php if(!isset($paciente)){ ?>
								<h1 class="text-light no-margin"><?php echo "No hay paciente definido"; ?></h1>
							<?php }else{ ?>
								<h1 class="text-light no-margin"><?php echo $paciente[0]['NOMBRE'].' '.$paciente[0]['APELLIDO_PATERNO'].' '.$paciente[0]['APELLIDO_MATERNO']; ?></h1>
							<?php } ?>
								&nbsp;&nbsp;
						</div><!--end .margin-bottom-xxl -->
						<ul class="nav nav-tabs" data-toggle="tabs">
							<li class="active"><a href="#verconsulta">CONSULTA</a></li>
							<li><a href="#notes">NOTAS</a></li>
							<li><a href="#historia">Historia Clinica</a></li>
							<li><a href="#videos">Videos</a></li>
						</ul>
						<div class="tab-content">
							<!-- BEGIN CONTACTS NOTES -->
							<div class="tab-pane" id="notes">
								<br/>
								<?php if(!isset($notas) || $notas == ''){ echo 'No hay Notas'; } else{ ?>
									<?php foreach($notas as $n) { ?>
									<div class="list-results list-results-underlined">
											<div class="col-xs-12">
												<p class="clearfix">
													<span class="fa fa-fw fa-file fa-2x pull-left text-primary"></span>
													<span class="pull-left">
														<span class="text-bold"><?php echo date_format($n['FECHA'],'Y-m-d'); ?></span><br/>
													</span>
												</p>
												<div>
													<em><?php echo $n['NOTAS']; ?></em>
												</div>
											</div><!--end .col -->
									</div><!--end .list-results -->
									<?php } ?>
								<?php } ?>
							</div>
							<!-- END CONTACTS NOTES -->

							<!-- BEGIN CONTACTS HISTORIA CLINICA -->
							<div class="tab-pane" id="historia">
								<br>
								<div id="verhistoriac"></div>
							</div>
							<!-- END CONTACTS HISTORIA CLINICA -->

							<!-- BEGIN VERCONSULTA  -->
							<div class="tab-pane-active" id="verconsulta">
								<br>
								<div class="row">
									<div class="col-md-12">
										<div id="consultita"></div>
									</div>
								</div>
							</div>
							<!-- END VERCONSULTA -->
							<!--Inicio mostrar videos -->
							<div class="tab-pane" id="videos">
								<br/>
								<!-- BEGIN FILE UPLOAD -->
								<div class="row">
									<?php if(isset($paciente))  {  ?>
									<div class=" col-md-12">
										<div class="card">
											<div class="card-head style-primary">
											
												<header>Subir Videos</header>
											</div>
											<div class="card-body no-padding">
												<form action="<?php echo $this->basePath() ?>/consultados/guardarvideo" class="dropzone dz-clickable" id="dropa">
												<input type="hidden" id="pacid" name="pacid" value= <?php echo $paciente[0]['ID'];?> >
												<div class="dz-message">
													<h3 >Agrega aquí los videos  <br/><br/></h3>
												</div>
												</form>
											</div><!--end .card-body -->
										</div><!--end .card -->
									</div><!--end .col -->
									<?php } ?>
								</div><!--end .row -->
								<!-- END FILE UPLOAD -->
							</div><!--Fin mostrar videos -->
						</div><!--end .tab-content -->
					</div><!--end .col -->
					<!-- END CONTACTS MAIN CONTENT -->
				</div><!--end .row -->
			</div><!--end .hbox-column -->
		</div>
	</div>
	<!-- END CONTACTS DETAILS -->
	<div class="offcanvas backdrop">
		<!-- BEGIN CONTACTS COMMON DETAILS -->
		<div id="datosgenerales" class="offcanvas-pane width-8">
			<div class="offcanvas-head">
                <header class="text-primary">Información del Paciente</header>
                <div class="offcanvas-tools">
                    <a class="btn btn-icon-toggle btn-default-light pull-right" data-dismiss="offcanvas">
                        <i class="md md-close"></i>
                    </a>
                </div>
            </div>
            <div class="offcanvas-body no-padding">
				<div class="hbox-column col-md-12 style-default-light">
					<div class="row">
						<div class="col-xs-12">
							<h4>Datos Personales</h4>
							<br/>
							<?php if(!isset($paciente)){ ?>
								<span class="text-medium style-warning">No hay usuario seleccionado</span>
							<?php }else{ ?>
							<dl class="dl-horizontal dl-icon">
								<dt><span class="fa fa-fw fa-gift fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Años</span><br/>
									<span class="text-medium"><?php echo date_format($paciente[0]['FECHA_NACIMIENTO'],'d/m/Y'); ?></span>
								</dd>
								<dt><span class="fa fa-fw fa-home fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Dirección</span><br/>
									<span class="text-medium"><?php echo $paciente[0]['CALLE']; ?>&nbsp;No. <?php echo $paciente[0]['NUMERO_EXT']; ?></span><br>
									<span class="text-medium"><?php echo $paciente[0]['COLONIA']; ?></span><br>
									<span class="text-medium"><span class="opacity-50">C.P. </span><?php echo $paciente[0]['CODIGO_POSTAL']; ?></span>
								</dd>
								<dt><span class="fa fa-fw fa-home fa-lg opacity-50"></span></dt>
								<dd>
									<span class="opacity-50">Tipo Sanguíneo</span><br/>
									<span class="text-medium"><?php echo $paciente[0]['CALLE']; ?></span>
								</dd>
							</dl><!--end .dl-horizontal -->
							<?php } ?>
							<br/>
							<h4>Antecedentes</h4>
							<br/>
							<?php if(!isset($paciente)){ ?>
								<span class="text-medium style-warning">No hay usuario seleccionado</span>
							<?php }else{ ?>
							<dl class="dl-horizontal dl-icon">
								<?php if(isset($antecedentes[0]['TABAQUISMO'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/cigarrete.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Tabaquismo</span><br/>
									<span class="text-medium"><?php echo $antecedentes[0]['TABAQUISMO']; ?></span><br/>
								</dd>
								<?php } ?>
								<?php if(isset($antecedentes[0]['TOXICOMANIAS'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/syringe.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Toxicomanias</span><br/>
									<span class="text-medium"><?php echo $antecedentes[0]['TOXICOMANIAS']; ?></span><br/>
								</dd>
								<?php } ?>
								<?php if(isset($antecedentes[0]['ALCOHOLISMO'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/wine.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Alcoholismo</span><br/>
									<span class="text-medium"><?php echo $antecedentes[0]['ALCOHOLISMO']; ?></span><br/>
								</dd>
								<?php } ?>
								<?php if(isset($antecedentes[0]['AUMENTO_PERDIDA'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/gainlossweight.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Aumento/Perdida de Peso</span><br/>
									<span class="text-medium"><?php if($antecedentes[0]['AUMENTO_PERDIDA'] == "1"){ echo 'Sí'; }else{?>
									<?php echo 'No'; }?>
									</span><br/>
								</dd>
								<?php } ?>
								<?php if(isset($antecedentes[0]['ALERGIAS'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/allergies.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Alergias</span><br/>
									<span class="text-medium"><?php echo $antecedentes[0]['ALERGIAS']; ?></span><br/>
								</dd>
								<?php } ?>
								<?php if(isset($antecedentes[0]['CIRUGIAS'])){ ?>
								<dt><span><img src="<?php echo $this->basePath();?>/public/img/surgery.png" alt="" width="18px" height="18px"></span></dt>
								<dd>
									<span class="opacity-50">Cirugias</span><br/>
									<span class="text-medium"><?php echo $antecedentes[0]['CIRUGIAS']; ?></span><br/>
								</dd>
								<?php } ?>
							</dl><!--end .dl-horizontal -->
							<?php } ?>
						</div><!--end .col -->
					</div><!--end .row -->
				</div><!--end .hbox-column -->
			</div>
		</div>
		<!-- END CONTACTS COMMON DETAILS -->	
	</div>
</div>
<form action='<?php echo $this->basePath()?>/consultados' method="post" name="fPac" id="fPac">
	<input type="hidden" value="" id="pac" name="pac"/>
</form>

<form action='<?php echo $this->basePath()?>/consultados/consultando' method="post" name="fCon" id="fCon">
	<input type="hidden" value="" id="pacienteid" name="pacienteid"/>
</form>

<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/jquery-ui/jquery-ui-theme.css" />
<script src="<?php echo $this->basePath() ?>/public/js/libs/dropzone/dropzone.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/exclie/consultados.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-ui/jquery-ui.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/exclie/pacientes.js"></script>
<script>

	var ruta = '<?php echo $this->basePath(); ?>';	

	function nuevaConsulta(pac)
	{
       	document.getElementById('pacienteid').value = pac;
        document.fCon.submit();
    }

    function detalleConsulta(id)
    {
    	$.ajax({
           type: "POST",
           url: "<?php echo $this->basePath() ?>/consultados/verconsulta",
           data: {id_consulta:id},
           dataType: "HTML",
           
           success: function(response) {
           		$('#consultita').html(response);

           },
           error: function(){
                 alert('Inténtalo más tarde.');
           }
       });
    }


    function detalleHisto(id)
    {
    	console.log(id);
    	$.ajax({
           type: "POST",
           url: "<?php echo $this->basePath() ?>/consultados/verhistoclinica",
           data: {id_consulta:id},
           dataType: "HTML",
           
           success: function(response) {
           		$('#verhistoriac').html(response);
           		$('#historia').addClass('active');
           },
           error: function(){
                 alert('Inténtalo más tarde.');
           }
       });
    }
    
	
</script>
