<style> 


.page {
  page-break-after:always;
  position: relative;
}
.gineco {
  page-break-after:always;
  position: relative;
}

@page{
  margin: 240px 60px 30px 30px 90px;
}
p {
  font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;
  font-size: 12px;
  font-style: normal;
  font-variant: normal;
  font-weight: 400;
  line-height: 10px;
}


</style>
<link type="text/css" rel="stylesheet" href="<?php echo getcwd() ?>/public/css/theme-default/bootstrap.css" />
<div class="page">
  <table style="width:100%;">
    <tbody>
      <tr>
        <td align="center" style="width:23%;"><img src="<?php echo getcwd().'/public/img/gine.png';?>" height="98"></td>
        <td style="width:43%; text-align: center;">
          <p style="font-size: 14px;"><b>Dr. Jaime Escárcega Preciado</b></p>
          <p>GINECOLOGÍA Y OBSTETRICIA / BIOLOGÍA DE LA REPRODUCCIÓN</p>
          <p><b>Cédula Profesional </b> 1363699 / Universidad Autónoma de Chihuahua</p>
          <p><b>Cédula Especialidad </b> 9426903 / Universidad Autónoma de Chihuahua</p>
        </td>
        <td style="width:33%; text-align: center;">
          <p> 
            <?php date_default_timezone_set('America/Chihuahua');
            $dias = array("Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sábado");
            $meses = array("enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre");
            echo date('d')." de ".$meses[date('n')-1]. " de ".date('Y') ;
            ?>
          </p>
        </td>
      </tr>
    </tbody>
  </table>
  <hr>
  <?php if(!isset($imagenes)){ ?>
  <table style="width:100%;">
    <tbody>
      <tr>
        <td style="width:33%; text-align: left;">
          <p><b>Paciente: </b> <?php echo $paciente[0]['APELLIDO_PATERNO'].' '.$paciente[0]['APELLIDO_MATERNO'].' '.$paciente[0]['NOMBRE']; ?></p>
          <p><b>Fecha de Consulta: </b><?php echo date_format($expescar[0]['FECHA_CONS'],'Y-m-d'); ?> </p>
        </td>
        <td style="width:33%; text-align: left;">
          <p><b>Sexo:</b> <?php if($paciente[0]['SEXO'] == 2){echo 'Femenino';} ?></p>
          <p><b>Motivo de Consulta: </b><?php echo $expescar[0]['PADECIMIENTO']; ?> </p>
        </td>
        <td style="width:33%; text-align: left;">
          <p><b>Fecha de Nacimiento:</b> <?php if($paciente[0]['FECHA_NACIMIENTO']){echo date_format($paciente[0]['FECHA_NACIMIENTO'],'Y-m-d');} ?></p>
        </td>
      </tr>
    </tbody>
  </table>
  <hr>
  
  <h2 class="text-primary">Historial Médico</h2>
  <h3 class="text-primary">Antecedentes No Patológicos</h3>
  <table style="width:100%;">
    <tbody>
      <tr>
        <td></td>
      </tr>
      <tr>
        <td style="width:33%; text-align: left;">
          <p><b>Tabaquismo:</b></p>
            <?php if($antes[0]['TABAQUISMO']){ echo $antes[0]['TABAQUISMO'];}else{ ?>
             <p>--</p>
            <?php } ?>
        </td>
        <td style="width:33%; text-align: left;">
          <p><b>Alcoholismo:</b></p> 
          <?php if($antes[0]['ALCOHOLISMO']){ echo $antes[0]['ALCOHOLISMO'];}else{ ?> 
            <p>--</p>
          <?php } ?>
        </td>
        <td style="width:33%; text-align: left;">
          <p><b>Drogas:</b></p>
          <?php if($antes[0]['TOXICOMANIAS']){ echo $antes[0]['TOXICOMANIAS'];}else{ ?> 
          <p>--</p>
          <?php } ?>
        </td>
      </tr>
    </tbody>
  </table>
  <h3 class="text-primary">Antecedentes Patológicos</h3>
  <table style="width:100%;">
    <tbody>
      <tr>
        <td></td>
      </tr>
      <tr>
        <td style="width:33%; text-align: left;">
          <p><b>Diabetes:</b></p>
          <?php if($antes[0]['DIABETES']){  ?>
            <?php if($antes[0]['DIABETES']==1) {?>
             <p>MADRE</p>
            <?php }if ($antes[0]['DIABETES']==2) { ?>
              <p>PADRE</p>
            <?php }if ($antes[0]['DIABETES']==3) { ?>
              <p>MADRE y PADRE</p>
            <?php }if ($antes[0]['DIABETES']==4) { ?>
              <p>ABUELA</p>
            <?php }if ($antes[0]['DIABETES']==5) { ?>
            <p>ABUELO</p>
            <?php }if ($antes[0]['DIABETES']==6) { ?>
            <p>ABUELA Y ABUELO</p>
            <?php } ?>
          <?php }else{ ?>
            <p>--</p>
          <?php } ?>
        </td>
        <td style="width:33%; text-align: left;">
          <p><b>Enfermedades Tiroideas:</b> </p>
          <?php if($antes[0]['TIROIDES']){ ?>
            <?php if($antes[0]['TIROIDES']==1) {?>
                <p>MADRE</p>
              <?php }if ($antes[0]['TIROIDES']==2) { ?>
                <p>PADRE</p>
              <?php }if ($antes[0]['TIROIDES']==3) { ?>
                <p>MADRE y PADRE</p>
              <?php }if ($antes[0]['TIROIDES']==4) { ?>
                <p>ABUELA</p>
              <?php }if ($antes[0]['TIROIDES']==5) { ?>
              <p>ABUELO</p>
              <?php }if ($antes[0]['TIROIDES']==6) { ?>
              <p>ABUELA Y ABUELO</p>
            <?php } ?>
          <?php }else{ ?>
            <p>--</p>
          <?php } ?>
        </td>
        <td style="width:33%; text-align: left;">
          <p><b>Cardiopatias:</b></p>
          <?php if($antes[0]['CARDIOPATIAS']){ ?> 
            <?php if($antes[0]['CARDIOPATIAS']==1) {?>
                  <p>MADRE</p>
                <?php }if ($antes[0]['CARDIOPATIAS']==2) { ?>
                  <p>PADRE</p>
                <?php }if ($antes[0]['CARDIOPATIAS']==3) { ?>
                  <p>MADRE y PADRE</p>
                <?php }if ($antes[0]['CARDIOPATIAS']==4) { ?>
                  <p>ABUELA</p>
                <?php }if ($antes[0]['CARDIOPATIAS']==5) { ?>
                <p>ABUELO</p>
                <?php }if ($antes[0]['CARDIOPATIAS']==6) { ?>
                <p>ABUELA Y ABUELO</p>
            <?php } ?>
          <?php }else{ ?>
          <p>--</p>
          <?php } ?>
        </td>
      </tr>
      <tr>
        <td style="width:33%; text-align: left;">
          <p><b>Cancer:</b></p>
          <?php if($antes[0]['CANCER']){ ?>
            <?php if($antes[0]['CANCER']==1) {?>
                  <p>MADRE</p>
                <?php }if ($antes[0]['CANCER']==2) { ?>
                  <p>PADRE</p>
                <?php }if ($antes[0]['CANCER']==3) { ?>
                  <p>MADRE y PADRE</p>
                <?php }if ($antes[0]['CANCER']==4) { ?>
                  <p>ABUELA</p>
                <?php }if ($antes[0]['CANCER']==5) { ?>
                <p>ABUELO</p>
                <?php }if ($antes[0]['CANCER']==6) { ?>
                <p>ABUELA Y ABUELO</p>
             <?php } ?>
          <?php }else{ ?>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:33%; text-align: left;">
          <p><b>Hipertensión:</b></p>
          <?php if($antes[0]['HIPERTENSION']){ ?>
            <?php if($antes[0]['HIPERTENSION']==1) {?>
                  <p>MADRE</p>
                <?php }if ($antes[0]['HIPERTENSION']==2) { ?>
                  <p>PADRE</p>
                <?php }if ($antes[0]['HIPERTENSION']==3) { ?>
                  <p>MADRE y PADRE</p>
                <?php }if ($antes[0]['HIPERTENSION']==4) { ?>
                  <p>ABUELA</p>
                <?php }if ($antes[0]['HIPERTENSION']==5) { ?>
                <p>ABUELO</p>
                <?php }if ($antes[0]['HIPERTENSION']==6) { ?>
                <p>ABUELA Y ABUELO</p>
            <?php } ?>
          <?php }else{ ?>
          <p>--</p>
          <?php } ?>
        </td>
      </tr>
    </tbody>
  </table>
  <h3 class="text-primary">Alergias</h3>
  <table style="width:100%;">
    <tbody>
      <tr>
        <td></td>
      </tr>
      <tr>
        <td align="left">
          <p><?php if($antes[0]['ALERGIAS']){ echo $antes[0]['ALERGIAS'];}else{  ?></p>
          <p>--</p>
          <?php } ?>
        </td>
      </tr>
    </tbody>
  </table>
  <h3 class="text-primary">Antecedentes Gineco-Obstericos</h3>
  <!-- comienza expescar -->
  <table style="width:100%;">
    <tbody>
      <tr>
        <td></td>
      </tr>
      <tr>
        <td style="width:30%; text-align: left;">
          <p><b>Mernarca:</b></p>
          <p><?php if($expescar[0]['MENARCA']){ echo $expescar[0]['MENARCA'];}else{  ?></p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:30%; text-align: left;">
          <p><b>FUM:</b> </p>
          <p><?php if($expescar[0]['FUM']){ echo $expescar[0]['FUM'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:30%; text-align: left;">
          <p><b>IVSA:</b> </p>
          <p><?php if($expescar[0]['IVSA']){ echo $expescar[0]['IVSA'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:30%; text-align: left;">
          <p><b>Papanicolao:</b> </p>
          <p><?php if($expescar[0]['PAP']){ echo $expescar[0]['PAP'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
      </tr>
      <tr>
        <td style="width:20%; text-align: left;">
          <p><b>Ciclos:</b></p>
          <p><?php if($expescar[0]['CICLOS']){ echo $expescar[0]['CICLOS'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:20%; text-align: left;">
          <p><b>Duración:</b></p>
          <p><?php if($expescar[0]['DURACION']){ echo $expescar[0]['DURACION'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:20%; text-align: left;">
          <p><b>Duración:</b></p>
          <p><?php if($expescar[0]['DURACION']){ echo $expescar[0]['DURACION'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:20%; text-align: left;">
          <p><b>Dismenorrea:</b> </p>
          <p><?php if($expescar[0]['DISMENORREA']){ echo $expescar[0]['DISMENORREA'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:20%; text-align: left;">
          <p><b>Flujo:</b> </p>
          <p><?php if($expescar[0]['FLUJO']){ echo $expescar[0]['FLUJO'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
      </tr>
      <tr>
        <td style="width:30%; text-align: left;">
          <p><b>Anticonceptivos:</b> </p>
          <p><?php if($expescar[0]['ANTICONCEPTIVOS']){ echo $expescar[0]['ANTICONCEPTIVOS'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:30%; text-align: left;">
          <p><b>Galactorrea:</b> </p>
          <p><?php if($expescar[0]['GALACTORREA']){ echo $expescar[0]['GALACTORREA'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:30%; text-align: left;">
          <p><b>Hirsutismo:</b> </p>
          <p><?php if($expescar[0]['HIRSUTISM']){ echo $expescar[0]['HIRSUTISM'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:30%; text-align: left;">
          <p><b>Cirugias Previas:</b> </p>
          <p><?php if($expescar[0]['CIRUGIAS_PREVIAS']){ echo $expescar[0]['CIRUGIAS_PREVIAS'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
      </tr>
      <tr>
         <td style="width:20%; text-align: left;">
           <p><b>Gestas:</b></p>
          <p><?php if($expescar[0]['GESTAS']){ echo $expescar[0]['GESTAS'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:20%; text-align: left;">
          <p><b>Partos:</b></p>
          <p><?php if($expescar[0]['PARTOS']){ echo $expescar[0]['PARTOS'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:20%; text-align: left;">
          <p><b>Abortos:</b></p>
          <p><?php if($expescar[0]['ABORTOS']){ echo $expescar[0]['ABORTOS'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:20%; text-align: left;">
           <p><b>Cesareas:</b></p>
          <p><?php if($expescar[0]['CESAREAS']){ echo $expescar[0]['CESAREAS'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:20%; text-align: left;">
           <p><b>Ectopicos:</b></p>
          <p><?php if($expescar[0]['ECTOPICOS']){ echo $expescar[0]['ECTOPICOS'];}else{ ?> </p>
          <p>--</p>
          <?php } ?>
        </td>
      </tr>
    </tbody>
  </table>
  <h3 class="text-primary">Examén Físico</h3>
  <table style="width:100%;">
    <tbody>
      <tr>
        <td></td>
      </tr>
      <tr>
        <td style="width:50%; text-align: left;">
          <p><b>Sistema Digestivo:</b><?php if($expescar[0]['SIST_DIGESTIVO']){ echo $expescar[0]['SIST_DIGESTIVO'];}else{  ?></p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:50%; text-align: left;">
          <p><b>Sistema Urinario:</b><?php if($expescar[0]['SIST_URINARIO']){ echo $expescar[0]['SIST_URINARIO'];}else{  ?></p>
          <p>--</p>
          <?php } ?>
        </td>
      </tr>
    </tbody>
  </table>
  <h3 class="text-primary">Signos Vitales</h3>
  <table style="width:100%;">
    <tbody>
      <tr>
        <td></td>
      </tr>
      <tr>
        <td style="width:33%; text-align: left;">
          <p><b>Peso:</b><?php if($expescar[0]['PESO']){ echo $expescar[0]['PESO'];}else{  ?></p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:33%; text-align: left;">
          <p><b>Presión:</b><?php if($expescar[0]['PRESION']){ echo $expescar[0]['PRESION'];}else{  ?></p>
          <p>--</p>
          <?php } ?>
        </td>
        <td style="width:33%; text-align: left;">
          <p><b>Tiroides:</b><?php if($expescar[0]['TIROIDESNUM']){ echo $expescar[0]['TIROIDESNUM'];}else{  ?></p>
          <p>--</p>
          <?php } ?>
        </td>
      </tr>
    </tbody>
  </table>
  <h3 class="text-primary">Exploración Física</h3>
  <p><?php if($expescar[0]['IMAGEN']){ ?>
    <img src="<?php echo getcwd().'/public/imagenes/consultas/'.$paciente[0]['ID'].'/'.$expescar[0]['IMAGEN'];?>" width="100%">
    <?php }else{  ?></p>
    <p>--</p>
  <?php } ?>
  <h3 class="text-primary">Diagnóstico y Tratamiento</h3>
  <table style="width:100%;">
    <tbody>
      <tr>
        <td></td>
      </tr>
      <tr>
        <td style="width:50%; text-align: left;">
          <p><b>Tratamiento:</b></p>
           <?php if($expescar[0]['PLAN']){ echo $expescar[0]['PLAN'];}else{  ?>
           <p>--</p>
          <?php } ?>
        </td>
        <td style="width:50%; text-align: left;">
          <p><b>Impresión Diagnostica:</b></p>
          <?php if($expescar[0]['IMX']){ echo $expescar[0]['IMX'];}else{  ?>
          <p>--</p>
          <?php } ?>
        </td>
      </tr>
     </tbody>
  </table>
  <!-- termina expescar -->
  <br><table style='page-break-after:always;'></br></table><br>
  <!-- COMIENZA GINE -->
  <?php if($gine){ ?>
      <?php foreach ($gine as $gin) { ?>
        <div class="gineco">
          <hr>
            <p><b>Fecha de Consulta: </b><?php echo date_format($gin[0]['FECHA_CONS'],'Y-m-d'); ?> </p>
            <p><b>Motivo de Consulta: </b><?php echo $gin[0]['MOTIVO_CONS']; ?> </p>
          <hr>
          <h3 class="text-primary">Datos Ginecologicos</h3>
              <table style="width:100%;">
                <tbody>
                  <tr>
                    <td></td>
                  </tr>
                  <tr>
                    <td style="width:33%; text-align: left;">
                      <p><b>FUM: </b><?php if($gin[0]['FUM']){ echo date_format($gin[0]['FUM'],'Y-m-d');}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                       <p><b>Ciclo: </b><?php if($gin[0]['CICLO']){ echo $gin[0]['CICLO'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                       <p><b>Tiroides: </b><?php if($gin[0]['TIROIDESNUM']){ echo $gin[0]['TIROIDESNUM'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                    <td style="width:33%; text-align: left;">
                      <p><b>Gestas: </b><?php if($gin[0]['GESTAS']){ echo $gin[0]['GESTAS'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                      <p><b>Partos: </b><?php if($gin[0]['PARTOS']){ echo $gin[0]['PARTOS'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                      <p><b>Cesareas: </b><?php if($gin[0]['CESAREAS']){ echo $gin[0]['CESAREAS'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                    <td style="width:33%; text-align: left;">
                      <p><b>Abortos: </b><?php if($gin[0]['ABORTOS']){ echo $gin[0]['ABORTOS'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                      <p><b>Ectopicos: </b><?php if($gin[0]['ECTOPICOS']){ echo $gin[0]['ECTOPICOS'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                  </tr>
                </tbody>
              </table>
              <h3 class="text-primary">Signos Vitales</h3>
              <table style="width:100%;">
                <tbody>
                  <tr>
                    <td></td>
                  </tr>
                  <tr>
                    <td style="width:33%; text-align: left;">
                      <p><b>Peso:</b><?php if($gin[0]['PESO']){ echo $gin[0]['PESO'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                    <td style="width:33%; text-align: left;">
                      <p><b>Presión:</b><?php if($gin[0]['PRESION']){ echo $gin[0]['PRESION'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                    <td style="width:33%; text-align: left;">
                      <p><b>Tiroides:</b><?php if($gin[0]['TIROIDESNUM']){ echo $gin[0]['TIROIDESNUM'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                  </tr>
                </tbody>
              </table>
              <h3 class="text-primary">Exploración Física</h3>
              <p><?php if($gin[0]['IMAGEN']){ ?>
                <img src="<?php echo getcwd().'/public/imagenes/consultas/'.$paciente[0]['ID'].'/'.$gin[0]['IMAGEN'];?>" width="100%">
                <?php }else{  ?></p>
                <p>--</p>
              <?php } ?>
              <h3 class="text-primary">Diagnóstico y Tratamiento</h3>
              <table style="width:100%;">
                <tbody>
                  <tr>
                    <td></td>
                  </tr>
                  <tr>
                    <td style="width:50%; text-align: left;">
                      <p><b>Tratamiento:</b></p>
                       <?php if($gin[0]['PLAN']){ echo $gin[0]['PLAN'];}else{  ?>
                       <p>--</p>
                      <?php } ?>
                    </td>
                    <td style="width:50%; text-align: left;">
                      <p><b>Impresión Diagnostica:</b></p>
                      <?php if($gin[0]['IMX']){ echo $gin[0]['IMX'];}else{  ?>
                      <p>--</p>
                      <?php } ?>
                    </td>
                  </tr>
                 </tbody>
              </table>
             <!--  <h3 class="text-primary">Imágenes de la consulta</h3>
                  <?php $fotos = $gin[1]['imagenes']; ?> 
                  <?php if($fotos){ ?>
                    <?php print_r($fotos); ?>
                    <?php foreach ($fotos as $foti) { ?>
                       <img src="<?php echo getcwd().'/public/imagenes/consultas/'.$paciente[0]['ID'].'/fotos/'.$foti['IMAGEN'];?>" width="100%">
                    <?php } ?>
                   
                  <?php }else{ ?>
                  <p>--</p>
                  <?php } ?> -->
        </div>    
            
      <?php } ?>
  <?php } ?>

  <!-- COMIENZA MONITOREOS -->
  <?php if($monito){ ?>
    <?php foreach ($monito as $mon) { ?>
      <div class="gineco">
          <hr>
            <p><b>Motivo de Consulta: </b>Monitoreo </p>
          <hr>
          <h3 class="text-primary">Diagnóstico y Tratamiento</h3>
          <table style="width:100%;">
            <tbody>
              <tr>
                <td></td>
              </tr>
              <tr>
                <td style="width:50%; text-align: left;">
                  <p><b>Reproducción Asistida:</b></p>
                   <?php if($mon[0]['REPRODUCCION']){ echo $mon[0]['REPRODUCCION'];}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:50%; text-align: left;">
                  <p><b>Protocolo:</b></p>
                  <?php if($mon[0]['PROTOCOLO']){ echo $mon[0]['PROTOCOLO'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>FUR:</b></p>
                   <?php if($mon[0]['FUR']){ echo date_format($mon[0]['FUR'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Anticonceptivo o Progestina:</b></p>
                  <?php if($mon[0]['PROGESTINA']){ echo $mon[0]['PROGESTINA'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['PROGESTINA_DEL']){ echo date_format($mon[0]['PROGESTINA_DEL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['PROGESTINA_AL']){ echo date_format($mon[0]['PROGESTINA_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>FPM:</b></p>
                   <?php if($mon[0]['FPM']){ echo date_format($mon[0]['FPM'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>GNRH:</b></p>
                  <?php if($mon[0]['GNRH']){ echo $mon[0]['GNRH'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['GNRHD_EL']){ echo date_format($mon[0]['GNRHD_EL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['GNRH_AL']){ echo date_format($mon[0]['GNRH_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>Menotropinas:</b></p>
                  <?php if($mon[0]['MENOTROPINAS']){ echo $mon[0]['MENOTROPINAS'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['MENOTROPINAS_DEL']){ echo date_format($mon[0]['MENOTROPINAS_DEL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['MENOTROPINAL_AL']){ echo date_format($mon[0]['MENOTROPINAL_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;"></td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>FSH:</b></p>
                  <?php if($mon[0]['FSH']){ echo $mon[0]['FSH'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['FSH_DEL']){ echo date_format($mon[0]['FSH_DEL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['FSH_AL']){ echo date_format($mon[0]['FSH_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;"></td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>Primogyn:</b></p>
                  <?php if($mon[0]['PRIMOGYN']){ echo $mon[0]['PRIMOGYN'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['PRIMOGYN_DEL']){ echo date_format($mon[0]['PRIMOGYN_DEL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['PRIMOGYN_AL']){ echo date_format($mon[0]['PRIMOGYN_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;"></td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>Otros:</b></p>
                  <?php if($mon[0]['OTROS']){ echo $mon[0]['OTROS'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['OTROS_DEL']){ echo date_format($mon[0]['OTROS_DEL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['OTROS_AL']){ echo date_format($mon[0]['OTROS_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;"></td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>Fecha de Procedimiento:</b></p>
                  <?php if($mon[0]['FECHA_PROCEDIIENTO']){ echo date_format($mon[0]['FECHA_PROCEDIIENTO'],'Y-m-d');}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Residente:</b></p>
                   <?php if($mon[0]['RESIDENTE']){ echo $mon[0]['RESIDENTE'];}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Autorizado:</b></p>
                   <?php if($mon[0]['AUTORIZADO']){ echo $mon[0]['AUTORIZADO'];}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Enviado:</b></p>
                   <?php if($mon[0]['ENVIADO']){ echo $mon[0]['ENVIADO'];}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
              </tr>
             </tbody>
          </table>
          <img src="<?php echo getcwd().'/public/imagenes/consultas/'.$paciente[0]['ID'].'/'.$mon[0]['IMAGEN'];?>" width="100%"><br>
      </div>
    <?php } ?>
  <?php } ?>
  <!-- Termina monitoreos -->
<?php }else{ ?>
    <!-- Aqui comienza el historial que contiene fotos -->
    <h2 class="text-primary">Historial Médico</h2>
   
    <?php foreach ($imagenes as $ima) { ?>
      <img src="<?php echo getcwd().'/public/imagenes/consultas/'.$paciente[0]['ID'].'/'.$ima['IMAGEN'];?>" width="100%"><br>
    
    <?php } ?>
    <br><table style='page-break-after:always;'></br></table><br>
    <!-- COMIENZA GINE -->
    <?php if($gine){ ?>
      <?php foreach ($gine as $gin) { ?>
        <div class="gineco">
          <hr>
            <p><b>Fecha de Consulta: </b><?php echo date_format($gin[0]['FECHA_CONS'],'Y-m-d'); ?> </p>
            <p><b>Motivo de Consulta: </b><?php echo $gin[0]['MOTIVO_CONS']; ?> </p>
          <hr>
          <h3 class="text-primary">Datos Ginecologicos</h3>
              <table style="width:100%;">
                <tbody>
                  <tr>
                    <td></td>
                  </tr>
                  <tr>
                    <td style="width:33%; text-align: left;">
                      <p><b>FUM: </b><?php if($gin[0]['FUM']){ echo date_format($gin[0]['FUM'],'Y-m-d');}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                       <p><b>Ciclo: </b><?php if($gin[0]['CICLO']){ echo $gin[0]['CICLO'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                       <p><b>Tiroides: </b><?php if($gin[0]['TIROIDESNUM']){ echo $gin[0]['TIROIDESNUM'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                    <td style="width:33%; text-align: left;">
                      <p><b>Gestas: </b><?php if($gin[0]['GESTAS']){ echo $gin[0]['GESTAS'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                      <p><b>Partos: </b><?php if($gin[0]['PARTOS']){ echo $gin[0]['PARTOS'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                      <p><b>Cesareas: </b><?php if($gin[0]['CESAREAS']){ echo $gin[0]['CESAREAS'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                    <td style="width:33%; text-align: left;">
                      <p><b>Abortos: </b><?php if($gin[0]['ABORTOS']){ echo $gin[0]['ABORTOS'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                      <p><b>Ectopicos: </b><?php if($gin[0]['ECTOPICOS']){ echo $gin[0]['ECTOPICOS'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                  </tr>
                </tbody>
              </table>
              <h3 class="text-primary">Signos Vitales</h3>
              <table style="width:100%;">
                <tbody>
                  <tr>
                    <td></td>
                  </tr>
                  <tr>
                    <td style="width:33%; text-align: left;">
                      <p><b>Peso:</b><?php if($gin[0]['PESO']){ echo $gin[0]['PESO'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                    <td style="width:33%; text-align: left;">
                      <p><b>Presión:</b><?php if($gin[0]['PRESION']){ echo $gin[0]['PRESION'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                    <td style="width:33%; text-align: left;">
                      <p><b>Tiroides:</b><?php if($gin[0]['TIROIDESNUM']){ echo $gin[0]['TIROIDESNUM'];}else{  ?></p>
                      <p>--</p>
                      <?php } ?>
                    </td>
                  </tr>
                </tbody>
              </table>
              <h3 class="text-primary">Exploración Física</h3>
              <p><?php if($gin[0]['IMAGEN']){ ?>
                <img src="<?php echo getcwd().'/public/imagenes/consultas/'.$paciente[0]['ID'].'/'.$gin[0]['IMAGEN'];?>" width="100%">
                <?php }else{  ?></p>
                <p>--</p>
              <?php } ?>
              <h3 class="text-primary">Diagnóstico y Tratamiento</h3>
              <table style="width:100%;">
                <tbody>
                  <tr>
                    <td></td>
                  </tr>
                  <tr>
                    <td style="width:50%; text-align: left;">
                      <p><b>Tratamiento:</b></p>
                       <?php if($gin[0]['PLAN']){ echo $gin[0]['PLAN'];}else{  ?>
                       <p>--</p>
                      <?php } ?>
                    </td>
                    <td style="width:50%; text-align: left;">
                      <p><b>Impresión Diagnostica:</b></p>
                      <?php if($gin[0]['IMX']){ echo $gin[0]['IMX'];}else{  ?>
                      <p>--</p>
                      <?php } ?>
                    </td>
                  </tr>
                 </tbody>
              </table>
              <!-- <h3 class="text-primary">Imágenes de la consulta</h3>
                  <?php $fotos = $gin[1]['imagenes']; ?> 
                  <?php if($fotos){ ?>
                    <?php print_r($fotos); ?>
                    <?php foreach ($fotos as $foti) { ?>
                       <img src="<?php echo getcwd().'/public/imagenes/consultas/'.$paciente[0]['ID'].'/fotos/'.$foti['IMAGEN'];?>" width="100%">
                    <?php } ?>
                   
                  <?php }else{ ?>
                  <p>--</p>
                  <?php } ?> -->
        </div>    
            
      <?php } ?>
    <?php } ?>

    <!-- COMIENZA MONITOREOS -->
  <?php if($monito){ ?>
    <?php foreach ($monito as $mon) { ?>
      <div class="gineco">
          <hr>
            <p><b>Motivo de Consulta: </b>Monitoreo </p>
          <hr>
          <h3 class="text-primary">Diagnóstico y Tratamiento</h3>
          <table style="width:100%;">
            <tbody>
              <tr>
                <td></td>
              </tr>
              <tr>
                <td style="width:50%; text-align: left;">
                  <p><b>Reproducción Asistida:</b></p>
                   <?php if($mon[0]['REPRODUCCION']){ echo $mon[0]['REPRODUCCION'];}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:50%; text-align: left;">
                  <p><b>Protocolo:</b></p>
                  <?php if($mon[0]['PROTOCOLO']){ echo $mon[0]['PROTOCOLO'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>FUR:</b></p>
                   <?php if($mon[0]['FUR']){ echo date_format($mon[0]['FUR'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Anticonceptivo o Progestina:</b></p>
                  <?php if($mon[0]['PROGESTINA']){ echo $mon[0]['PROGESTINA'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['PROGESTINA_DEL']){ echo date_format($mon[0]['PROGESTINA_DEL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['PROGESTINA_AL']){ echo date_format($mon[0]['PROGESTINA_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>FPM:</b></p>
                   <?php if($mon[0]['FPM']){ echo date_format($mon[0]['FPM'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>GNRH:</b></p>
                  <?php if($mon[0]['GNRH']){ echo $mon[0]['GNRH'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['GNRHD_EL']){ echo date_format($mon[0]['GNRHD_EL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['GNRH_AL']){ echo date_format($mon[0]['GNRH_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>Menotropinas:</b></p>
                  <?php if($mon[0]['MENOTROPINAS']){ echo $mon[0]['MENOTROPINAS'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['MENOTROPINAS_DEL']){ echo date_format($mon[0]['MENOTROPINAS_DEL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['MENOTROPINAL_AL']){ echo date_format($mon[0]['MENOTROPINAL_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;"></td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>FSH:</b></p>
                  <?php if($mon[0]['FSH']){ echo $mon[0]['FSH'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['FSH_DEL']){ echo date_format($mon[0]['FSH_DEL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['FSH_AL']){ echo date_format($mon[0]['FSH_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;"></td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>Primogyn:</b></p>
                  <?php if($mon[0]['PRIMOGYN']){ echo $mon[0]['PRIMOGYN'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['PRIMOGYN_DEL']){ echo date_format($mon[0]['PRIMOGYN_DEL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['PRIMOGYN_AL']){ echo date_format($mon[0]['PRIMOGYN_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;"></td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>Otros:</b></p>
                  <?php if($mon[0]['OTROS']){ echo $mon[0]['OTROS'];}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Del:</b></p>
                   <?php if($mon[0]['OTROS_DEL']){ echo date_format($mon[0]['OTROS_DEL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Al:</b></p>
                   <?php if($mon[0]['OTROS_AL']){ echo date_format($mon[0]['OTROS_AL'],'Y-m-d');}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;"></td>
              </tr>
              <tr>
                <td style="width:25%; text-align: left;">
                  <p><b>Fecha de Procedimiento:</b></p>
                  <?php if($mon[0]['FECHA_PROCEDIIENTO']){ echo date_format($mon[0]['FECHA_PROCEDIIENTO'],'Y-m-d');}else{  ?>
                  <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Residente:</b></p>
                   <?php if($mon[0]['RESIDENTE']){ echo $mon[0]['RESIDENTE'];}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Autorizado:</b></p>
                   <?php if($mon[0]['AUTORIZADO']){ echo $mon[0]['AUTORIZADO'];}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
                <td style="width:25%; text-align: left;">
                  <p><b>Enviado:</b></p>
                   <?php if($mon[0]['ENVIADO']){ echo $mon[0]['ENVIADO'];}else{  ?>
                   <p>--</p>
                  <?php } ?>
                </td>
              </tr>
             </tbody>
          </table>
          <img src="<?php echo getcwd().'/public/imagenes/consultas/'.$paciente[0]['ID'].'/'.$mon[0]['IMAGEN'];?>" width="100%"><br>
      </div>
    <?php } ?>
  <?php } ?>
  <!-- Termina monitoreos -->
  <?php } ?>
    
</div> 

 
