<style> 
.page {
position: relative;
}
.pagepr {
page-break-before: always;
position: relative;
}

.page p.re {
    margin: 70px 150px 100px 70px;
    font-size: 85%;

}

.page p.pr {
    margin: 79px 150px 10px 20px;
    font-size: 85%;
}

.pagepr p.pr2 {
    margin: 0 0 0 110;
    font-size: 85%;
}
p{
  font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;
}

</style>

<div class="page">
  <p class="re">
      <?php date_default_timezone_set('America/Chihuahua');
            $dias = array("Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sábado");
            $meses = array("enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre");
            echo date('d')." de ".$meses[date('n')-1]. " de ".date('Y') ;
      ?>
      <br />
     <?php  echo $pacienten.' '.$pacientep.' '.$pacientem; ?>
      <input type="hidden" name="id" value="<?php echo $idp ?>" />
      <table style="position: fixed; top:150px; margin: 0 0 0 50; font-size: 85%">  
      
      <?php foreach($medicinas as $s){?>
        <tr>
          <td><b><?php echo $s['MEDICAMENTO']['NOMBRE']; ?></b></td> 
          <td><?php echo '('.$s['FRECUENCIA'].')'; ?></td>                          
        </tr>
      <?php } ?>
        <tr>
          <td>
            
          </td>
        </tr>  
        <tfoot style="position: fixed; margin: 0 0 20 50; font-size: 85%">
          <tr>
            <td><?php if ($medicinas[0]['RECETA']['INDICACIONES_ADICIONALES'] ) { ?>
              <p><b>Indicaciones Adicionales: </b><br> <?php echo $medicinas[0]['RECETA']['INDICACIONES_ADICIONALES']; ?></p>
            <?php } ?></td>
          </tr>
        </tfoot>
      </table>
  </p>   
<div/>

