<style> 


.page {
  page-break-after:always;
  position: relative;
}
.page p.re {
    margin: 158px 150px 30px 80px;
    font-size: 85%;

}
.page p.texto
{
  margin: 0px 150px 100px 60px;
    font-size: 85%;
}
p {
  font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;
  font-size: 12px;
  font-style: normal;
  font-variant: normal;
  font-weight: 400;
  line-height: 26px;
}
#hojam{
  position: fixed; bottom:60px; top:-50px; right:-60px; left: -50px;
}

@page{
  margin: 240px 60px 30px 30px 90px;
}


</style>


<?php 

$texto = $ordenes[0]['DATOSNUEVOS'];
$separarTexto = explode(".*", $texto);

?>

<?php foreach($ordenes as $key => $orden){?>
  <div id="hojam"> <img src="<?php echo getcwd().'/public/img/hojaMembretadaStarM.jpg';?>" height="100%" width="100%"></div>
  <div class="page">
    
    <p class="re">
      <?php date_default_timezone_set('America/Chihuahua');
        $dias = array("Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sábado");
        $meses = array("enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre");
        echo date('d')." de ".$meses[date('n')-1]. " de ".date('Y') ;
      ?>
      <br>
      <?php  echo $pacienten.' '.$pacientep.' '.$pacientem; ?>
    </p>
    <p class="texto">
      <p><b><?php echo $orden['NOMBRE']?></b></p><br>
      <?php $key2 =$key+1;?>
      <p><?php echo $separarTexto[$key] ?></p><br>
      
    </p>
  </div>
  
   <?php } ?>

 

 
