<div class="section-body">
	<div class="card">
		<div class="card-head style-primary">
			<header>Descargar Expediente de Paciente</header>
		</div>
		<div class="card-body">
			<div class="table-resposive">
				<table id="datatable1"  class="table table-striped table-hover" cellspacing="0" width="100%">
			        <thead>
			            <tr>
			            	<th>ID</th>
							<th>Apellido Paterno</th>
							<th>Apellido Materno</th>
							<th>Nombre(s)</th>
							<th>Telefono</th>
							<th>Dirección</th>
							<th class="no-sort"></th>
						</tr>
			        </thead>
			        <tbody id="listado">
						<?php foreach($pacientes as $pac) {  ?>
							<tr>
								<td><?php echo $pac['ID'];?></td>											
								<td><?php echo $pac['APELLIDO_PATERNO'];?></td>
								<td><?php echo $pac['APELLIDO_MATERNO'];?></td>
								<td><?php echo $pac['NOMBRE'];?></td>
								<td><?php echo $pac['TELEFONO_1'];?></td>
								<td><?php echo $pac['CALLE'].' '.$pac['NUMERO_EXT'];?></td>
								<td><a onclick="descarga(<?php echo $pac['ID'];?>);" class="btn btn-icon-toggle ink-reaction" href="#"><i class="fa fa-download"></i></a></td>
							</tr>
						<?php } ?> 
					</tbody>
			    </table>
			</div>	
					
			
		</div>
	</div>
</div>


<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-1/libs/jquery-ui/jquery-ui-theme.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/DataTables/jquery.dataTables.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/DataTables/extensions/dataTables.colVis.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/DataTables/extensions/dataTables.tableTools.css" />



<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-ui/jquery-ui.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/DataTables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/core/demo/DemoTableDynamic.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/inputmask/jquery.inputmask.bundle.min.js"></script>


<script>
var editor;
	$(document).ready(function () {
		var ruta = "<?php echo $this->basePath() ?>";
		$(":input").inputmask();
		$('#modAddesc').hide();
		
		
	});

	function mostrarpacientes(){
		$.ajax({
		    type: "POST",
		    url: "<?php echo $this->basePath() ?>/consultados/getpacientes",
		    dataType: "json",
		    
		    success: function(data) {
		      document.getElementById("listado").innerHTML="";
		      for (var i = 0; i < data['pacientes'].length; i++) {
				var row = $("<tr />")
			    $("#listado").append(row); 
			    row.append($("<td>" + data['pacientes'][i].ID + "</td>"));
			    row.append($("<td>" + data['pacientes'][i].APELLIDO_PATERNO + "</td>"));
			    row.append($("<td>" + data['pacientes'][i].APELLIDO_MATERNO + "</td>"));
			    row.append($("<td>" + data['pacientes'][i].NOMBRE + "</td>"));
			    row.append($("<td>" + data['pacientes'][i].TELEFONO_1 + "</td>"));
			    row.append($("<td>" + data['pacientes'][i].CALLE +' '+ data['pacientes'][i].NUMERO_EXT +"</td>"));
			    row.append($("<td><a onclick='borrar(" + data['pacientes'][i].ID + ");' class='btn btn-icon-toggle ink-reaction' href='#'><i class='fa fa-trash-o'></i></a></td>"));
			  }	
		    },
		    error: function() {
		        toastr.error('Ocurrió un error, inténtelo de nuevo mas tarde');
		    }
		});
	}
	
	function descarga(id){
		window.open('generahistorial/'+id); 
	}


</script>