<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/estilos.css" />
<div class="row">
<!-- BEGIN CANVAS -->
<div class="card-tiles">
	<div style="overflow: hidden; margin-bottom: 5px;">
		<div class="column-right links" id="colores2">
			<strong>COLORES:</strong>
				<button type="button" onclick='$("#monitoreo").data("jqScribble").update({brushColor: "rgb(32,37,43)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-default-dark fa fa-pencil" data-toggle="tooltip" data-original-title="Negro"></button>
				<button type="button" onclick='$("#monitoreo").data("jqScribble").update({brushColor: "rgb(244,67,54)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-danger fa fa-pencil" data-toggle="tooltip" data-original-title="Rojo"></button>
				<button type="button" onclick='$("#monitoreo").data("jqScribble").update({brushColor: "rgb(76,175,80)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-success fa fa-pencil" data-toggle="tooltip" data-original-title="Verde"></button>
				<button type="button" onclick='$("#monitoreo").data("jqScribble").update({brushColor: "rgb(33,150,243)",brushSize:"2"});' class="btn ink-reaction btn-raised btn-sm btn-info fa fa-pencil" data-toggle="tooltip" data-original-title="Azul"></button>
				<button type="button" onclick='$("#monitoreo").data("jqScribble").update({brushColor: "rgb(255,255,255)",brushSize:"30"});' class="btn ink-reaction btn-raised btn-sm btn-default-bright fa fa-eraser" data-toggle="tooltip" data-original-title="Borrador"></button>
		</div>
	</div>
	<canvas id="monitoreo"></canvas>
	<div class="pull-right">	
	<button type="button" class="btn btn-raised btn-primary ink-reaction" onclick="guardamonitoreo()" id="saveCons">Guardar</button>
	</div>
</div><!--end .card-tiles -->
<!-- END CANVAS  -->
</div>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-ui/jquery-ui.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/jquery.jqscribble.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath() ?>/public/js/jqscribble.extrabrushes.js" type="text/javascript"></script>
<script>
	$(document).ready(function()
	{
		$("#monitoreo").jqScribble();
		 $("#monitoreo").data("jqScribble").update({backgroundImage: "<?php echo $this->basePath(); ?>/public/img/cuadro_monitoreo.png"});
	});

	</script>