<div class="card">
	<div class="card-head style-primary">
		<div class="tools">
			<a class="btn btn-icon-toggle ink-reaction" href="" onclick="agregaOrden();">
                <i class="fa fa-plus"></i>
            </a>
		</div>
	</div>
	<div class="card-body">
		<form class="form form-validate" id="formOrden" novalidate="novalidate">
			<input type="hidden" name="consultaid" value="<?php echo $cons; ?>">
			<input type="hidden" name="datosOrden">
			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
						<input type="text" class="form-control" id="ordenes" name="orden">
						<label for="orden">ORDENES</label>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
						<textarea id="ckeditor" name="datos"></textarea>
					</div>
				</div>
			</div>
		</form>
		<div class="card-actionbar">
			<div class="card-actionbar-row">
				<button type="button" class="btn btn-raised btn-primary ink-reaction" onclick="guardarorden()" id="saveOrden">Guardar</button>
			</div>
		</div>
	</div>
</div>
<form action="#" class="form" id="agendaConsulta">

	<input type="hidden" name="start" id="start">
	<input type="hidden" name="end" id="end">
	<input type="hidden" name="className" id="className">
	<input type="hidden" name="idevento" id="idevento">
	<input type="hidden" name="idpaciente" id="idpaciente">
	
	<div class="modal fade" id="modAgendarcon" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-lg">
	    <div class="modal-content">
	      	<div class="modal-header">
	        	<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
	        	<h4 class="modal-title">
	        		Cita
	        	</h4>
	      	</div>
	      	<div class="modal-body">
	      	<div class="row">

	      		<div class="col-sm-4"></div>
	      		<div class="col-sm-4"></div>
	      		<div class="col-sm-4">
	      			<span class="text-medium text-primary pull-right"><p class="form-control-static" id="quien"></p></span>
	      		</div>
	      	</div>
	      		<div class="row">
	      			<div class="col-sm-4">
	      				<div class="form-group">
	      					<label>Fecha</label>
	      					<input class="form-control" type="date" id="cFecha">	
	      				</div>
	      				
	      			</div>
	      			<div class="col-sm-4">
	      				<div class="form-group">
	      					<label>Inicio:</label>
	      					<input class="form-control" type="time" id="desde">	
	      				</div>	      				
	      			</div>
	      			<div class="col-sm-4">
	      				<div class="form-group">
	      					<label>Fin: </label>
	      					<input class="form-control col-sm-4" type="time" id="hasta">	
	      				</div>	      				
	      			</div>	
	      		</div>      							
				<div class="row">
					<div class="col-sm-6">							
						<div class="form-group">
							<input type="text" class="form-control" id="title" name="title">
							<label for="title">PACIENTE</label>	
						</div>							
					</div>
					<div class="col-sm-3">
						<div class="form-group">
							<input type="text" class="form-control" id="edad" name="edad">
							<label for="edad">EDAD</label>	
						</div>						
					</div>
					<!-- <div class="col-sm-3" style="margin-bottom:10px">
					    <button id="bNuevopaciente" type="button" class="btn btn-default btn-raised glyphicon glyphicon-user" onclick="pacientesModal()" style="margin-top:23px;padding:6px 12px"> Registrar</button>
					</div> -->	
				</div>
				<div class="row">
					<div class="col-sm-6">
						<div class="form-group">
							<input type="text" class="form-control" name="referido" id="referidopor">
							<label for="referidopor">REFERIDO POR</label>	
						</div>							
					</div>
					<div class="form-group col-sm-4">
						<select name="scargo" class="form-control" id="sCargo">
							<option value="1">PARTICULAR</option>
							<option value="2">BANCO
							<option value="3">IMSS</option>
							<option value="4">CORTESÍA</option>
						</select>
						<label for="sCargo">CARGO</label>
					</div>												
				</div>										
				<div class="row">
					<div class="col-sm-6">
						<div class="form-group">
							<input type="text" class="form-control" id="telefono1" name="telefono1">
							<label for="telefono1">TELÉFONO 1</label>	
						</div>
						
					</div>
					<div class="col-sm-6">
						<div class="form-group">
							<input type="text" class="form-control" id="telefono2" name="telefono2">
							<label for="telefono2">TELÉFONO 2</label>	
						</div>						
					</div>					
				</div>	
				<div class="row">
					<div class="form-group" id='color-evento'>
						<div class="col-sm-12" >
							<i class="fa fa-circle fa-2x text-primary" onclick="color('','Consulta de primera vez');"></i>
							<i class="fa fa-circle fa-2x text-warning" onclick="color('event-warning','Consulta de seguimiento');"></i>
							<i class="fa fa-circle fa-2x text-blue" onclick="color('event-blue','Retiro de puntos');"></i>
							<i class="fa fa-circle fa-2x text-success" onclick="color('event-success','Aplicación de Zoladex');"></i>
							<i class="fa fa-circle fa-2x text-rosa" onclick="color('event-rosa','Resultados');"></i>
							<i class="fa fa-circle fa-2x text-accent" onclick="color('event-morado','Orden de Internamiento');"></i>
							<i class="fa fa-circle fa-2x text-lima" onclick="color('event-lima','Llenar Informe');"></i>
							<i class="fa fa-circle fa-2x text-cafe" onclick="color('event-cafe','Procedimiento Especial');"></i>
							<i class="fa fa-circle fa-2x text-danger" onclick="color('event-danger','Embarazo');"></i>
							<i class="fa fa-circle fa-2x text-rosota" onclick="color('event-rosota','Aplicación de Pellets');"></i>
							<i class="fa fa-circle fa-2x text-azul-gris" onclick="color('event-azul-gris','Cirugía');"></i>
							<i class="fa fa-circle fa-2x text-azul-cielo" onclick="color('event-azul-cielo','Capacitación');"></i>
						</div>
					</div>
				</div>
								
	      	</div>
	      	<div class="modal-footer">
	      		<a href="#" onclick="borrarevento();" id="lBorrar" style="float:left">Eliminar evento</a>
	        	<button type="button" class="btn btn-primary" id="btnGuardarcita">GUARDAR</button>        
	      	</div>
	    </div>
	  </div>
	</div>
</form>
<input type="hidden" id="id_orden">	
<input type="hidden" id="id_consul">


<script src="<?php echo $this->basePath() ?>/public/js/libs/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/ckeditor/adapters/jquery.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/select2/select2.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-ui/jquery-ui.min.js"></script>


<script>
	var ruta = '<?php echo $this->basePath() ?>/';
	$(document).ready(function() {
		$( '#ckeditor' ).ckeditor();
	});

	function guardarorden()
	{
		
		var contenido = CKEDITOR.instances['ckeditor'].getData();
		$('#datosOrden').val(contenido);
		var formulario = $('#formOrden').serialize();
		$.ajax({
			    type: "POST",
			    url: "<?php echo $this->basePath() ?>/consultados/guardarorden",
			    dataType: "json",
			    data: formulario,
			    success: function(respuesta) {
			      $('#id_orden').val(respuesta['ordenid']);
			       $('#id_consul').val(respuesta['consultation']);
			       //verOrden();
			    },
			    error: function(){
			          toastr.error('Ocurrió un error, inténtelo más tarde.');
			    }
			});
	}

	function verOrden(){
		window.open('generaorden/'+$('#id_orden').val());
	}
</script>