<div class="card">
<div class="card-head style-primary"></div>
<div class="card-body">
	<form class="form form-validate" id="formReceta" novalidate="novalidate">
		<input type="hidden" name="consultaid" value="<?php echo $consulta; ?>">
		<input type="hidden" id="array-med" name="array-med">
		<div class="row">
			<div class="col-md-9"></div>
			<div class="col-md-3">
				<div class="form-group">
					<input type="text" class="form-control" id="fechahoy2" name="fechahoy2">
					<label for="fechahoy">Fecha</label>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<input type="text" class="form-control" id="medicamento" >
					<label for="medicamento">Medicamento</label>
				</div>
			</div>
			<div class="col-md-6">
				<div class="form-group">
					<input type="text" class="form-control" id="presc" >
					<label for="presc">Prescripción</label>
				</div>
			</div>
		</div>
		<div style="float:right;margin-top:10px;">
            <button type="button" class="btn btn-floating-action btn-primary" onclick="agregar();"><i class="fa fa-plus"></i></button>
         </div>
		<div class="row">
			<div class="col-md-12">
				<table class="table table-striped" id="table-med-receta"   method="post">
	              <thead>
	                <tr id="tr" name="tabla">
	                  <th>Nombre/Sal</th>
	                  <th>Prescripción</th>
	                </tr>
	              </thead>
	              <tbody class="medicam">
	              </tbody>
	            </table>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<input type="text" class="form-control" id="indicaciones" name="indicaciones">
					<label for="indicaciones">Indicaciones Generales</label>
				</div>
			</div>
		</div>
	</form>
	<div class="card-actionbar">
		<div class="card-actionbar-row">
			<button type="button" class="btn btn-raised btn-primary ink-reaction" onclick="guardarreceta()" id="saveReceta">Guardar</button>
		</div>
	</div>
</div>
<input type="hidden" id="id_receta">	
<input type="hidden" id="id_consul">

<script>
	var contador = 0;
	$(document).ready(function() {
		fechaActual2();
    });

	function fechaActual2()
	{
		var today = new Date();
	    var dd = today.getDate();
	    var mm = today.getMonth()+1; 
	    var yyyy = today.getFullYear();

	    if(dd<10){
	        dd='0'+dd
	    } 
	    if(mm<10){
	        mm='0'+mm
	    } 
	    var today = dd+'-'+mm+'-'+yyyy;

	    $('#fechahoy2').val(today);
	}

	function agregar(){
	  var med = document.getElementById("medicamento").value;
	  var presc = document.getElementById("presc").value;
	  contador++;

	  if(med != "" ){
	    
	    var trparaborrar = contador;  
	    $(".table tbody.medicam").append("<tr id='"+contador+"' class='trmedicamento'  >"+
	           "<td id='tdMed'>"+med+"</td>"+
	           "<td id='tdFrec'>"+presc+"</td>"+"<td><span class='glyphicon glyphicon-remove' onclick = 'myDeleteFunction(\""+trparaborrar+"\");' style='float:right;color:crimson'></span>"+"</td>"+
	           "</tr>");
	    var med = document.getElementById("medicamento").value = "";
	    var presc = document.getElementById("presc").value = "";
	  }
	  else{ 
	  	alert("Faltan campos de agregar");
	  }
	}

	function myDeleteFunction(trborrar){
	  $('#'+trborrar).remove();
	}

	function guardarreceta(){
		  var medicamentos = {};
		  
		  for(i=1; i<= document.getElementById("table-med-receta").rows.length-1; i++){
			cadena = document.getElementById("table-med-receta").rows[i].id;
			tractual = cadena;
			medicamentos[i] = {};
			medicamentos[i]['MEDICAMENTO'] = $('#'+tractual+' #tdMed').text();
			medicamentos[i]['PRESC'] = $('#'+tractual+' #tdFrec').text();
			 
			
		  }
		  	medicamentos= JSON.stringify(medicamentos);
		  	$('#array-med').val(medicamentos);
		    var datastring = $('#formReceta').serialize();

			$.ajax({
			    type: "POST",
			    url: "<?php echo $this->basePath() ?>/consultados/guardareceta",
			    dataType: "json",
			    data: datastring,
			    success: function(respuesta) {
			       console.log(respuesta);
			       $('#id_receta').val(respuesta['recetaid']);
			       $('#id_consul').val(respuesta['consulta']);
			       console.log(respuesta['recetaid']);
			       verReceta();
			    },
			    error: function(){
			          alert('Ocurrió un error, inténtelo más tarde.');
			    }
			});
	}

	function verReceta(){
		window.open('generareceta/'+$('#id_receta').val());
	}
</script>