<div class="card">
	<div class="card-body ">
		<?php if(count($recetas)!= 0){ ?>
		<div class="row text-primary">
			<div class="col-md-12">
				<h4 class="text-primary">Recetas</h4>
					<?php foreach($recetas as $rece){ ?>
						<ul class="list divider-full-bleed">
							<li class="tile">
								<a class="tile-content ink-reaction" onclick="verReceta(<?php echo $rece['ID'];?>);">
									<div class="tile-icon">
										<i class="md md-receipt"></i>
									</div>
									<div class="tile-text">
										<?php echo date_format($rece['FECHA_INICIO'],'Y-m-d') ?>
									</div>
								</a>
							</li>
						</ul>
					<?php } ?>
			</div>
		</div>
		<?php } ?>
		<div class="row">
			<div class="col-md-7">
				<div class="form-group">
					<h4 class="text-primary">Motivo consulta</h4>
					<p class="form-control-static"><?php echo $consultag[0]['MOTIVO_CONS'];?></p>
				</div>
			</div>
			<div class="col-md-2"></div>
			<div class="col-md-3">
				<div class="form-group">
					<h4 class="text-primary">Fecha</h4>
					<p class="form-control-static"><?php echo date_format($consultag[0]['FECHA_CONS'],'Y-m-d');?></p>	
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2">
				<div class="form-group">
					<div class="input-group">
						<div class="input-group-content">
							<h4 class="text-primary">Edad</h4>
							<p class="form-control-static"><?php echo $consultag[0]['EDAD'];?></p>
						</div>
						<span class="input-group-addon">años</span>
					</div>
				</div>
				<div class="form-group">
					<h4 class="text-primary">Ciclo</h4>
					<?php if(isset($consultag[0]['CICLO'])){ ?>
					<p class="form-control-static"><?php echo $consultag[0]['CICLO'];?></p>
					<?php } ?>
				</div>
				<div class="form-group">
					<h4 class="text-primary">FUM</h4>
					<?php if(isset($consultag[0]['FUM'])){ ?>
					<p class="form-control-static"><?php echo date_format($consultag[0]['FUM'],'Y-m-d');?></p>
					<?php }  ?>
				</div>
				<div class="row">
					<div class="col-sm-2">
						<div class="form-group">
							<h4 class="text-primary">G</h4>
							<?php if(isset($consultag[0]['GESTAS'])){ ?>
							<p class="form-control-static"><?php echo $consultag[0]['GESTAS'];?></p>
							<?php } ?>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="form-group">
							<h4 class="text-primary">P</h4>
							<?php if(isset($consultag[0]['PARTOS'])){ ?>
							<p class="form-control-static"><?php echo $consultag[0]['PARTOS'];?></p>
							<?php } ?>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="form-group">
							<h4 class="text-primary">C</h4>
							<?php if(isset($consultag[0]['CESAREAS'])){ ?>
							<p class="form-control-static"><?php echo $consultag[0]['CESAREAS'];?></p>
							<?php } ?>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="form-group">
							<h4 class="text-primary">A</h4>
							<?php if(isset($consultag[0]['ABORTOS'])){ ?>
							<p class="form-control-static"><?php echo $consultag[0]['ABORTOS'];?></p>
							<?php } ?>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="form-group">
							<h4 class="text-primary">E</h4>
							<?php if(isset($consultag[0]['ECTOPICOS'])){ ?>
							<p class="form-control-static"><?php echo $consultag[0]['ECTOPICOS'];?></p>
							<?php } ?>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-2"></div>
			<div class="col-sm-5"></div>
			<div class="col-sm-3">
				
				<div class="form-group">
					<div class="input-group">
						<div class="input-group-content">
							<h4 class="text-primary">Tiroides</h4>
							<?php if(isset($consultag[0]['TIROIDESNUM'])){ ?>
							<p class="form-control-static"><?php echo $consultag[0]['TIROIDESNUM'];?></p>
							<?php } ?>
						</div>
						<span class="input-group-addon">ml U/L</span>
					</div>
				</div>
				<div class="form-group">
					<div class="input-group">
						<div class="input-group-content">
							<h4 class="text-primary">Peso</h4>
							<?php if(isset($consultag[0]['PESO'])){ ?>
							<p class="form-control-static"><?php echo $consultag[0]['PESO'];?></p>
							<?php } ?>
							</div>
						<span class="input-group-addon">Kg</span>
					</div>
				</div>
				<div class="form-group">
					<div class="input-group">
						<div class="input-group-content">
							<h4 class="text-primary">Presión</h4>
							<?php if(isset($consultag[0]['PRESION'])){ ?>
							<p class="form-control-static"><?php echo $consultag[0]['PRESION'];?></p>
							<?php } ?>
							</div>
						<span class="input-group-addon">mmHg</span>
					</div>
				</div>
				<div class="form-group">
					<div class="list-results list-results-underlined">
						<div class="col-xs-12">
							<div id="linkas" class="links">
								<div>
									<?php if($fotos){ ?>
										<?php foreach($fotos as $fl) { ?>
											<?php $nomfil = explode('.',$fl['IMAGEN']);?>
											<a href="<?php echo $this->basePath() ?>/public/imagenes/consultas/<?php echo $pacin[0].'/fotos/'.$fl['IMAGEN']; ?>" title="Galería" data-gallery=""><img src="<?php echo $this->basePath() ?>/public/imagenes/consultas/<?php echo $pacin[0].'/fotos/'.$nomfil[0].'.'.$nomfil[1].'_th.'.$nomfil[2]; ?>"></a>
										<?php } ?>
									<?php } ?>
								</div>
								<div id="blueimp-gallery" class="blueimp-gallery">
								    <div class="slides"></div>
								    <h3 class="title"></h3>
								    <ol class="indicator"></ol>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<hr>
		<div class="row">
			<?php if(isset($consultag[0]['IMAGEN'])){ ?>
			<img src="<?php echo $this->basePath(); ?>/public/imagenes/consultas/<?php echo $pacin[0];?>/<?php echo $consultag[0]['IMAGEN'];?>" alt="" style="max-width: 100%;,max-height: 100%;">
			<?php } ?>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<h4 class="text-primary">Plan</h4>
					<?php if(isset($consultag[0]['PLAN'])){ ?>
					<p class="form-control-static"><?php echo $consultag[0]['PLAN'];?></p>
					<?php } ?>
				</div>
			</div>
			<div class="col-md-6">
				<div class="form-group">
					<h4 class="text-primary">IMX</h4>
					<?php if(isset($consultag[0]['IMX'])){ ?>
					<p class="form-control-static"><?php echo $consultag[0]['IMX'];?></p>
					<?php } ?>
				</div>
			</div>
		</div>
	</div><!--end .card-body -->
	
</div><!--end .card -->

<div id="prescription" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Receta Medica</h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-9"></div>
					<div class="col-md-3">
						<div class="form-group">
							<h4 class="text-primary">Fecha</h4>
							<p class="form-control-static" id="FechaReceta"></p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<table class="table table-striped" id="table-med-receta">
			              <thead>
			                  <th class="text-primary">Nombre/Sal</th>
			                  <th class="text-primary">Prescripción</th>
			              </thead>
			              <tbody class="medicam">
			              </tbody>
			            </table>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<h4 class="text-primary">Indicaciones Generales</h4>
							<p class="form-control-static" id="indicaciones"></p>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<!-- <button type="button" class="btn btn-primary btn-ok" id="Imprime">Imprimir</button> -->
			</div>
		</div>
	</div>
</div>
<script>
	document.getElementById('linkas').onclick = function (event) {
	    event = event || window.event;
	    var target = event.target || event.srcElement,
	        link = target.src ? target.parentNode : target,
	        options = {index: link, event: event},
	        links = this.getElementsByTagName('a');
	    blueimp.Gallery(links, options);
	}; 

	function verReceta(id)
	{
		$.ajax({
			    type: "POST",
			    url: "<?php echo $this->basePath() ?>/consultados/verprescript",
			    dataType: "json",
			    data: {id:id},
			    success: function(response) {
			        console.dir(response);
			        $('#medicam').html('');
			     
			        $('#indicaciones').text(response['receta'][0].INDICACIONES_ADICIONALES);
			        var fecha   = response['receta'][0].FECHA_INICIO.date;
	       			var arr 	= fecha.split(" ");
	       			var mes 	= arr[0];
	       			var separa  = mes.split("-"); 
	       			var Mes 	= separa[2];
	       			var dia 	= separa[1];
	       			var anio 	= separa[0];
	       			$('#FechaReceta').text(dia + "-" + Mes + "-" + anio);

			        var medicinas = response['medicinas'];
			        var total = medicinas.length;
			      	
	                for (var i = 0, len = total; i < len; i++) {
	                  $(".table tbody.medicam").append("<tr class='trmedicamento'  >"+
				           "<td id='tdMed'>"+response['medicinas'][0]['MEDICAMENTO'].NOMBRE +"</td>"+
				           "<td id='tdFrec'>"+response['medicinas'][0].FRECUENCIA+"</td>"+
				           "</tr>");
	                  
	                }
					$("#prescription").modal('show');

			    },
			    error: function(){
			          toastr.error('Ocurrió un error, inténtelo más tarde.');
			    }
			});
	} 
</script>