
<?php if($imgs){ ?>
<img src="<?php echo $this->basePath(); ?>/public/imagenes/consultas/<?php echo $patientito;?>/<?php echo $imgs[0]['IMAGEN'];?>" alt="" style="max-width: 100%;,max-height: 100%;">
<img src="<?php echo $this->basePath(); ?>/public/imagenes/consultas/<?php echo $patientito;?>/<?php echo $imgs[1]['IMAGEN'];?>" alt="" style="max-width: 100%;,max-height: 100%;">	
<?php }else{ ?>
	<div class="card">
			<div class="card-body ">
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<h4 class="text-primary">Motivo Consulta</h4>
							<p class="form-control-static"><?php echo $consultah[0]['PADECIMIENTO'];?></p>
						</div>
					</div>
					<div class="col-md-3"></div>
					<div class="col-md-3">
						<div class="form-group">
							<h4 class="text-primary">Fecha</h4>
							<p class="form-control-static"><?php echo date_format($consultah[0]['FECHA_CONS'],'Y-m-d');?></p>	
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-5">
						<div class="row">
							<div class="col-sm-6">
								<div class="form-group">
									<h4 class="text-primary">Ciclo</h4>
									<?php if(isset($consultah[0]['CICLOS'])){ ?>
										<?php if($consultah[0]['CICLOS'] == 1){ ?>
											<p class="form-control-static">REGULAR</p>
										<?php }else{ ?>
											<p class="form-control-static">IRREGULAR</p>
										<?php } ?>
									<?php } ?>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="form-group">
									<h4 class="text-primary">FUM</h4>
									<?php if(isset($consultah[0]['FUM'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['FUM'];?></p>
									<?php }  ?>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-2">
								<div class="form-group">
									<h4 class="text-primary">G</h4>
									<?php if(isset($consultah[0]['GESTAS'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['GESTAS'];?></p>
									<?php } ?>
								</div>
							</div>
							<div class="col-sm-2">
								<div class="form-group">
									<h4 class="text-primary">P</h4>
									<?php if(isset($consultah[0]['PARTOS'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['PARTOS'];?></p>
									<?php } ?>
								</div>
							</div>
							<div class="col-sm-2">
								<div class="form-group">
									<h4 class="text-primary">C</h4>
									<?php if(isset($consultah[0]['CESAREAS'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['CESAREAS'];?></p>
									<?php } ?>
								</div>
							</div>
							<div class="col-sm-2">
								<h4 class="text-primary">A</h4>
									<?php if(isset($consultah[0]['ABOTOS'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['ABOTOS'];?></p>
									<?php } ?>
							</div>
							<div class="col-sm-2">
								<div class="form-group">
									<h4 class="text-primary">E</h4>
									<?php if(isset($consultah[0]['ECTOPICOS'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['ECTOPICOS'];?></p>
									<?php } ?>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-3">
								<div class="form-group">
									<h4 class="text-primary">MENARCA</h4>
									<?php if(isset($consultah[0]['MENARCA'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['MENARCA'];?></p>
									<?php } ?>
								</div>
							</div>
							<div class="col-sm-3">
								<div class="form-group">
									<h4 class="text-primary">IVSA</h4>
									<?php if(isset($consultah[0]['IVSA'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['IVSA'];?></p>
									<?php } ?>
								</div>
							</div>
							<div class="col-sm-3">
								<div class="form-group">
									<h4 class="text-primary">DURACIÓN</h4>
									<?php if(isset($consultah[0]['DURACION'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['DURACION'];?></p>
									<?php } ?>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="row">
								<?php if($consultah[0]['PRIMERHIJO_NOMBRE']){ ?>
								<div class="form-group col-sm-3">
									<div class="checkbox checkbox-styled checkbox-success">
										<label>
											<input type="checkbox" value="" disabled="" checked="checked">
											<span class="text-primary">PRIMER HIJO</span>
										</label>
									</div>		
								</div>
								<div class="form-group col-sm-12" id="hijoUno">
									<div>
										<div>
											<h5>NOMBRE </h5>
											<p class="form-control-static"><?php echo $consultah[0]['PRIMERHIJO_NOMBRE'];?></p>
											<br>
										</div>	
										<div>
											<h5>EDAD </h5>
											<p class="form-control-static"><?php echo $consultah[0]['PRIMERHIJO_EDAD'];?></p>
										</div>											
									</div>
								</div>
								<?php } ?>
								<?php if($consultah[0]['SEGUNDOHIJO_NOMBRE']){ ?>
								<div class="form-group col-sm-3">
									<div class="checkbox checkbox-styled checkbox-success">
										<label>
											<input type="checkbox" value="" disabled="" checked="checked">
											<span class="text-primary">SEGUNDO HIJO</span>
										</label>
									</div>		
								</div>
								<div class="form-group col-sm-12" id="hijoDos">
									<div>
										<div>
											<h5>NOMBRE </h5>
											<p class="form-control-static"><?php echo $consultah[0]['SEGUNDOHIJO_NOMBRE'];?></p>
											<br>
										</div>	
										<div>
											<h5>EDAD </h5>
											<p class="form-control-static"><?php echo $consultah[0]['SEGUNDOHIJO_EDAD'];?></p>
										</div>											
									</div>
								</div>
								<?php } ?>
								<?php if($consultah[0]['TERCERHIJO_NOMBRE']){ ?>
								<div class="form-group col-sm-3">
									<div class="checkbox checkbox-styled checkbox-success">
										<label>
											<input type="checkbox" value="" disabled="" checked="checked">
											<span class="text-primary">TERCER HIJO</span>
										</label>
									</div>		
								</div>
								<div class="form-group col-sm-12" id="hijoTres">
									<div>
										<div>
											<h5>NOMBRE </h5>
											<p class="form-control-static"><?php echo $consultah[0]['TERCERHIJO_NOMBRE'];?></p>
											<br>
										</div>	
										<div>
											<h5>EDAD </h5>
											<p class="form-control-static"><?php echo $consultah[0]['TERCERHIJO_EDAD'];?></p>
										</div>											
									</div>
								</div>
								<?php } ?>
							</div>
						</div>
						<div class="row">
							<?php if($consultah[0]['DISMENORREA']){ ?>
							<div class="form-group col-sm-4">
								<div class="checkbox checkbox-styled checkbox-success">
									<label>
										<input type="checkbox" value="" disabled="" checked="checked">
										<span class="text-primary">DISMENORREA</span>
									</label>
								</div>		
							</div>
							<div class="form-group col-sm-12" id="adisme">
								<p class="form-control-static"><?php echo $consultah[0]['DISMENORREA'];?></p>
							</div>
							<?php } ?>
						</div>
						<div class="row">
							<?php if($consultah[0]['FLUJO']){ ?>
							<div class="form-group col-sm-4">
								<div class="checkbox checkbox-styled checkbox-success">
									<label>
										<input type="checkbox" value="" disabled="" checked="checked">
										<span class="text-primary">FLUJO</span>
									</label>
								</div>		
							</div>
							<div class="form-group col-sm-12" id="aflu" >
								<p class="form-control-static"><?php echo $consultah[0]['FLUJO'];?></p>
							</div>
							<?php } ?>											
						</div>
						<div class="row">
							<?php if($consultah[0]['SIST_URINARIO']){ ?>
							<div class="form-group col-sm-4">
								<div class="checkbox checkbox-styled checkbox-success">
									<label>
										<input type="checkbox" value="" disabled="" checked="checked">
										<span class="text-primary">SISTEMA URINARIO</span>
									</label>
								</div>		
							</div>
							<div class="form-group col-sm-12" id="asistU">
								<p class="form-control-static"><?php echo $consultah[0]['SIST_URINARIO'];?></p>
							</div>
							<?php } ?>
						</div>
						<div class="row">
							<?php if($consultah[0]['SIST_DIGESTIVO']){ ?>
							<div class="form-group col-sm-4">
								<div class="checkbox checkbox-styled checkbox-success">
									<label>
										<input type="checkbox" value="" disabled="" checked="checked">
										<span class="text-primary">SISTEMA DIGESTIVO</span>
									</label>
								</div>		
							</div>
							<div class="form-group col-sm-12" id="asistU">
								<p class="form-control-static"><?php echo $consultah[0]['SIST_DIGESTIVO'];?></p>
							</div>
							<?php } ?>
						</div>
						<div class="row">
							<?php if($consultah[0]['ANTICONCEPTIVOS']){ ?>
							<div class="form-group col-sm-4">
								<div class="checkbox checkbox-styled checkbox-success">
									<label>
										<input type="checkbox" value="" disabled="" checked="checked">
										<span class="text-primary">ANTICONCEPTIVOS</span>
									</label>
								</div>		
							</div>
							<div class="form-group col-sm-12" id="asistU">
								<p class="form-control-static"><?php echo $consultah[0]['ANTICONCEPTIVOS'];?></p>
							</div>
							<?php } ?>
						</div>
						<div class="row">
							<?php if($consultah[0]['PAP']){ ?>
							<div class="form-group col-sm-4">
								<div class="checkbox checkbox-styled checkbox-success">
									<label>
										<input type="checkbox" value="" disabled="" checked="checked">
										<span class="text-primary">PAP</span>
									</label>
								</div>		
							</div>
							<div class="form-group col-sm-12" id="asistU">
								<p class="form-control-static"><?php echo $consultah[0]['PAP'];?></p>
							</div>
							<?php } ?>
						</div>
						<div class="row">
							<?php if($consultah[0]['GALACTORREA']){ ?>
							<div class="form-group col-sm-4">
								<div class="checkbox checkbox-styled checkbox-success">
									<label>
										<input type="checkbox" value="" disabled="" checked="checked">
										<span class="text-primary">GALACTORREA</span>
									</label>
								</div>		
							</div>
							<div class="form-group col-sm-12" id="asistU">
								<p class="form-control-static"><?php echo $consultah[0]['GALACTORREA'];?></p>
							</div>
							<?php } ?>
						</div>
						<div class="row">
							<?php if($consultah[0]['HIRSUTISM']){ ?>
							<div class="form-group col-sm-4">
								<div class="checkbox checkbox-styled checkbox-success">
									<label>
										<input type="checkbox" value="" disabled="" checked="checked">
										<span class="text-primary">HIRSUTISMO</span>
									</label>
								</div>		
							</div>
							<div class="form-group col-sm-12" id="asistU">
								<p class="form-control-static"><?php echo $consultah[0]['HIRSUTISM'];?></p>
							</div>
							<?php } ?>
						</div>
						<div class="row">
							<?php if($consultah[0]['COH']){ ?>
							<div class="form-group col-sm-4">
								<div class="checkbox checkbox-styled checkbox-success">
									<label>
										<input type="checkbox" value="" disabled="" checked="checked">
										<span class="text-primary">COH-HAM</span>
									</label>
								</div>		
							</div>
							<div class="form-group col-sm-12" id="asistU">
								<p class="form-control-static"><?php echo $consultah[0]['COH'];?></p>
							</div>
							<?php } ?>
						</div>
						
						<div class="row">
							<?php if($consultah[0]['ESPERMO_FECHA']){ ?>
							<div class="form-group col-sm-4">
								<div class="checkbox checkbox-styled checkbox-success">
									<label>
										<input type="checkbox" value="" disabled="" checked="checked">
										<span class="text-primary">ESPERMOGRAMA</span>
									</label>
								</div>		
							</div>
							<div class="form-group col-sm-10 " id="divaespermo">
								<div class="form-group col-sm-3">
									<div>
										<h5>Fecha</h5>
										<p class="form-control-static"><?php echo $consultah[0]['ESPERMO_FECHA'];?></p><br>
									</div>
									<div>
										<h5>Motivilidad</h5>
										<p class="form-control-static"><?php echo $consultah[0]['ESPERMO_MOTIVIDAD'];?></p><br>
									</div>
									<div>
										<h5>Cultivo</h5>
										<p class="form-control-static"><?php echo $consultah[0]['ESPERMO_CULTIVO'];?></p><br>
									</div>
								</div>
								<div class="form-group col-sm-3">
									<div>
										<h5>Cuenta</h5>
										<p class="form-control-static"><?php echo $consultah[0]['ESPERMO_CUENTA'];?></p><br>
									</div>
									<div>
										<h5>FN</h5>
										<p class="form-control-static"><?php echo $consultah[0]['ESPERMO_FN'];?></p><br>
									</div>
									<div>
										<h5>APP</h5>
										<p class="form-control-static"><?php echo $consultah[0]['ESPERMO_APP'];?></p><br>
									</div>
								</div>
								<div class="form-group col-sm-3">
									<div>
										<h5>VOLUMEN</h5>
										<p class="form-control-static"><?php echo $consultah[0]['ESPERMO_VOLUMEN'];?></p><br>
									</div>
									<div>
									<br>
										<h5>Fragmentación DNA</h5>
										<p class="form-control-static"><?php echo $consultah[0]['ESPERMO_DNA'];?></p><br>
									</div>
								</div>
							</div>
							<?php } ?>
						</div>
						<div class="row">
							<?php if($consultah[0]['LABORATORIO_NOTAS']){ ?>
							<div class="form-group col-sm-4">
								<div class="checkbox checkbox-styled checkbox-success">
									<label>
										<input type="checkbox" value="" disabled="" checked="checked">
										<span class="text-primary">LABORATORIO</span>
									</label>
								</div>		
							</div>
							<div class="form-group col-sm-12" id="asistU">
								<p class="form-control-static"><?php echo $consultah[0]['LABORATORIO_NOTAS'];?></p>
							</div>
							<?php } ?>
						</div>
					</div>
					<div class="col-sm-4"></div>
					<div class="col-sm-3">
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-content">
									<h4 class="text-primary">Edad</h4>
									<p class="form-control-static"><?php echo $consultah[0]['EDAD'];?></p>
								</div>
								<span class="input-group-addon">años</span>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-content">
									<h4 class="text-primary">Tiroides</h4>
									<?php if(isset($consultah[0]['TIROIDESNUM'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['TIROIDESNUM'];?></p>
									<?php } ?>
								</div>
								<span class="input-group-addon">ml U/L</span>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-content">
									<h4 class="text-primary">Peso</h4>
									<?php if(isset($consultah[0]['PESO'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['PESO'];?></p>
									<?php } ?>
								</div>
								<span class="input-group-addon">Kg</span>
							</div>
						</div>
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-content">
									<h4 class="text-primary">Presión</h4>
									<?php if(isset($consultah[0]['PRESION'])){ ?>
									<p class="form-control-static"><?php echo $consultah[0]['PRESION'];?></p>
									<?php } ?>
								</div>
								<span class="input-group-addon">mmHg</span>
							</div>
						</div>
						<div class="form-group">
							<h4 class="text-primary">IMX</h4>
							<?php if(isset($consultah[0]['IMX'])){ ?>
							<p class="form-control-static"><?php echo $consultah[0]['IMX'];?></p>
							<?php } ?>
						</div>
						<div class="form-group">
							<h4 class="text-primary">Plan</h4>
							<?php if(isset($consultah[0]['PLAN'])){ ?>
							<p class="form-control-static"><?php echo $consultah[0]['PLAN'];?></p>
							<?php } ?>
						</div>
					</div>
					
				</div>
				<hr>
				<div class="row">
					<?php if(isset($consultah[0]['IMAGEN'])){ ?>
					<img src="<?php echo $this->basePath(); ?>/public/imagenes/consultas/<?php echo $patientito;?>/<?php echo $consultah[0]['IMAGEN'];?>" alt="" style="max-width: 100%;,max-height: 100%;">
					<?php } ?>
				</div>
				
				
			</div><!--end .card-body -->
	</div>

<?php } ?>

