<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Registo de Usuario</title>

		<!-- BEGIN META -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="keywords" content="your,keywords">
		<meta name="description" content="Short explanation about this website">
		<!-- END META -->

		<!-- BEGIN STYLESHEETS -->
		<link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css'/>
		<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/bootstrap.css?1422792965" />
		<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/materialadmin.css?1425466319" />
		<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/font-awesome.min.css?1422529194" />
		<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/material-design-iconic-font.min.css?1421434286" />
		<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/summernote/summernote.css?1425218701" />

		
		<!-- END STYLESHEETS -->

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script type="text/javascript" src="../../js/libs/utils/html5shiv.js?1403934957"></script>
		<script type="text/javascript" src="../../js/libs/utils/respond.min.js?1403934956"></script>
		<![endif]-->
	</head>
	<body class="menubar-hoverable header-fixed ">
		
		<!-- BEGIN LOGIN SECTION -->
		<section class="section-account">
			<div class="img-backdrop" style="background-image: url('<?php echo $this->basePath() ?>/public/img/img16.jpg')"></div>
			<div class="spacer"></div>
			<div class="card contain-sm style-transparent">
				<div class="card-body">
					<div class="row">
						<div class="col-sm-6">
							<br/>
							
							<span class="text-lg text-bold text-primary">Registro de Usuario</span>
							<br/><br/>
							<form id="sesion" class="form form-validate floating-label" action="/exclie_star/registro" accept-charset="utf-8" method="post" novalidate="novalidate">	

							<div class="row">
              <div class="col-xs-6 col-md-6">
                <?php
                 // $element = $form->get('usaurio');
                  //echo $this->formPassword($element);
                  //echo $this->formElementErrors($element);
                ?>
              </div>


								<div class="form-group">
									<input type="text" class="form-control" id="usuario" name="usuario" required data-rule-minlength="6">
									<label for="usuario">Usuario</label>
								</div>
								<div class="form-group">
									<input type="text" class="form-control" id="nombre" name="nombre" required>
									<label for="nombre">Nombre Completo</label>
								</div>
								<div class="form-group">
									<input type="email" class="form-control" id="email" name="email" required>
									<label for="email">Correo Electrónico</label>									
								</div>

								<div class="form-group">
									<input type="text" class="form-control"  id="telefono" name="telefono" data-inputmask="'mask': '999-999-9999'">
									<label for="telefono">Teléfono</label>												
								</div>

								<div class="form-group">
									<input type="password" name="password" id="password" class="form-control" required="" data-rule-minlength="8">
									<label for="password1" class="control-label">Contraseña</label>
								</div>							
								
								<div class="form-group">
									<input type="password" name="passwordrepeat" id="passwordrepeat" class="form-control" data-rule-equalto="#password" required="">
									<label for="passwordrepeat" class="control-label">Verificar Contraseña</label>
								</div>

								<div class="form-group">
												<select id="rol" name="rol" class="form-control" required>
												<option value="">&nbsp;</option>
												<?php foreach ($roles as $key => $rol): ?>
													<option value="<?php echo $rol['id'] ?>"><?php echo $rol['name'];?></option>
												<?php endforeach ?>	
												</select>
												<label for="rol">Rol que desempeña</label>
											</div>

								<div class="form-group" id="skills">
												<ul class="list-unstyled" id="skillsList"></ul>
												<div class="form-group">
													<a class="btn btn-raised btn-default-bright" data-duplicate="skillTmpl" data-target="#skillsList!">ADD NEW skill</a>
												</div><!--end .form-group -->
											</div>



								<div class="form-group">
												<textarea name="motivo" id="motivo" class="form-control" rows="2" required></textarea>
												<label for="motivo">Motivo por el cual es necesario tener acceso al sistema</label>
											</div>
								<br/>
								<div class="row">
									<div class="col-xs-12 text-left">
										<!--<div class="checkbox checkbox-inline checkbox-styled">
											<label>
											<input type="checkbox"> <span>Recordarme</span>
											</label>
										</div>
									</div>end .col -->
									<div class="col-xs-12 text-right">
										<button class="btn btn-primary btn-raised" type="submit">Registrar</button>
									</div><!--end .col -->
								</div><!--end .row -->
							</form>
						</div><!--end .col -->
								
							</div><!--end .row -->
						</div>

						<!--end .card-body -->
					</div><!--end .card -->
				</section>
				<!-- END LOGIN SECTION -->

				<script type="text/html" id="skillTmpl">
			<li class="clearfix">
				
						<div class="form-group">
							<input type="text" class="form-control" id="skill-<%=index%>" name="skill-<%=index%>">
							<label for="skill-<%=index%>">Skill <%=index%></label>
						</div>
				
					<div class="col-xs-4">
						<div class="form-group">
							<select name="skill-rating-<%=index%>" class="form-control">
								<option value=""></option>
								<option value="100">100</option>
								<option value="90">90</option>
								<option value="80">80</option>
								<option value="70">70</option>
								<option value="60">60</option>
								<option value="50">50</option>
								<option value="40">40</option>
								<option value="30">30</option>
								<option value="20">20</option>
								<option value="10">10</option>
							</select>
							<label for="skill-rating-<%=index%>">Rating</label>
						</div>
					</div>
				
			</li>
		</script>




				<!-- BEGIN JAVASCRIPT -->      
				
				<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery/jquery-1.11.2.min.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery/jquery-migrate-1.2.1.min.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/libs/bootstrap/bootstrap.min.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/libs/spin.js/spin.min.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/libs/autosize/jquery.autosize.min.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/libs/nanoscroller/jquery.nanoscroller.min.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/core/source/App.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/core/source/AppNavigation.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/core/source/AppOffcanvas.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/core/source/AppCard.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/core/source/AppForm.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/core/source/AppNavSearch.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/core/source/AppVendor.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/core/demo/Demo.js"></script>	
				<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-validation/dist/jquery.validate.min.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/libs/inputmask/jquery.inputmask.bundle.min.js"></script>
				<script src="<?php echo $this->basePath() ?>/public/js/core/demo/DemoFormComponents.js"></script>						   		
				<!-- END JAVASCRIPT -->

			</body>
		</html>		