	<div class="section-body">		
		<!-- BEGIN FORM WIZARD -->
		<div class="row">
			<div class="col-lg-12">
				<div class="card">
					<div class="card-head style-primary">
						<header>Registro de paciente</header>
					</div>
					<div class="card-body ">
						<div id="rootwizard1" class="form-wizard form-wizard-horizontal">
							<form class="form floating-label">
								<div class="form-wizard-nav">
									<div class="progress"><div class="progress-bar progress-bar-primary"></div></div>
									<ul class="nav nav-justified">
										<li class="active"><a href="#tab1" data-toggle="tab"><span class="step">1</span> <span class="title">GENERAL</span></a></li>
										<li><a href="#tab2" data-toggle="tab"><span class="step">2</span> <span class="title">ANTECEDENTES</span></a></li>
										<li><a href="#tab3" data-toggle="tab"><span class="step">3</span> <span class="title">FINALES</span></a></li>
									</ul>
								</div><!--end .form-wizard-nav -->
								<div class="tab-content clearfix">
									<div class="tab-pane active" id="tab1">
										<div>
											<label class="radio-inline radio-styled">
												<input type="radio" name="gendre"><span>MASCULINO</span>
											</label>
											<label class="radio-inline radio-styled">
												<input type="radio" name="gendre" checked><span>FEMENINO</span>
											</label>
										</div>
										<br/>
										<div class="row">						
											<div class="col-sm-4">
												<div class="form-group floating-label">
													<input type="text" class="form-control input-lg" id="Lastname1">
													<label for="Lastname1">APELLIDO PATERNO</label>
												</div>
											</div>
											<div class="col-sm-4">
												<div class="form-group floating-label">
													<input type="text" class="form-control input-lg" id="Lastname1">
													<label for="Lastname1">APELLIDO MATERNO</label>
												</div>
											</div>
											<div class="col-sm-4">
												<div class="form-group floating-label">
													<input type="text" class="form-control input-lg" id="Firstname1">
													<label for="Firstname1">NOMBRE(s)</label>
												</div>
											</div>
										</div>
										<div class="row">						
											<div class="col-sm-4">
												<div class="form-group floating-label">
													<select class="form-control input-lg" name="sEstado" id="sEstados">
														<?php foreach ($estados as $key => $estado): ?>
															<option value="<?php echo $estado['ID'] ?>" 
															<?php if ($estado['ID'] == 8): // Chihuahua predefinido ?>
																selected
															<?php endif ?>><?php echo $estado['NOMBRE']; ?></option>
														<?php endforeach ?>
													</select>
													<label for="Lastname1">CIUDAD</label>
												</div>
											</div>
											<div class="col-sm-4">
												<div class="form-group floating-label">
													<select class="form-control input-lg" name="sEstado" id="sEstados">
														<?php foreach ($municipios as $key => $municipio): ?>
															<option value="<?php echo $municipio['ID'] ?>" 
															<?php if ($municipio['ID'] == 233): // Chihuahua predefinido ?>
																selected	
															<?php endif ?>><?php echo $municipio['NOMBRE']; ?></option>
														<?php endforeach ?>
													</select>
													<label for="Lastname1">MUNICIPIO</label>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-sm-6">
												<div class="form-group floating-label">
													<input type="text" class="form-control input-lg" id="Lastname1">
													<label for="Lastname1">DIRECCION</label>
												</div>
											</div>
											<div class="col-sm-3">
												<div class="form-group floating-label">
													<input type="text" class="form-control input-lg" id="Lastname1">
													<label for="Lastname1">NUM EXT.</label>
												</div>
											</div>
											<div class="col-sm-3">
												<div class="form-group floating-label">
													<input type="text" class="form-control input-lg" id="Lastname1">
													<label for="Lastname1">NUM INT.</label>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-sm-4">
												<div class="form-group floating-label">
													<input type="text" class="form-control input-lg" id="Lastname1">
													<label for="Lastname1">COLONIA</label>
												</div>
											</div>
											<div class="col-sm-4">
												<div class="form-group floating-label">
													<input type="text" class="form-control input-lg" id="Lastname1">
													<label for="Lastname1">TELÉFONO 1</label>
												</div>
											</div>
											<div class="col-sm-4">
												<div class="form-group floating-label">
													<input type="text" class="form-control input-lg" id="Lastname1">
													<label for="Lastname1">TELÉFONO 2</label>
												</div>
											</div>
										</div>
										<div class="row">						
											<div class="col-sm-4">
												<div class="form-group floating-label">
													<input type="text" class="form-control input-lg" id="Lastname1">
													<label for="Lastname1">OCUPACIÓN</label>
												</div>
											</div>

											<div class="col-sm-4">
												<div class="form-group floating-label">
													<select class="form-control input-lg" name="sEstadocivil" id="sEstadocivil">
														<option value="1">Soltero(a)</option>
														<option value="2">Casado(a)</option>
														<option value="3">Viudo(a)</option>
													</select>
													<label for="Firstname1">ESTADO CIVIL</label>
												</div>
											</div>
											
											<div class="col-sm-4">
												<div class="form-group floating-label">
													<select class="form-control input-lg" name="sTipoSanguineo" id="sTipoSanguineo">
														<option value="9">Desconoce</option>
														<option value="1">O+</option>
														<option value="2">A+</option>
														<option value="3">O-</option>
														<option value="4">B+</option>
														<option value="5">A-</option>
														<option value="6">B-</option>
														<option value="7">AB+</option>
														<option value="8">AB-</option>
													</select>
													<label for="Lastname1">TIPO DE SANGRE</label>
												</div>
											</div>						
										</div>																				
									</div><!--end #tab1 -->

									<!-- EMPIEZAN ANTECEDENTES -->
									<div class="tab-pane" id="tab2">
										<div class="row">
											<div class="form-group">
												<div class="col-sm-6">
												
													<label class="checkbox-inline checkbox-styled">
														<input type="checkbox">
														<span>Fuma</span>
													</label>
													

													<input type="text" class="form-control input-lg" id="Lastname1">
													<label for="Lastname1">QUE TANTO FUMA?</label>
													

													<label class="checkbox-inline checkbox-styled">
														<input type="checkbox">
														<span>Bebe alcohol</span>
													</label>
													
														
												</div>																					
											</div>
										</div>
										
						
									</div><!--end #tab2 -->
									<div class="tab-pane" id="tab3">
										<br/><br/>
										<div class="form-group">
											<input type="text" name="URL" id="URL" class="form-control">
											<label for="URL" class="control-label">URL</label>
											<p class="help-block">Starts with http://</p>
										</div>
										<div class="form-group">
											<input type="text" name="rangelength" id="rangelength" class="form-control">
											<label for="rangelength" class="control-label">Range restriction</label>
											<p class="help-block">Between 5 and 10</p>
										</div>
									</div><!--end #tab3 -->									
								</div><!--end .tab-content -->
								<ul class="pager wizard">									
									<li class="previous"><a class="btn-raised" href="javascript:void(0);">Atrás</a></li>									
									<li class="next"><a class="btn-raised" href="javascript:void(0);">Siguiente</a></li>
								</ul>
							</form>
						</div><!--end #rootwizard -->
					</div><!--end .card-body -->
				</div><!--end .card -->				
			</div><!--end .col -->
		</div><!--end .row -->
</div><!--end .section-body -->


	<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/wizard/wizard.css" />
	<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/jquery-ui/jquery-ui-theme.css" />
	<script src="<?php echo $this->basePath() ?>/public/js/libs/wizard/jquery.bootstrap.wizard.min.js"></script>
	<script src="<?php echo $this->basePath() ?>/public/js/exclie/pacientes.js"></script>
	<script src="<?php echo $this->basePath() ?>/public/js/core/demo/DemoFormWizard.js"></script>
	<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-ui/jquery-ui.min.js"></script>
