<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/rickshaw/rickshaw.css?1422792967" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/morris/morris.core.css?1420463396" />
<script src="<?php echo $this->basePath() ?>/public/js/core/demo/Demo.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/core/demo/DemoDashboard.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/sparkline/jquery.sparkline.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/d3/d3.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/d3/d3.v3.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/rickshaw/rickshaw.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.time.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.resize.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.orderBars.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.pie.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/curvedLines.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/spin.js/spin.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-knob/jquery.knob.min.js"></script>

<section>
     <div class="section-body">
        <div class="row">

            <!-- BEGIN ALERT - BOUNCE RATES -->
            <div class="col-md-4 col-sm-6">
                <a href="<?php echo $this->basePath() ?>/agenda" >
                <div class="card">
                    <div class="card-body no-padding">
                        <div class="alert alert-callout alert-info no-margin">
                            <strong class="pull-right text-xl"><i class="fa fa-calendar"></i></strong>
                            <strong class="text-xl">Agenda</strong><br/>
                            <span class=""></span>
                            <div class="stick-bottom-left-right">
                                <div class="progress progress-hairline no-margin">
                                    <div class="progress-bar progress-bar-info" style="width:43%"></div>
                                </div>
                            </div>
                        </div>
                    </div><!--end .card-body -->
                </div><!--end .card -->
                </a>
            </div><!--end .col -->
            <!-- END ALERT - BOUNCE RATES -->

            

            <!-- BEGIN ALERT - BOUNCE RATES -->
            <div class="col-md-4 col-sm-6">
                <a href="<?php echo $this->basePath() ?>/consultados" >
                <div class="card">
                    <div class="card-body no-padding">
                        <div class="alert alert-callout alert-success no-margin">
                            <strong class="pull-right text-xl"><i class="fa fa-stethoscope"></i></strong>
                            <strong class="text-xl">Consultas</strong><br/>
                            <span class=""></span>
                            <div class="stick-bottom-left-right">
                                <div class="progress progress-hairline no-margin">
                                    <div class="progress-bar progress-bar-success" style="width:43%"></div>
                                </div>
                            </div>
                        </div>
                    </div><!--end .card-body -->
                </div><!--end .card -->
                </a>
            </div><!--end .col -->
            <!-- END ALERT - BOUNCE RATES -->

            <!-- BEGIN ALERT - BOUNCE RATES -->
            <div class="col-md-4 col-sm-6">
                <a href="<?php echo $this->basePath() ?>/pacientes" >
                <div class="card">
                    <div class="card-body no-padding">
                        <div class="alert alert-callout alert-warning no-margin">
                            <strong class="pull-right text-xl"><i class="fa fa-user-plus"></i></strong>
                            <strong class="text-xl">Pacientes</strong><br/>
                            <span class=""></span>
                            <div class="stick-bottom-left-right">
                                <div class="progress progress-hairline no-margin">
                                    <div class="progress-bar progress-bar-warning" style="width:43%"></div>
                                </div>
                            </div>
                        </div>
                    </div><!--end .card-body -->
                </div><!--end .card -->
                </a>
            </div><!--end .col -->
            <!-- END ALERT - BOUNCE RATES -->

        </div><!--end .row -->
        
        
    </div><!--end .section-body -->
</section>