<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/rickshaw/rickshaw.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/theme-default/libs/morris/morris.core.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() ?>/public/css/estilos.css" />
<script src="<?php echo $this->basePath() ?>/public/js/core/demo/Demo.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/sparkline/jquery.sparkline.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/d3/d3.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/d3/d3.v3.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/rickshaw/rickshaw.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.time.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.resize.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.orderBars.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/jquery.flot.pie.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/flot/curvedLines.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/spin.js/spin.min.js"></script>
<script src="<?php echo $this->basePath() ?>/public/js/libs/jquery-knob/jquery.knob.min.js"></script>


     <div class="section-body">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <img src="<?php echo $this->basePath();?>/public/img/gine.png" alt="" class="p" style="align-content: center;">
                        </div>
                        <div class="col-md-6">
                            <br><br><br>
                            <br><br><br>
                            <?php if($this->identity()->getRole()->getId()==1 || $this->identity()->getRole()->getId()==2 || $this->identity()->getRole()->getId()==3 || $this->identity()->getRole()->getId()==5){ ?>
                            <div class="row">
                                <div class="col-md-6">
                                    <a href="<?php echo $this->basePath() ?>/agenda" >
                                    <div class="card card-bordered style-primary">
                                        <div class="card-body">
                                            <strong class="pull-right text-xl"><i class="fa fa-calendar fa-2x"></i></strong>
                                            <strong class="text-xl">Agenda</strong><br/>
                                        </div><!--end .card-body -->
                                    </div><!--end .card -->
                                    </a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <a href="<?php echo $this->basePath() ?>/pacientes" >
                                    <div class="card card-bordered style-primary">
                                        <div class="card-body">
                                            <strong class="pull-right text-xl"><i class="fa fa-user-plus fa-2x"></i></strong>
                                            <strong class="text-xl">Pacientes</strong><br/>
                                        </div><!--end .card-body -->
                                    </div><!--end .card -->
                                    </a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <a href="<?php echo $this->basePath() ?>/consultados/listapaciente" >
                                    <div class="card card-bordered style-primary">
                                        <div class="card-body">
                                            <strong class="pull-right text-xl"><i class="fa fa-download fa-2x"></i></strong>
                                            <strong class="text-xl">Descarga de Expediente</strong><br/>
                                        </div><!--end .card-body -->
                                    </div><!--end .card -->
                                    </a>
                                </div>
                            </div>
                            
                            
                            <?php } ?>
                            <?php if($this->identity()->getRole()->getId()==1 || $this->identity()->getRole()->getId()==2 || $this->identity()->getRole()->getId()==3 ){ ?>
                            <div class="row">
                                <div class="col-md-6">
                                    <a href="<?php echo $this->basePath() ?>/consultados" >
                                    <div class="card card-bordered style-primary">
                                        <div class="card-body">
                                            <strong class="pull-right text-xl"><i class="fa fa-stethoscope fa-2x"></i></strong>
                                            <strong class="text-xl">Consultas</strong><br/>
                                        </div><!--end .card-body -->
                                    </div><!--end .card -->
                                    </a>
                                </div>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--end .row -->
    </div><!--end .section-body -->
